### ISSUE TITLE
New Scrapper RadVideo - Wait until Cody tests it

### ISSUE THREAD

**Issue by JPH71** [CodyBerenson/PGMA-Modernized#10]
@CodyBerenson 

Hi Cody 

Here is the new RadVideo bundle along with GayAdult and GayAdultFilms.
I have also included GEVI as there was one line introducing an error that kept showing up in the logs even though it did not affect its operation

[4 bundles.zip](https://github.com/CodyBerenson/PGMA-Modernized/files/4467362/4.bundles.zip)

**Comment by JPH71** [comment]
@CodyBerenson 
Just made the necessary changes to radvideo... to stop it going into a loop....
made changes to gaydvdempire to correctly scrape collections
and gevi as mentioned in previous email... but i had forgotten to up the version....
also included are gayadult/gayadultfilms.... i haven't uped the version as the changes were not in the __init__.py script

off to bed it's 04h10 here........

happy testing
[5 bundles.zip](https://github.com/CodyBerenson/PGMA-Modernized/files/4467825/5.bundles.zip)

**Comment by CodyBerenson** [comment]
@jph71 
I threw half a dozen movies at RAD, all matched.  Since it has some limited titles compared to some of the other sites, i was only able to find 6 titles...but I feel that it is good enough.  :)

I'm going to test GEVI now, and if it passes, I'll push all to the master repository

**Comment by JPH71** [comment]
Brilliant xx
Just going to have a late lunch then start on IAFD

**Comment by CodyBerenson** [comment]
Hi @JPH71 

i'm unable to get a match on gaydvdempire....

I'm not sure if this matched with the old code or not.  I'm going to do some more testing.

Here's the film:

(Channel 1 Releasing) - My Sister's Husband (1996).mp4

Entry in GDVDE:

https://www.gaydvdempire.com/1639656/my-sisters-husband-gay-porn-movies.html?partner_id=56800950

**Comment by CodyBerenson** [comment]
Hi @JPH71 
This movie successfully matched using the previous code, but not the new code.  :(

**Comment by CodyBerenson** [comment]
I'm still testing, but I haven't run into any more issues.  GayDVDEmpire doesn't add the tagline to the metadata....I had thought we addressed this....but oh well.

**Comment by CodyBerenson** [comment]
spoke too soon.  another film that won't match:

(Bijou Classics) - One in a Billion (1984).mpg

https://www.gaydvdempire.com/1888284/one-in-a-billion-porn-videos.html

**Comment by CodyBerenson** [comment]
and, i just reverted code and that last movie, too, matches with the old code.  So, that's two failures with the new code that the old code handled perfectly.  Sorry buttercup.

**Comment by JPH71** [comment]
Before GayDVDEmpire had a preference that you could match against either
production year or release date...
I took this option if i can remember after mentioning it to you asking if
you used the production year...
What I am going to do is get the scrapper to check both the release year
and the production date........ that should sort out that issue.
This issue would have resulted before depending on the preference you chose.

Which version of gaydvdempire have you reverted to??

I will sort out the change now..... iafd search really runs slow... but at
least the site seems to behave properly with no stupid buttons....

**Comment by CodyBerenson** [comment]
i just revered to the version that's in the master repository...here's the bundle:

[GayDVDEmpire.bundle.zip](https://github.com/CodyBerenson/PGMA-Modernized/files/4471958/GayDVDEmpire.bundle.zip)

**Comment by JPH71** [comment]
@CodyBerenson 
I have sped it up - it no longer needs to do another request to find the release date... and made the xpath more exact... this title My Sister's husband was a good one to test all the code as i realised at one stage it was looking at the same title released by next door studios 

it now searches past the first page of results too

Tagline had an error in it from the early days when i was a python newbie - it was supposed to set the tagline like in the other agents to the video url if it did not find an actual video tagline. 
however, 

if couldn't find the video tagline it just skipped and went ahead....
Tagline is now set as video url - unless there is a tagline element in the video url page

My new logic is as follows
check title = site site titlecheck studio = site titlecheck year = production year - this gives the default date as 31st dec yyyy
if the release date year = production year - use the release date as it will have day and month also thus release date will only be used if it is within 366 days of the 31st dec production year

here is the latest gaydvdempire agent
[GayDVDEmpire.bundle.zip](https://github.com/CodyBerenson/PGMA-Modernized/files/4472580/GayDVDEmpire.bundle.zip)

**Comment by CodyBerenson** [comment]
youre amazing. will test tomorrow!

**Comment by CodyBerenson** [comment]
@JPH71 

Good afternoon (evening for you) buttercup.  I threw a bakers dozen films at GayDVDEmpire.  All matched perfectly, quickly.

So, i will push the Rad, the updated GEVI, the updated GDVDE, and GA & GF bundles to the master repo

**Comment by CodyBerenson** [comment]
Master Repository updated.  I'll close this issue in a day or so.  :)  

You did good, my friend!

**Comment by JPH71** [comment]
Brilliant....
I will start on IAFD this evening... It's a darned slow website when
manually using it...
But looks easy to scrape...
I am glad I did RadVideo as it picked up loads of my unmatchable stuff...

I hope you approved of the logic in relation to production/release dates..

J xxx

**Comment by CodyBerenson** [comment]
No surprise that its so slow.  The gay content is probably about 10% of the dirty movies out there.  lol.  I wish there was a way to segregate.

**Comment by JPH71** [comment]
Yep...
Any ideas on any other sites/blogs that could do with a scrapping agent?

**Comment by JPH71** [comment]
I will look into cade's workout now and get back to you

**Comment by j-ktz** [comment]
Thank you!
