### ISSUE TITLE
Fagalicious - Title Won't Match

### ISSUE THREAD

**Issue by j-ktz** [CodyBerenson/PGMA-Modernized#101]
Can't get this scene to match: [(Fun-Size Boys) - Legrand Wolf, Cole Blue and Ian Levine in “Follow-up Visit” (2021)](https://fagalicious.com/fun-size-boys-legrand-wolf-cole-blue-ian-levine-follow-up-visit/)

Log: 
[com.plexapp.agents.Fagalicious.log](https://github.com/CodyBerenson/PGMA-Modernized/files/6489171/com.plexapp.agents.Fagalicious.log)

**Comment by CodyBerenson** [comment]
Hi @j-ktz hope you are well and behaving!

Hmmmm...this did match for me.  Did you download the latest Fagalicious?  It was pushed yesterday in resolution to other Fagalicious issues....

Please advise.

**Comment by JPH71** [comment]
hey @j-ktz <https://github.com/j-ktz>

You are using the old version.
Also install ffmpeg - to help with duration matching

**Comment by j-ktz** [comment]
@CodyBerenson Ah! Didn't see the new release. Yup. That got it to match. @JPH71 Hmmm, I think I already have it installed. Tell me more about duration matching?

**Comment by JPH71** [comment]
I introduced Duration matching to cater for the fact that IAFD has scenes
and full film titles with the same names.
So when you match a film it sometimes picks the scene instead of the film
on IAFD and therefore does not get extra information in relation to the
cast and their roles, As the the scene would have fewer actors than the
whole movie.

A second reason is that sometimes and very very rarely you can have the
same movie title for two films by the same studio...
A classic case which has irritated me for ages is *(Hot House) - Hole
Busters (2010)* and  *(Hot House) - Hole Busters 1 (2010)* from the hole
buster series that runs from 1 to 10....
The previous matching always meant that it did not pick the series, the
only difference is their duration and successful matching depends on this.

As Films and Scenes come from different sources, I have allowed that there
could be differences in time either plus or minus... this is catered for in
the preferences


Jason xx

**Comment by j-ktz** [comment]
@JPH71 Sounds awesome! So I need to tweak my preferences and also download and install FFMPEG? Do I install that on my NAS (where Plex is installed)?

**Comment by JPH71** [comment]
That would be the most likely place for it to go - so long as it's in the
path

**Comment by j-ktz** [comment]
Having an issue with this one too: [(AmateurGayPOV) - Klein Kerr in “My Daughter’s Boyfriend” (2021)](https://fagalicious.com/amateurgaypov-klein-kerr-my-daughters-boyfriend/
[com.plexapp.agents.Fagalicious.log](https://github.com/CodyBerenson/PGMA-Modernized/files/6516135/com.plexapp.agents.Fagalicious.log)
)

**Comment by CodyBerenson** [comment]
Interesting, I just tested it, matched fine for me.

![image](https://user-images.githubusercontent.com/40373801/118992113-58034c00-b952-11eb-9b64-62221a7f12bd.png)

In the meantime...maybe stop/restart PMS and/or try a fix match?

**Comment by vampirelayer** [comment]
Jesus that poster!

**Comment by CodyBerenson** [comment]
I know, right?  so hot even the masking couldn't obscure it...had to go back and triple mask it.  LOL

**Comment by j-ktz** [comment]
@CodyBerenson Hmm so strange! It seems like when I add a new folder for a studio, Plex thinks the name of the file is the folder name. Could have something to do with it. Have you run into that?

**Comment by j-ktz** [comment]
@CodyBerenson I just tried it again (with more videos in the folder) and still no dice. The debug says it's looking for the scene at "https://fagalicious.com/search/%22klein+kerr+in+my%22" which returns no results too.

**Comment by JPH71** [comment]
@CodyBerenson <https://github.com/CodyBerenson> and @j-ktz
<https://github.com/j-ktz>

Hi guys, sorry that I have not been my responsive self... halfway through a
72hr working week and by the time I get home after each 12hr shift my eyes
feel like they are rattling in my head. As they say in this part of Belgium
in dialectic French... *"I am so tired, my eyes are like the slit on a
cat's vulva"...* Lord knows who went exploring to come up with that one!
I finish my sentence on Sunday, so after birthday drinks with a colleague,
I will start working on it next week...
skip that - I just checked it with the klein kerr title and it works...
the debug log returns : SEARCH:: Search Query:
https://fagalicious.com/search/klein+kerr+in as it splits at the first *["]* it
finds...
I did a direct cut and paste of the scene title of the webpage...

Could you try this - if it still does not work - I will figure something
else out - the way I build the search string is rather historical and may
need a review as fagalicious has changed time and time again...

The Title I used is this:* (AmateurGayPOV) - Klein Kerr in “My Daughter’s
Boyfriend” (2021)* with all the curly apostrophes included.

Jason

**Comment by j-ktz** [comment]
@JPH71 Thanks for trying! I just copy/pasted your text and nada. 

[com.plexapp.agents.Fagalicious.log](https://github.com/CodyBerenson/PGMA-Modernized/files/6519228/com.plexapp.agents.Fagalicious.log)

**Comment by vampirelayer** [comment]
I have followed @JPH71 advice and changed the quotes I copied copied from Fagalicious to the double quotes from my keyboard and it works. 

They seem to be different characters even both are semantically the same.

Try that.

**Comment by j-ktz** [comment]
@vampirelayer Thx for trying! Idk why I'm the problem child. So far I've tried:
- Rebooting PMS
- Downloading and replacing ALL plugins
- Making sure multiple video files are in the folder
- Title with straight quotes and curly quotes

I give up LOL

**Comment by CodyBerenson** [comment]
You can always match using either the QueerClick entry or the IADF entry and swap out the poster.

**Comment by j-ktz** [comment]
@CodyBerenson I didn't see it on IAFD but I matched witch QC and then changed the title and poster in Plex cause QC was so  messy. 😆 TY!!!!

**Comment by CodyBerenson** [comment]
@j-ktz the only reason I knew it was on IAFD because i was trying to figure out who in the hell the top was....and IAFD didn't include it.  :(

https://www.iafd.com/title.rme/title=my+daughter%27s+boyfriend/year=2021/my_daughter%27s_boyfriend.htm

**Comment by vampirelayer** [comment]
My guess is Manuel Skye is the top. Also a personal favourite!

**Comment by JPH71** [comment]
@j-ktz - I will be looking at fagalicious - its search string formulation
needs an overhaul... I noticed from your log that it was not creating the
search string correctly...

@CodyBerenson <https://github.com/CodyBerenson>  reopen this issue!
