### ISSUE TITLE
WayBig causing error on NVIDIA Sheild

### ISSUE THREAD

**Issue by InSanniti** [CodyBerenson/PGMA-Modernized#103]
Get the attached error in Waybig bundle on NVIDIA shield running the latest PMS. Same version works fine on my Windows 10 PMS

2021-05-26 02:23:11,272 (254c2bd4f0) :  CRITICAL (agentkit:1095) - Exception in the update function of agent named 'WayBig (IAFD)', called with guid 'com.plexapp.agents.GayAdult://36740?lang=xn' (most recent call last):
  File "/data/data/com.plexapp.mediaserver.smb/Resources/Plug-ins-d0ce30438/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/api/agentkit.py", line 1093, in _update
    agent.update(obj, media, lang, **kwargs)
  File "/storage/emulated/0/Android/data/com.plexapp.mediaserver.smb/Plex Media Server/Plug-ins/WayBig.bundle/Contents/Code/__init__.py", line 402, in update
    FILMDICT = ast.literal_eval(metadata.id)    # use ast.literal_eval does not convert strings to unicode
AttributeError: 'module' object has no attribute 'literal_eval'

**Comment by InSanniti** [comment]
[com.plexapp.agents.WayBig.log](https://github.com/CodyBerenson/PGMA-Modernized/files/6541581/com.plexapp.agents.WayBig.log)

**Comment by JPH71** [comment]
Please update to the latest version and try that first - then let me know
if you are still having the same errors....
delete the folder with the current agent
download the new agent from github, set your preferences...
install ffmpeg if you want to use duration matching
...
if it still errors send me the logs!

Jason

**Comment by InSanniti** [comment]
Hi JPH71, yes it is using the latest already. Although I redownloaded, deleted and put the new download in it's place.. The same log errors show when it finds a match

**Comment by CodyBerenson** [comment]
@InSanniti please attach the log file.  Thanks.

**Comment by InSanniti** [comment]
Attached is a recreate of the issue just now with the latest versions
[com.plexapp.agents.WayBig.log](https://github.com/CodyBerenson/PGMA-Modernized/files/6566987/com.plexapp.agents.WayBig.log)

**Comment by JPH71** [comment]
I will look into it this week!
Cheers

**Comment by JPH71** [comment]
@InSanniti : This issue shoudl now have been resolved... I was going through all the issues this evening...
Please confirm and we can close this...
