### ISSUE TITLE
IAFD - Scenes / Chapters

### ISSUE THREAD

**Issue by jocklover** [CodyBerenson/PGMA-Modernized#104]
Is there handling for scenes / chapters on IAFD?

I have separate files for each scene of a video. IAFD lists each scene within the movie, not separately. For obvious reasons I would like to avoid naming each file with the same name to get a match.

Here is the IAFD listing: https://www.iafd.com/title.rme/title=blake+ellis%3a+total+submission/year=2019/blake-ellis-total-submission.htm

(Some content from Dream Boy Bondage is available from other sources as separate scenes but not this one and some others.)

Thanks for a great tool!

**Comment by JPH71** [comment]
Plex handles multi-part movies quite well...

I would simply name the movie as:
(Dream Boy Bondage) - Blake Ellis- Total Submission (2019) - Part 1.mp4
(Dream Boy Bondage) - Blake Ellis- Total Submission (2019) - Part 2.mp4
(Dream Boy Bondage) - Blake Ellis- Total Submission (2019) - Part 3.mp4

This way it shows up as only one entry in Plex.
*N.B - if you have collections enabled and you do not want a "Blake Ellis"
collection being created follow "Blake Ellis" with a hyphen (-) directly...
no space between the two*

Jason

**Comment by jocklover** [comment]
Thank you @JPH71  for the tip on Plex joining parts! Using the parts nomenclature I was able to get Plex to join most of the files. However, Parts 1, 10 & 11 are not joining.
Also, I am still not getting a match to the IAFD record.

File list:
![image](https://user-images.githubusercontent.com/57208899/124218480-e6293100-dabf-11eb-8434-81ac300227ef.png)

**Comment by CodyBerenson** [comment]
Hi @jocklover !

Per Plex documentation, Only stacks up to 8 parts are supported.
https://support.plex.tv/articles/naming-and-organizing-your-movie-media-files/

In these cases, Plex recommends joining the files outside of plex and they provide an unofficial guide and tool recommendation.  

Personally, I use avidemux
http://avidemux.sourceforge.net/

If all of the files are similar filetypes, similar dimensions tools such as avidemux do this really quickly, without re-encoding.  

Cheers!

**Comment by JPH71** [comment]
Hi @jocklover <https://github.com/jocklover>

I use mkvtoolkit to join files

Join files that are continuous and are off the same video dimensions

Jason

**Comment by jocklover** [comment]
Apologies, it looks like I led the topic in the wrong direction - my ultimate goal is not to join files.
I am looking for a way to get PGMA to recognize individual scenes of a movie. I thought there was a file nomenclature that could be used for scenes.
IAFD lists all scenes for each DBB movie under one title, but I have typically found the scenes in separate files and am hoping for a way for PGMA to recognize them.
Thanks!

**Comment by JPH71** [comment]
As Cody mentioned - you can only have a maximum of 8 separate scenes
stacked into one title.
That's why I think three of your parts were not recognised. Try adding the
parts 1 by 1 and see where it starts breaking down

**Comment by jocklover** [comment]
Is there a way that I can name a file such that PGMA matches it to IAFD?
Can PGMA ignore certain portions of a file name such that I can name each as a Scene (Part / Chapter / etc) and it still match to a movie in IAFD.
Is this functionality built into the existing code? Can it be added?
Is it an update to the RegEx (which I have no familiarity with)?

I am not concerned about stacking / joining / etc.

**Comment by CodyBerenson** [comment]
Hi @jocklover 
I believe I'm confused about the challenge you're having.  Are you saying you aren't able to match this file in IAFD at all?  My responses to your questions below.
> 
> Is there a way that I can name a file such that PGMA matches it to IAFD?

Yes.  In This case, properly naming the file:  (Dream Boy Bondage) - Blake Ellis - Total Submission (2019).mp4 will match against IAFD:

![image](https://user-images.githubusercontent.com/40373801/124389238-4254a680-dcb4-11eb-9116-63e43eec3400.png)


> Can PGMA ignore certain portions of a file name such that I can name each as a Scene (Part / Chapter / etc) and it still match to a movie in IAFD.

Further, combining Plex native functionality of stacking with PGMA's matching, you can stack up to 8 files in that match that Plex will recognize as 1 file and play continuously in order:

![image](https://user-images.githubusercontent.com/40373801/124389297-79c35300-dcb4-11eb-92d4-d72d09fea4e2.png)

> Is this functionality built into the existing code? Can it be added?
Stacking is native to Plex, matching as I've shown above is in the PGMA code.

> Is it an update to the RegEx (which I have no familiarity with)?
This is what your RegEx should be set to.  If yours is different and you need to update it, you will need to stop PMS and restart PMS in order for it to take effect.
![image](https://user-images.githubusercontent.com/40373801/124389414-f1917d80-dcb4-11eb-8578-8efb5fbe483b.png)


> I am not concerned about stacking / joining / etc.
That is up to you.  If you have all 10 of your scenes located in the same folder with the only differentiation in filename being Part 0X, Plex will automatically stack.  If you wish to have 10 separate entries in Plex vs 1, you will need to locate each scene in its own folder

Hopefully this clarified.  Happy Independence Day, if you're in the USA.  

Cody

**Comment by jocklover** [comment]
Thank you @CodyBerenson - based on your response, I am naming the files correctly, but they are not still matching.
(Fun fact PLEX has apparently upped the stacking to 9 titles.)

Digging into my library a little more, it looks like may I have a wider issue w/ IAFD matching (that may not have anything to with the parts naming). I am seeing issues with some Military Classified scenes as well.

Examples of MC not matching IAFD:

- (Military Classified) - Carlos- Blowjob (2019).mp4 --> https://www.iafd.com/title.rme/title=carlos%3a+blowjob/year=2019/carlos-blowjob.htm
- (Military Classified) - Astin- Blowjob (2019).mp4 --> https://www.iafd.com/title.rme/title=astin%3a+blowjob/year=2019/astin-blowjob.htm
- (Military Classified) - Brando-Justino- Anal (2019).mp4 --> https://www.iafd.com/title.rme/title=brando-justino%3a+anal/year=2019/brando-justino-anal.htm

(I have tried both "- " & " - " in the title name.)

However, some scenes are matching to IAFD, so PGMA is likely working, _and I'm just missing something?_
Sorry this thread is taking a long and winding path (I can open a separate post if needed).

I know that PGMA can be particular about nomenclature convention but just am not seeing what I am missing.
AND THANKS FOR SUCH GREAT ENGAGMENT ON MY THREAD!

**Comment by CodyBerenson** [comment]
@jocklover I get the same results for these three titles.

@JPH71 Can you look into when you get a chance.  I'm unable to match any of these titles on IAFD as well.   Cheers!

**Comment by CodyBerenson** [comment]
@jocklover if you are still unable to match the Dream Boy Bondage file, Jason will need your specific IAFD log to troubleshoot, since it works fine for us. 

So, please stop your pms, restart it, attempt to fix match against the title, and then attach the log.  Please see the FAQ for where to find the log.

**Comment by jocklover** [comment]
Log attached:
[com.plexapp.agents.IAFD.log](https://github.com/CodyBerenson/PGMA-Modernized/files/6761463/com.plexapp.agents.IAFD.log)
I ran it for the Part 01-09 stacked media, and the Part 10 & Part 11 individual medias.

Looks like it may not handling the "Part ##" portion of the name and failing to match (but not sure).

Here is the RegEx that is in the IAFD settings (I don't know how to ready it and it should still be the default): ^\((?P<studio>.+?)\) - (?P<title>.+?)(?:\s\((?P<year>\d{4})\))?(\s?-\s?(?P<part>(cd|disc|disk|dvd|part|pt).+))?$

It looks like the IAFD agent info says "(v2020-04-22)" but I should have the latest version, the extracted files are dated May 5, 2021 (not sure if there is another way to get the version info).
THANKS FOR ALL THE SUPPORT!

**Comment by JPH71** [comment]
Firstly - You have mentioned looking at the regex in the agents options in
the plex media player...
if you can do this you are not using the latest version as this option to
change regex was removed in the last version and it went into the python
code, as the regex was too complex for people to understand and was never
ever ever changed.

Secondly - your parts are wrong make sure you append *" - Part x"* where x
is a number not as you have done... otherwise this will mess up with the
matching - as you can see in the logs it thinks the title is *Blake Ellis-
Total Submission (2019) Part 10* instead of *Blake Ellis- Total Submission*

*Try the second option first and if you still have problems delete the
agent in the plug-ins folder and download the latest from PGMA*

*If you have the parts correct - Plex will only display one entry... If
there are more than one entry its because Plex may still have a stacking
limit - so match against the none-stacked entry and send me the log!*

*Jason!*

**Comment by jocklover** [comment]
Based on your suggestion I tried " - Part 01"; " - Part 1"; " - Part01" and it looks like it is now querying for "Part 1" as the title in the IAFD web address. Interestingly, using "01" or " 01" allows 9 files to stack (not the limit of 8 listed (https://support.plex.tv/articles/naming-and-organizing-your-movie-media-files/)
[com.plexapp.agents.IAFD.log](https://github.com/CodyBerenson/PGMA-Modernized/files/6767389/com.plexapp.agents.IAFD.log)

I am not sure why I would see the RegEx field - I have the May 15th / Fix #100 version. I even wiped out my Plug-Ins folder and watched PLEX "forget" all the PGMA agents. Then re-added freshly downloaded files (using the posted ZIP) and restarted the PLEX app. Extracted files are dated May 15. And I still see the RegEx field.

**Comment by CodyBerenson** [comment]
@jph71 Moving the three above military classified titles which do not match to a new issue.

**Comment by JPH71** [comment]
My Fault!!


I really thought I had sent in the amended IAFD plugin to Cody for testing
and release and it must have slipped past..

I am working on better title matching - as soon as I have sorted out the
little bugger, Cody will test and release.

Sorry for all the hassle, but at least we now know we have an issue...

I will look at the titles that Cody has put into the issue to help with the
title matching activity I am doing at the moment.

Jason xx

**Comment by jocklover** [comment]
No issue with splitting off the MC matching issues to #105 - glad those titles help.
Any thoughts on the DBB Blake Ellis title not matching? Is that something that should have been resolved in a pending release or going into the #105 fix? Or are we still sorting that out?
Again, appreciate everything - this is amazing to get this support on a project like this!

**Comment by CodyBerenson** [comment]
Have you tried updating your RegEx to what I posted above, stopped your PMS, restarted your PMS, renamed your files to what i posted above, and attempted to rematch?  Here is the link to the specific post above:  https://github.com/CodyBerenson/PGMA-Modernized/issues/104#issuecomment-873605408

Please confirm that you have tried this.  It would help if you include a screen shot of your updated RegEx.  

The DBB title matches fine as I illustrate in the screen shot above, so there is likely something in your configuration that is askew and therefore nothing to be resolved on our side.

**Comment by JPH71** [comment]
Still sorting that out...

I am having an indepth look at IAFD title matching...

1 thing left to tweak....

Jason

**Comment by jocklover** [comment]
I updated the RegEx yesterday and retried the match to no result and was about ready to give up with this week long saga.
BUT then I remembered one tiny little detail you mentioned - "restart PMS". Well, I did that today (which meant rebooting the QNAP because it doesn't properly restart the PMS app... :( )

AND AND AND ... IT WORKED!!! MAGIC!!!
The stacked Part 01 - 09 & the individual parts 10 & 11 all matched up and pulled down their info from IAFD.

THANK YOU SO MUCH!!!
I will close this and look forward to an update on #105.

**Comment by CodyBerenson** [comment]
@jocklover 

Glad to hear it!  FYI, whenever you update bundles, (e.g., when there's a fix to #105), you'll need to restart PMS (in your case I guess reboot your device)....PMS won't recognize a single update to any of the code until its restarted.

**Comment by JPH71** [comment]
@jocklover <https://github.com/jocklover>

Believe you me - that restart malarkey has got me many a time.... I have
stopped writing or rewritten large chunks of code thinking nowt was
working... until the Ah! moment....
