### ISSUE TITLE
IAFD Unable to match titles with Genre in the title

### ISSUE THREAD

**Issue by CodyBerenson** [CodyBerenson/PGMA-Modernized#105]
- (Military Classified) - Carlos- Blowjob (2019).mp4 --> https://www.iafd.com/title.rme/title=carlos%3a+blowjob/year=2019/carlos-blowjob.htm
- (Military Classified) - Astin- Blowjob (2019).mp4 --> https://www.iafd.com/title.rme/title=astin%3a+blowjob/year=2019/astin-blowjob.htm
- (Military Classified) - Brando-Justino- Anal (2019).mp4 --> https://www.iafd.com/title.rme/title=brando-justino%3a+anal/year=2019/brando-justino-anal.htm

_Originally posted by @jocklover in https://github.com/CodyBerenson/PGMA-Modernized/issues/104#issuecomment-873633559_

**Comment by jocklover** [comment]
Some additional titles to test, if needed
![image](https://user-images.githubusercontent.com/57208899/124867100-16bb1000-df83-11eb-9308-d18b165622d0.png)
These are all titles listed on IAFD, and I think I have everything correct in the name.

It seems to be mostly with the titles "Name- Blowjob" but also seeing duos sometimes not hitting (though some do).

Thanks!

**Comment by CodyBerenson** [comment]
Additional IAFD titles. 

(College Boy Physicals) - Balls Deep (2020).mp4 --> https://www.iafd.com/title.rme/title=balls+deep/year=2020/balls-deep.htm
(College Boy Physicals) - X Ray Boner (2020).mp4 --> https://www.iafd.com/title.rme/title=x-ray+boner/year=2020/x-ray_boner.htm

**Comment by CodyBerenson** [comment]
@jocklover 
Hey dude, hope all is well.  I'm working on packaging up a new release.  @jph71 has fixed the IAFD issue that affects these types of filenames.  Please note:  in your screenshot, Barrett is misspelled...I see you tried to trick me.  LOL.  Otherwise, all of the titles in this issue now match.  

Please note:  You are correctly using dash space rather than space dash space for the colon in the title (I am unable to get any of the titles to match using space dash space to replace the colon).

I'll leave this issue open for a couple of days after the release, and then close it.  Cheers.

**Comment by jocklover** [comment]
YES, issue resolved!!! thanks!!!
I did find a few misspelled issues on my part, but massive pairing success.
