### ISSUE TITLE
General Matching Assistance

### ISSUE THREAD

**Issue by jocklover** [CodyBerenson/PGMA-Modernized#106]
I don't think these are related to #105 (but let me know if I'm wrong).
Having a few miscellaneous matching failure and looking for guidance.
Below are the most recent naming tries and record source. I have tried a few other variations but still not getting a match. THANKS

IAFD:
- (Gay Hoopla) - Ryan Love Gets Off Looking At His Asshole In The Mirror (2021).mp4 --> https://www.iafd.com/title.rme/title=ryan+love+gets+off+looking+at+his+asshole+in+the+mirror/year=2021/ryan-love-gets-off-looking-at-his-asshole-in-the-mirror.htm
- (Gay Hoopla) - Ripped Young Construction Worker Jerks Off (2020).mp4 --> https://www.iafd.com/title.rme/title=ripped+young+construction+worker+jerks+off/year=2020/ripped-young-construction-worker-jerks-off.htm
- (College Boy Physicals) - Balls Deep (2020).mp4 --> https://www.iafd.com/title.rme/title=balls+deep/year=2020/balls-deep.htm
- (College Boy Physicals) - X Ray Boner (2020).mp4 --> https://www.iafd.com/title.rme/title=x-ray+boner/year=2020/x-ray_boner.htm

WayBig:
- (GayHoopla) - Matt Mason AKA CreamyGorilla- Mystery Model 70 (2020).mp4 --> https://www.waybig.com/blog/2020/08/24/gayhoopla-matt-mason-mystery-model-70/
- (GayHoopla) - Roman Austin Strokes His Soul Out- The Most Intense Cumshot Ever (2021).mp4 --> https://www.waybig.com/blog/2021/06/07/gayhoopla-roman-austin-strokes-his-soul-out-the-most-intense-cumshot-ever/
- (GayHoopla) - Brock Perry AKA Mystery Model 68- Young Body Builder Jerks Off (2020).mp4 --> https://www.waybig.com/blog/2020/08/10/gayhoopla-mystery-model-68-young-body-builder-jerks-off/
- (GayHoopla) - First Double- Solo- Identical Twins Dee King and Jay King Cum Simultaneously (2021).mp4 --> https://www.waybig.com/blog/2021/03/29/gayhoopla-first-double-solo-identical-twins-dee-king-jay-king-cum-simultaneously/

Again, THANK YOU!

**Comment by CodyBerenson** [comment]
Hi @jocklover thanks for reaching out!

I've tested and have some mixed results.  Some match for me fine with no intervention, some won't match, and some match when properly named.  I'll break this down:

Matched for me in IAFD using your naming:
- (Gay Hoopla) - Ryan Love Gets Off Looking at His Asshole in the Mirror (2021).mp4
- (Gay Hoopla) - Ripped Young Construction Worker Jerks Off (2020)

Won't match for me in IAFD:
- (College Boy Physicals) - Balls Deep (2020).mp4
- (College Boy Physicals) - X Ray Boner (2020).mp4

Matches for me if the correct file names are used.  Note:  you may be overthinking Waybig.  For the most part, its copy, paste, add (YYYY) at the end, and add an open parenthesis at the beginning and substitute a parenthesis dash for the colon.  Here are the properly named files which match perfectly in Waybig:
- (GayHoopla) - Roman Austin Strokes His Soul Out! [The Most Intense Cumshot Ever!] (2021)
- (GayHoopla) - Brock Perry [a.k.a. Mystery Model #68] (Young Body Builder Jerks Off) (2020)
- (Gayhoopla First Double-Solo) - Identical Twins Dee King & Jay King Cum Simultaneously (2021)
- (GayHoopla) - Matt Mason a.k.a. CreamyGorilla [Mystery Model #70] (2020)

Try these file names for WayBig and rematch.  

For the two IAFD that won't match, i'll add to #105.

Hope this helps.

**Comment by CodyBerenson** [comment]
well, crap.  two of the waybig files are confusing github.  here is the screenshot of the properly named files for waybig

![image](https://user-images.githubusercontent.com/40373801/126376761-ea647ab9-4cde-4e97-a849-e276034ce463.png)

**Comment by jocklover** [comment]
Thank you for the follow-up. Those tips solved all of those issues.
- I thought I was seeing issues w/ the [] & # symbols and actually did get a bunch of matches without them.
- Also, ended up switching sources since the Identical Twins was going to need that ridiculous studio title.


Here are more IAFD matching issues. These are absolutely ridiculous titles and I have exactly copied/pasted as well as fiddling with dropping the punctuation. I also tried "Gay Hoopla" and "GayHoopla" (just in case).

It looks like part of the issues I am seeing is that maybe the name is too long? The log is showing no results returned and I have to trim the URL search string to get IAFD to return results in a web browser. [com.plexapp.agents.IAFD.log](https://github.com/CodyBerenson/PGMA-Modernized/files/6866624/com.plexapp.agents.IAFD.log)
These are also listed with the Label as "gayhoopla.com (secret menu)" - do I need to a different studio name?

- (Gay Hoopla) - 2 of Our Newest Superstars Help A Newbie Out Who's Been Having Performance Anxiety. Interesting Tactics Gentlemen (2019).mp4
https://www.iafd.com/title.rme/title=2+of+our+newest+superstars+help+a+newbie+out+who%27s+been+having+performance+anxiety.+interesting+tactics+gentlemen/year=2019/2_of_our_newest_superstars_help_a_newbie_out_who%27s_been_having_performance_anxiety._interesting_tactics_gentlemen.htm
- (Gay Hoopla) - After Hours Hook Up Past Curfew! 2 of 3 Models Unreleased (2020).mp4
https://www.iafd.com/title.rme/title=after+hours+hook+up+past+curfew%21+2+of+3+models+unreleased/year=2020/after_hours_hook_up_past_curfew%21_2_of_3_models_unreleased.htm
- (Gay Hoopla) - Gayhoopla Experience Featuring Canelo Ment and Andre Willis. No Sex in This Video Even Though There Was Penetration... You'll Find Out. Cumshots Included. (2020).mp4
https://www.iafd.com/title.rme/title=gayhoopla+experience+featuring+canelo+ment+and+andre+willis.+no+sex+in+this+video+even+though+there+was+penetration...+you%27ll+find+out.+cumshots+included./year=2020/gayhoopla_experience_featuring_canelo_ment_and_andre_willis._no_sex_in_this_video_even_though_there_was_penetration..._you%27ll_find_out._cumshots_included..htm
- (Gay Hoopla) - Martavis Ray Under Fire from Jeremy 'The All Hole Slayer' Barker. Martavis's Ass Is Gonna Be Sore Tomorrow (2021).mp4
https://www.iafd.com/title.rme/title=martavis+ray+under+fire+from+jeremy+%22the+all+hole+slayer%22+barker.+martavis%27s+ass+is+gonna+be+sore+tomorrow/year=2021/martavis_ray_under_fire_from_jeremy_%22the_all_hole_slayer%22_barker._martavis%27s_ass_is_gonna_be_sore_tomorrow.htm
- (Gay Hoopla) - New Face Fucks! His 1st Gay Experience Ever! Did Exceptional! (2019).mp4
https://www.iafd.com/title.rme/title=new+face+fucks%21+his+1st+gay+experience+ever%21+did+exceptional%21/year=2019/new_face_fucks%21_his_1st_gay_experience_ever%21_did_exceptional%21.htm
- (Gay Hoopla) - Off Camera Kiss Leads To Two Of Our Newest Stars Flip Fucking (2019).mp4
https://www.iafd.com/title.rme/title=off+camera+kiss+leads+to+two+of+our+newest+stars+flip+fucking/year=2019/off_camera_kiss_leads_to_two_of_our_newest_stars_flip_fucking.htm
- (Gay Hoopla) - Str8 for Pay Gay Model Tries to Jerk to Str8 Porn. One of the Most Requested Scenes... Don't Ask Us Why. (2020).mp4
https://www.iafd.com/title.rme/title=str8+for+pay+gay+model+tries+to+jerk+to+str8+porn.+one+of+the+most+requested+scenes...+don%27t+ask+us+why./year=2020/str8_for_pay_gay_model_tries_to_jerk_to_str8_porn._one_of_the_most_requested_scenes..._don%27t_ask_us_why..htm
- (Gay Hoopla) - We Wish These 2 Muscle Daddies the Best. Hot Sex! Naughty Men (2019).mp4
https://www.iafd.com/title.rme/title=we+wish+these+2+muscle+daddies+the+best.+hot+sex%21+naughty+men/year=2019/we_wish_these_2_muscle_daddies_the_best._hot_sex%21_naughty_men.htm

AS ALWAYS THANK YOU FOR A GREAT TOOL! So many successful matches that are helping clean up and organize my media.

**Comment by JPH71** [comment]
Waybig - Matches:
(Gay Hoopla) - Matt Mason A.K.A. CreamyGorilla [Mystery Model #70] (2020)
(Gay Hoopla) - Identical Twins Dee King & Jay King Cum Simultaneously (2021)
(Gay Hoopla) - Brock Perry [A.K.A. Mystery Model #68] (Young Body Builder
Jerks Off) (2020)
(GayHoopla) -  Roman Austin Strokes His Soul Out! [The Most Intense Cumshot
Ever!] (2021)
