### ISSUE TITLE
Plex Image Cropper URL not working

### ISSUE THREAD

**Issue by j-ktz** [CodyBerenson/PGMA-Modernized#109]
Hey @CodyBerenson, not sure if it's just me but the URL to crop images doesn't seem to be working anymore. Can you check?

**Comment by CodyBerenson** [comment]
@j-ktz will do.  Google cloud stopped giving year free hosting and lowered it to 90 days.  It could be that the 90 days has expired and I need to set up another Thumbr instance.  I'll check and let you know.

**Comment by CodyBerenson** [comment]
@j-ktz 
hello again, bad boy.  The 90 day free clock had expired.  new account, new thumbor instance, new 90 days.  please update your registry expression's thumbor web address and kill and restart your PMS:  

http://34.86.184.21:8888

![image](https://user-images.githubusercontent.com/40373801/127325784-98abc3a1-85cd-40dd-9bd2-fafde6e609a8.png)

Thanks for calling attention to this.  

p.s. for anyone who is Docker savy, you can set up thumbor yourself and not have to rely on ours.  Here's the how-to:  https://thumbor.readthedocs.io/en/latest/getting_started.html#problems-installing-thumbor-locally

@jph71 please update your versions of the source code preferences for each scene agent to the above address.  I'll update the current code and release them to the master repository momentarily

**Comment by CodyBerenson** [comment]
Master repository updated.  We'll leave this bug open for a few days for folks' awareness.

**Comment by j-ktz** [comment]
Thanks for the quick fix, @CodyBerenson!

**Comment by JPH71** [comment]
Cheers Cody!

**Comment by vampirelayer** [comment]
This has started to work. Thanks y'all!
