### ISSUE TITLE
Poster URL broken?

### ISSUE THREAD

**Issue by j-ktz** [CodyBerenson/PGMA-Modernized#113]
Hey Boys,

Scrapers pulling in data but not posters today. When I try to access the URL, it doesn't load. Is it down?

**Comment by j-ktz** [comment]
Thanks Cody!

**Comment by j-ktz** [comment]
LOL.. See you in the next 90 days. I'm around!!! Anything I can help with? :)

**Comment by CodyBerenson** [comment]
Careful…thats a wide open offer…

**Comment by j-ktz** [comment]
I mean it! Always here to help test or whatever. Just ping me. 

On October 31, 2021, GitHub ***@***.***> wrote:
> Careful…thats a wide open offer…
>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/CodyBerenson/PGMA-
Modernized/issues/113#issuecomment-955757606>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AOEY5RHVPS5WBFA5T7EKC3LUJV3APANCNFSM5G3E2G2Q>.
Triage notifications on the go with GitHub Mobile for iOS
<https://apps.apple.com/app/apple-store/id1477376905?ct=notification-
email&mt=8&pt=524675> or Android
<https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-
email%26utm_medium%3Demail%26utm_source%3Dgithub>.
