### ISSUE TITLE
GEVI not matching after last update

### ISSUE THREAD

**Issue by ScoBoXxX** [CodyBerenson/PGMA-Modernized#114]
I'm having trouble with GEVI matching full films.  Scene agents are matching fine, just GEVI it seems.  I have three titles below that are not matching.  I was able to match Uncle Bobby fine on another PMS server.  Link to GEVI agent log attached.  It looks like it is finding the title but the entry in Plex is not updating at all.  No info, summary, poster, nada.  I removed all the plugins and reinstalled them yesterday to no avail.  Not sure what I am doing wrong...they're all indeed listed in GEVI site.

(BelAmi) - All Sex Party (2020)
(Icon Male) - Uncle Bobby (2019)
(Guys In Sweatpants) - Austin Wilde's Favorite Holes (2019)

GEVI log:  https://1drv.ms/u/s!Akzf-su3mpHu7W1SVK8dfg8dB88g?e=90o5yu
PMS log:  https://1drv.ms/u/s!Akzf-su3mpHu7Cq6C34kkT_dyeHC?e=uUfvp8

**Comment by CodyBerenson** [comment]
Hi @ScoBoXxX 

Hope this finds you well.  Thanks for calling this to our attention.  Jason coded a Fix that I tested with about two dozen titles.  Should be good to go with fix that was just pushed to the master repository.  

I'll leave this bug open for a couple of days for folks' awareness.  

Cheers!

**Comment by CodyBerenson** [comment]
@ScoBoXxX 

p.s. The three files you cite above match fine with this update:

![image](https://user-images.githubusercontent.com/40373801/139618866-37b03967-d30c-45b6-bb10-3a7a2ed5460a.png)

**Comment by ScoBoXxX** [comment]
Confirmed - thanks guys!  Always amazing :)
