### ISSUE TITLE
IAFD Struggling to Match

### ISSUE THREAD

**Issue by j-ktz** [CodyBerenson/PGMA-Modernized#115]
The last six scenes haven't matched. Getting this error:
`IAFD - UTILS :: FFProbe Error: Duration Matching will be skipped: [Errno 2] No such file or directory`

Log attached
[com.plexapp.agents.IAFD.log](https://github.com/CodyBerenson/PGMA-Modernized/files/7567156/com.plexapp.agents.IAFD.log)
.

**Comment by joca879** [comment]
Hi @j-ktz 
Hope you're well!
I've sent you an email. Give it a look when possible.
Thanks

**Comment by j-ktz** [comment]
@joca879 Will do! 

Any update on this boys? Let me know if  I can help in any way!

**Comment by CodyBerenson** [comment]
hiya @j-ktz  hope you are well.

I'll defer to @JPH71 on the timing for the fix to this plus a similiar fix needed to AEBN.  Until then (if you haven't already), I suggest you pull the IAFD version before the last release that introduced the issue...I tried it, and its working fine.  The AEBN workaround (turn off timing checking in the RegEx) doesn't work for IAFD, so you actually need to delete the broken agent and reapply the previous agent.  If @JPH71's timeline seems to be a long one, I may just revert AEBN and IAFD to their previous versions.

**Comment by j-ktz** [comment]
@CodyBerenson Hanging in there. Happy Holigays! I'd be happy to revert to the old IAFD and AEBN agents in  the meantime. Do you know how I download old versions? Sorry, Githhub newbie. I only see the current agents in the master zip.

**Comment by CodyBerenson** [comment]
@j-ktz
The current AEBN works, but only if you uncheck the timing option in the RegEx (Match against Site's recorded film/scene length, Note: IAFDs entry is always matched)

Here are the instructions to get to older IAFD or IAFD and AEBN code:

1. From the code tab, click on the IAFD.bundle. 
2. Click on the History button in the upper right hand corner
3. The October 19, 2021 release is what is broken, so click on the <> button for the August 1, 2021 release.  This will show you what the repository looked like at that time.
4. Get the code just like you always would.  Wipe out, copy, restart PMS just like you always would (just for the IAFD or IAFD and AEBN bundles).

Cheers

**Comment by j-ktz** [comment]
@CodyBerenson Thank you sir! Worked perfect.

**Comment by JPH71** [comment]
@j-ktz <https://github.com/j-ktz>

Could you send me the download link of any of the movies that failed with
the current AEBN iii version.
Each movie extension type stores its length differently and this sometimes
seems to change depending on when the movie was encoded.
I can then sort this out and make sure that it is not common to all
scrapers, as the code determining the length of videos is in the utilities
section.

In the meantime I will look through AEBN iii's code and see if it is
there.... it should be a one-liner....

**Comment by j-ktz** [comment]
@JPH71 I can! How should I send you links? Email?

**Comment by JPH71** [comment]
yes email ... ***@***.***

**Comment by JPH71** [comment]
Hi @j-ktz <https://github.com/j-ktz>

Checked the issue - the reason you are getting this error is because you
have not installed FFMPEG, this has to be done and the executable FFProbe
has to be in the path variables.
You will have to do this in your linux system or edit line 112 of the
utils.py program and put the full path to ffrrobe.....

Luckily you spotted this error as I found an error further down... that
would have still stopped the IAFD scrapper....

I tested it with
(CutlersDen) - Cutler X and Isaac X (2021).mp4

This same video is on BestExclusivePorn - name it (Cutler's Den) - black
cat- Cutler X fucks Isaac X bareback (2021) and you will get the artwork
that goes with it!

Mingi (much in Swahili) Love and a happy new year!

Jason xxx

**Comment by JPH71** [comment]
Hi @j-ktz <https://github.com/j-ktz>

Latest bundle is with Cody!

**Comment by j-ktz** [comment]
Thanks sir!

**Comment by CodyBerenson** [comment]
@j-ktz the fix to IAFD and AEBN have been pushed to the master repository
