### ISSUE TITLE
Looks like GEVI is not matching again

### ISSUE THREAD

**Issue by ScoBoXxX** [CodyBerenson/PGMA-Modernized#118]
Seems like I complain a lot about GEVI :(  But it appears to have stopped matching again.  I believe it worked yesterday but this morning I cannot match any full films.  I pretty much only match from GEVI for full films.  I have verified the file names and all that.  The logs indicate errors in matching the file names and ultimately resulted in no match.  I can provide those if necessary but thought maybe you'd be able to see an issue initially without them.  No match on filename, thus no meta data and no poster.

Note: scenes are matching fine, just not full films using GEVI.

example filenames:
(MEN.com) - Men Bang! (2019).mp4
(BelAmi) - Body Perfect (2014).mp4
(Staxus) - Bareback Xmas Cum Blizzard 1 (2020).mkv (this one has no release date in GEVI)
(Junior Studio) - The American Way 1 (1999).mkv (also tried with RAD Video as the studio)

Thanks for ALL you do!
sb

**Comment by CodyBerenson** [comment]
@ScoBoXxX Thanks for letting us know. 

@JPH71 Looks like GEVI has made some change to their site. Here’s a log for a test file. 

[com.plexapp.agents.GEVI.log](https://github.com/CodyBerenson/PGMA-Modernized/files/7875476/com.plexapp.agents.GEVI.log)

**Comment by JPH71** [comment]
@ScoBoXxX <https://github.com/ScoBoXxX> - thanks for letting us know - if
no one complains we would have missed it....
The updated contents are with Cody for final testing and upload into the
repository

Jason

**Comment by CodyBerenson** [comment]
Since I'm still on holiday in Spain, I performed only limited testing. The master repository has been updated. Cheers!
