### ISSUE TITLE
Thumbor broken

### ISSUE THREAD

**Issue by j-ktz** [CodyBerenson/PGMA-Modernized#120]
Does not seem to be working for me. Is there a new address?

**Comment by CodyBerenson** [comment]
@j-ktz Thanks for the head's up.  Here's the new address, update in the Scene Agents RegEdit, restart PMS, and see you in 90 days.  ;)

http://34.86.202.9:8888/unsafe

@jph71 Will you update the Scene agents?  Thanks!

**Comment by JPH71** [comment]
@cody will do...
I have made changes to utils.py which @cideAnator suggested, so loads will
come your way xxxx
