### ISSUE TITLE
IAFD Matching

### ISSUE THREAD

**Issue by jocklover** [CodyBerenson/PGMA-Modernized#122]
Hello Again!
Thank you all for the great work on this agent, always impressed with its functionality and the work you put into it. Also, thank you for previous troubleshooting support.

I was away from matching my library for a bit but am back at it again. Found many of my questions/issues either in the Usage Guide or in Issues - so thank you!

However, I am seeing an issue matching IAFD scenes. I think I have verified every aspect of the naming convention and setup, and the Logs even _seem_ to be indicating a successful match, however I am not getting the scene info to load in. (Note: WayBig & QueerClick are working correctly.)

**New Attempts at matching**
(TransSensual) - Blondes Have More Fun Scene 2 (2016)
https://www.iafd.com/title.rme/title=blondes+have+more+fun+scene+2/year=2016/blondes-have-more-fun-scene-2.htm
(TransSensual) - Can't leave this TS Latina Scene 3 (2016)
https://www.iafd.com/title.rme/title=can%27t+leave+this+ts+latina+scene+3/year=2016/can&apos;t-leave-this-ts-latina-scene-3.htm
(TransSensual) - TS Babysitters Scene 4 (2016)
https://www.iafd.com/title.rme/title=ts+babysitters+scene+4/year=2016/ts-babysitters-scene-4.htm
(TransSensual) - TS Stepmother Scene 4 (2016)
https://www.iafd.com/title.rme/title=ts+stepmother+scene+4/year=2016/ts-stepmother-scene-4.htm
(BaitBus) - Fake Cash Buys Real Ass Fucking (2019)
https://www.iafd.com/title.rme/title=fake+cash+buys+real+ass+fucking/year=2019/fake-cash-buys-real-ass-fucking.htm

**Sample of Previous Matches, now failing**
(Active Duty) - Active Duty Favorites - Best Of Quentin Gainz (2021)
https://www.iafd.com/title.rme/title=active+duty+favorites%3a+best+of+quentin+gainz/year=2020/active_duty_favorites%3a_best_of_quentin_gainz.htm
(Active Duty) - Active Duty Favorites - Cum On My Face (2021)
https://www.iafd.com/title.rme/title=active+duty+favorites%3a+cum+on+my+face/year=2021/active_duty_favorites%3a_cum_on_my_face.htm
(Active Duty) - Late Recruit (2021)
https://www.iafd.com/title.rme/title=late+recruit/year=2021/late_recruit.htm

Here is a log from the IAFD agent that should be providing the match, it is only a sample of two titles from the new section above:
[IAFD log for TS Scenes.txt](https://github.com/CodyBerenson/PGMA-Modernized/files/8121477/IAFD.log.for.TS.Scenes.txt)

I should be on the 6da4f67 version. I have disabled/enabled Plex & restarted NAS. The log is from "Refresh Metadata", I have also tried "Fix Match".

Thank you for your consideration and let me know if there is any additional info that I can provide.

**Comment by JPH71** [comment]
I will look into this, this evening xxx

**Comment by CodyBerenson** [comment]
@jocklover 

The current IAFD agent does not work.  Please see the work around in issue #115.

**Comment by jocklover** [comment]
[f8d8771](https://github.com/CodyBerenson/PGMA-Modernized/commit/f8d8771809d6b619f9e356e55bfcbfa7368c4abd) fixed the issue, thanks. I'll keep an eye out for a future update.

**Comment by CodyBerenson** [comment]
@jocklover the fix to IAFD has been pushed to the master repository
