### ISSUE TITLE
Waybig Matching Issue - Title contains "At Studio" at the end AND a colon and won't match

### ISSUE THREAD

**Issue by jocklover** [CodyBerenson/PGMA-Modernized#123]
I believe I have followed the Usage Guide to name scenes where WayBig listed the studio last, however I am not seeing successful matches. I am guessing I am doing something wrong, but not sure on the error of my ways.

(Bromo) - Vadim Black Bottoms For Brad Banks In 'Cream For Me A Gay XXX Parody' Part 3 (2016)
https://www.waybig.com/blog/2016/10/23/vadim-black-bottoms-for-brad-banks-in-cream-for-me-a-gay-xxx-parody-part-3-at-bromo/
(Bromo) - Vadim Black, Tom Faulk & Tobias Tag-Team James Edwards In 'Cream For Me A Gay XXX Parody' Part 4 (2016)
https://www.waybig.com/blog/2016/10/27/vadim-black-tom-faulk-tobias-tag-team-james-edwards-in-cream-for-me-a-gay-xxx-parody-part-4-at-bromo/
(MEN) - Vadim Black Fucks Allen King In 'Son Swap European Vacation' Part 7 (2016)
https://www.waybig.com/blog/2016/05/08/vadim-black-fucks-allen-king-in-son-swap-european-vacation-part-7-at-men-com/
(MEN) - Vadim Black Fucks Zach Taylor In 'Group Home' Part 2 (2016)
https://www.waybig.com/blog/2016/11/17/jack-hunter-noah-jones-vadim-black-will-braun-and-zach-taylor-in-group-home-orgy-part-3-at-men-com/

_These have other issues from the site title as well:_
(MEN) - Men At Sea Part 7 (Alex Mecum, Brenner Bolton, Landon Mycles And Vadim Black) (2015)
https://www.waybig.com/blog/2015/12/27/men-at-sea-part-7-alex-mecum-brenner-bolton-landon-mycles-and-vadim-black-at-men-com/
(MEN) - Str8-To-Gay My Best Friend’s Husband (Jimmy Fanz & Vadim Black) (Part 4) (2015)
https://www.waybig.com/blog/2015/06/02/str8-to-gay-my-best-friends-husband-jimmy-fanz-vadim-black-part-4/

Please let me know if you need any additional information. THANK YOU!

_Note: Opening this as a separate issue as I do not think it is related to the (IAFD matching issues) I just opened._

**Comment by JPH71** [comment]
I will get back to you this evening... in the meantime try dropping the
word PART

Jason xx

**Comment by CodyBerenson** [comment]
@jocklover 

I don't believe the Waybig agent handles the combined scenarios of 1) "at Studio" at the end of the title, and 2) a colon embedded as part of the title.  This is the scenario in each of these titles.  Out of the six titles you provided, I was able to get two to match...:

(Str8-To-Gay) - My Best Friend’s Husband (Jimmy Fanz & Vadim Black) (Part 4) (2015).mp4

(Vadim Black Fucks Allen King in ‘Son Swap) - European Vacation’ Part 7 at Men.com (2016)

I'm unfamiliar with the thought behind dropping the word "Part" so I'll defer to Jason to provide further guidance on how to deal with both an "at Studio" at the end of the title and a colon embedded as part of the title.

**Comment by jocklover** [comment]
Definitely appears to be the issues, I have run into a hole nother list of identical issues - has a colon and ends with at Studio. 
I have switched most of these over to QueerClick matches to get the metadata. (Just don't love they don't include scene titles.) The only outstanding title is "(Bromo) - Vadim Black, Tom Faulk & Tobias Tag-Team James Edwards In 'Cream For Me A Gay XXX Parody' Part 4 (2016)" isn't anywhere else (except IAFD) so I will just keep that on the side for now.
Thanks again for your help.

**Comment by JPH71** [comment]
I will sort out this conumdrum...

**Comment by CodyBerenson** [comment]
@JPH71 Terrific.  I'll leave this issue open for future resolution.

@jocklover   I'm probably not suggesting anything you don't already know...When I can't get the match that I'm looking for from a given site (e.g., WayBig), I will go ahead with my Plan B or Plan C (e.g., Fagalicious, or IAFD) and then manually update the Title and/or Summary using Plex's built in functionality, and use Thumbor to obtain the Posterart (I mostly prefer WayBig over the other indexes)...specifically in this case:

http://34.86.202.9:8888/unsafe/0x0:800x1200/https://zing.waybig.com/reviews/Bromo/10-27-16/cream-for-me-pt4-bromo-01.jpg

Cheers!

**Comment by JPH71** [comment]
I prefer watbig too... I will look into it and resolve the issue

**Comment by JPH71** [comment]
Issue solved - Cody will have the updated agent in a couple of minutes or so...
Thank you for this as I found 2 errors resulting from this - matching on studio and on title. because of the : and at in the title..
Also sorted out an issue with tags.... tags which have colons in them are disregarded as they could not be an actors name...

**Comment by jocklover** [comment]
Thanks for the work on this and the updates!
Unfortunately, it seems there may be an unintended side effect with this title:

(MEN Series) - Johnny Rapid, Luke Adams & Vadim Black In 'Men At Sea, Part 3' (2015)
https://www.waybig.com/blog/2015/12/13/men-johnny-rapid-luke-adams-vadim-black-men-at-sea/

Log seems to indicate that the Site Studio is "sea, part 3" (log file below)

[WayBig Log.log](https://github.com/CodyBerenson/PGMA-Modernized/files/8194458/WayBig.Log.log)

**Comment by JPH71** [comment]
Did it match?
This was a quick fix... and the logging will also need to be tweaked...

**Comment by jocklover** [comment]
The target titles from the beginning of this thread match correctly.
However I am seeing a new failure resulting from this update.

**Comment by jocklover** [comment]
See above, titles that include "at" in the name are being split off as the
studio incorrectly.

**Comment by CodyBerenson** [comment]
@jocklover , @JPH71 

Hi, Jason suggested that I revert to the previous version of WayBig and he will look for alternative means to fix this bug.  So, I've reopened the bug, and will revert the WayBig code momentarily.  

Cheers!

**Comment by CodyBerenson** [comment]
@jocklover @JPH71 

Good morning.  Jason has coded a fix for "At Studio" at the end of a title without breaking "at" anywhere in the title.  I have uploaded it into the "Beta" Branch.  From the Code tab, switch the Branch from "master" to "Beta" to try it out.  

In a few days, I'll merge Beta into master.  

Cheers.

**Comment by jocklover** [comment]
All test titles are matching, both with "at Studio" and "at _not Studio_" in their title.
Thanks for the work on this obnoxious naming issue. :)

**Comment by JPH71** [comment]
Thanks for spotting it!
