### ISSUE TITLE
Suggestions to Prevent Title Loss?

### ISSUE THREAD

**Issue by jocklover** [CodyBerenson/PGMA-Modernized#131]
Working with CockSureMen scenes from IAFD. They titles are only "_Actor on Actor_" and not an actual title (and no AKA title listed either). I don't want to loose the titles. Are there suggestions on file naming or other solutions to accomplish this?

I have tried _**(Studio) IAFD Title (year) Actual Title**_ and _**(Studio) IAFD Title Actual Title (year)**_, both to no avail.

Here are a couple sample titles if it helps to test:
(CockSureMen) - _Andrew Crime Barebacks Alex Vichner_ **When Im Next To You** (2016)
https://www.iafd.com/title.rme/title=andrew+crime+barebacks+alex+vichner/year=2016/andrew_crime_barebacks_alex_vichner.htm

(CockSureMen) - _Andrew Lewix Barebacks Ryan Volta_ (2017) **Claiming You**
https://www.iafd.com/title.rme/title=andrew+lewix+barebacks+ryan+volta/year=2017/andrew_lewix_barebacks_ryan_volta.htm

**Comment by JPH71** [comment]
Try this:  (CockSureMen) -  *When I'm Next To You* - *Andrew Crime
Barebacks Alex Vichner* (2016)

ensure that you enable collections from filenames snd you have a
space-dash-space after the *embolden* text

Jason xx

**Comment by jocklover** [comment]
With your suggestion and a little fiddling, I found the solution is:
(Studio) _Actual Title_ - **IAFD Title** (year)
_(This is one time that you **do** want "space dash space")_

So the sample titles above become:
(CockSureMen) - Claiming You - Andrew Lewix Barebacks Ryan Volta (2017)
(CockSureMen) - When Im Next To You - Andrew Crime Barebacks Alex Vichner (2016)

The PLEX title presents as _Studio Title_: **IAFD Title** which is fine, and contains the metadata. And the _Studio Title_ does appear as a collection item.
THANK YOU

**Comment by JPH71** [comment]
Perfect x
