### ISSUE TITLE
IAFD Match Failures

### ISSUE THREAD

**Issue by jocklover** [CodyBerenson/PGMA-Modernized#132]
Getting a few issues matching titles in IAFD. Any thoughts?

No title from SayUncle's MilitaryDick are matching (8 scenes tried). No issues w/ any other SayUncle studio.
Here are a two samples:
(MilitaryDick) - A Naughty Cadet (2021)
https://www.iafd.com/title.rme/title=naughty+cadet/year=2021/naughty_cadet.htm
(MilitaryDick) - Heavy Load (2022)
https://www.iafd.com/title.rme/title=heavy+load/year=2022/heavy_load.htm
_**Note: I have these titles in individual folders to keep accompanying photos organized, however the folder name exactly matches the scene title and this has not been an issue anywhere else I have done it._

**One off issues matching titles:**
(SayUncleLabs) - Concept- Twink Trap- Andrew x Jax (2021)
https://www.iafd.com/title.rme/title=concept%3a+twink+trap+-+andrew+x+jax/year=2021/concept%3a_twink_trap_-_andrew_x_jax.htm

(MissionaryBoys) - Bless Me, Father (2020)
https://www.iafd.com/title.rme/title=bless+me%2c+father/year=2020/bless_me%2c_father.htm

(MissionaryBoys) - Elder Awbride- The Calling (2019)
https://www.iafd.com/title.rme/title=elder+awbride%3a+the+calling/year=2019/elder_awbride%3a_the_calling.htm

Let me know if you need logs from match attempts on any of these. **THANK YOU**

**Comment by JPH71** [comment]
I will look into this!

**Comment by jocklover** [comment]
Feel like I should give up after this one!
While looking at #135 I rechecked these to see if there was a correlation.... and all of these match just fine now. No change to file name, just dropped back into to library or refreshed metadata. No clue, but will close this one out. Thanks again.
