### ISSUE TITLE
IAFD Matching Issue w/ "1" in Title

### ISSUE THREAD

**Issue by jocklover** [CodyBerenson/PGMA-Modernized#135]
There appears to be an issue w/ IAFD matching when there are is the number "1" in the title.

Reviewing the log, I see the search URL for titles w/ "1" drop the "1" from the search URL, however it is retained for 2+.
Title: (BoyForSale) - Boy River 1- The Merchandise (2019)
IAFD page: https://www.iafd.com/title.rme/title=boy+river+1%3a+the+merchandise/year=2019/boy-river-1-the-merchandise.htm
Log Search URL: https://www.iafd.com/results.asp?searchtype=comprehensive&searchstring=Boy+River+%3A+The+Merchandise
URL needed: https://www.iafd.com/results.asp?searchtype=comprehensive&searchstring=Boy+River+1%3A+The+Merchandise

Additional title examples:
(BoyForSale) - Boy Jay 1- The Merchandise (2019)
https://www.iafd.com/title.rme/title=boy+jay+1%3a+the+merchandise/year=2019/boy_jay_1%3a_the_merchandise.htm
(BoyForSale) - BOY DANNY 1- The Grooming (2020)
https://www.iafd.com/title.rme/title=boy+danny+1%3a+the+grooming/year=2020/boy_danny_1%3a_the_grooming.htm
(FunSizeBoys) - Eli 1- Dr. Wolf's Office (2021)
https://www.iafd.com/title.rme/title=eli+1%3a+dr.+wolf%27s+office/year=2021/eli_1%3a_dr._wolf%27s_office.htm
(FunSizeBoys) - Austin and Cole 1- Boys Big and Small (2019)
https://www.iafd.com/title.rme/title=austin+14%3a+boys+big+and+small/year=2019/austin_14%3a_boys_big_and_small.htm

**Comment by JPH71** [comment]
That is correct..
This is catered for in the comparison too of the title...

**Comment by jocklover** [comment]
If I understand correctly, you are referring to comparing returned results to file name.
The issue I am seeing is that _no results_ are being returned to be compared to when the "1" is missing from the search URL.

Here is a sample log result:
[IAFD No Results - 1 in Title.txt](https://github.com/CodyBerenson/PGMA-Modernized/files/8195858/IAFD.No.Results.-.1.in.Title.txt)

**Comment by JPH71** [comment]
I will check this out and get back to you...

**Comment by jocklover** [comment]
Appears the fix for this issue was included in one of the recent updates.
THANK YOU
