### ISSUE TITLE
Dual Studio Not Working

### ISSUE THREAD

**Issue by jocklover** [CodyBerenson/PGMA-Modernized#137]
In the course of trying to get a WayBig & IAFD dual match, I tried using the dual studio functionality listed on p16-17 of the Usage Guide: (**Studio**;_IAFD Studio_) Based on the logs, it appears that the WayBig & IAFD agents are both using the first studio for matching.
I may be missing something, but I think I am reading the logs correctly. The logs are here:
[Dual Studio Logging - WayBig.txt](https://github.com/CodyBerenson/PGMA-Modernized/files/8228491/Dual.Studio.Logging.-.WayBig.txt)
[Dual Studio Logging - IAFD.txt](https://github.com/CodyBerenson/PGMA-Modernized/files/8228493/Dual.Studio.Logging.-.IAFD.txt)

**Comment by CodyBerenson** [comment]
@jocklover Thanks for bringing this to our attention.  This issue isn't relating to "dual studio".  The issue just seems to be that the IAFD calls, as part of dual studio or not, are not currently working, period.

@JPH71 Can you look into IAFD?  I just tested two titles specifically for the IAFD agent and they don't match.  Same results as in his WayBig.txt log above.  I think you'll see the problem right away when you look in the log.  Thanks!

[com.plexapp.agents.IAFD.log](https://github.com/CodyBerenson/PGMA-Modernized/files/8233386/com.plexapp.agents.IAFD.log)

**Comment by jocklover** [comment]
I see how that is a problem that was occurring in the logs where the Site Title URL is bad.

However, I still think the wrong Studio is being used for the IAFD matching when 2 Studios are listed. From the IAFD log above, the Film Dictionary Variables are:
FileName: (NextDoorBuddies;Next Door) - Best Buds (2021)
CompareIAFDStudio: nextdoorbuddies
CompareStudio: nextdoorbuddies
Studio: NextDoorBuddies

If I am reading these variables correctly, the CompareIAFDStudio should be "NextDoor" / "Next Door" _not_ NextDoorBuddies based on the Usage Guide.

(I do understand that "Next Door" should be sufficient and Buddies (etc.) is optional, but this appears to be a bug regardless.)

**Comment by JPH71** [comment]
Yes, I will sort this out... together with a title matching error I
introduced in the last update...

Hopefully this will be sorted out this weekend.

Thanks for highlighting this
Xxx

**Comment by CodyBerenson** [comment]
@jocklover I think you'e slightly misunderstanding the functionality described on pages 16-17 of the guide, using the (Studio;IAFDStudio) portion of the file naming convention.  This is used to pull IAFD metadata into the data (i.e. role (top/bottom) )into the metadata scraped from the target matching site *_when IAFD lists a different studio than the target matching site for the same title_*.  If you look at the target matching site's log (e.g. Waybig), you'll see whether the IAFD match was successfull.  

*Therefore*, you do not even have to have IAFD checked as a matching agent, for this functionality to work, and looking at the IAFD log will not help.  The answers for the functionality described on page 16-17 is in the WayBig log.   

Just wanted to point this out, as @JPH71 trouble shoots why this title didn't return the roles for the actors.

@JPH71 Can you take a look?  This is a clear cut test case.  Title matching on IAFD and returning actor's roles doesn't seem to be working:

https://www.waybig.com/blog/2022/02/18/nextdoorbuddies-david-skylar-fucks-conner-blakely-conners-first-time/

[com.plexapp.agents.WayBig.log](https://github.com/CodyBerenson/PGMA-Modernized/files/8237765/com.plexapp.agents.WayBig.log)

**Comment by jocklover** [comment]
Here is a test case I ran w/ the IAFD Studio listed as "Unused_Studio" to make it easier to trace vs above.
_File name: (Next Door Buddies;Unused_Studio) - Best Buds (2021)_
WayBig successfully matched, then called IAFD to get the additional metadata scrape.
In both logs there is no utilization of "Unused_Studio" as the IAFD Studio, and instead  entries in both logs indicating the IAFD Studio is "Next Door Buddies".

[Dual Studio - WayBig.txt](https://github.com/CodyBerenson/PGMA-Modernized/files/8238308/Dual.Studio.-.WayBig.txt)
[Dual Studio - IAFD.txt](https://github.com/CodyBerenson/PGMA-Modernized/files/8238309/Dual.Studio.-.IAFD.txt)

**Comment by CodyBerenson** [comment]
@jocklover Good morning, @JPH71 Created fixes to this issue.  If you'd like to, we encourage you to test the fixes.  You can find the fixes in a separate branch of code for this repository called ReleaseTesting.  From the Code tab, change the branch from Master to ReleaseTesting, download and install the agents and restart PMS just like you would for any release.  At any time, you can switch the drop down back, reselect Master, download and install.  

![image](https://user-images.githubusercontent.com/40373801/168625758-27b55b19-8d64-4ded-8b40-45c4de3ae0ab.png)

**Comment by jocklover** [comment]
It appears that this is working correctly. Logs are accurately reporting Studio & IAFDStudio.

I can move this to a different issue thread, but the issue I am seeing is that titles are not matching to WayBig if only the scene title is used and not the WayBig blog article title. I only get the IAFD match. I thought this was working previously but not sure where it might have changed (or what the intended behavior is).
An example is: (MEN Series) - Captain Rapid, Part 3 (2019) _(tried w/ & w/out "Series" & ",")_
https://www.waybig.com/blog/2019/12/04/men-xavier-cox-kyle-connors-johnny-rapid-captain-rapid/

(I have verified WayBig is first in my Agent prefs.)
**THANK YOU**

**Comment by JPH71** [comment]
The agent always matches the waybig blog title... This has always been the
case.

If you look through the issues and the read me notes that Cody has you will
see that time and time again he has mentioned that you copy the waybig
blog title and rename the file exactly by replacing the colon with a space
dash space, and brackets around the studio and use the year of the date of
the blog article...

so
MEN Series: Xavier Cox & Kyle Connors With Johnny Rapid In ‘Captain Rapid,
Part 3’

becomes

(MEN Series) - Xavier Cox & Kyle Connors With Johnny Rapid In ‘Captain
Rapid, Part 3’ (2019)

OR

(MEN) - Xavier Cox & Kyle Connors With Johnny Rapid In ‘Captain Rapid, Part
3’ (2019)

What you are suggesting can be done...

by matching in IAFD, then picking the actors and then searching through the
blogs.... and that has given me an idea... but there will higher incidents
of non-exact matches.... but I will look into this soon...

Jason
