### ISSUE TITLE
Feature + blog site requests

### ISSUE THREAD

**Issue by ghost** [CodyBerenson/PGMA-Modernized#14]
First off, 
Amazing work done by y'all. I would have never thought to use blog sites for agent scraping. I am working on refactoring all these wonderful agents into a system that runs on Node.JS that has a single web interface page to visually / easily debug any scraping issues, auto updating agents from a master repo, and only one plugin that attaches to Plex, so no more restarting Plex every single change (from a dev. perspective this is huge, for me at least.) I would be interested if any of you guys know Node or have any suggestions on how this should be packaged.

**Comment by JPH71** [comment]
@nyethi, I have never used node, but that sounds exciting.
By the way I sent you the PLEX api documentation in case you had lost your copy.
I really need your help to tackle GayVODClub and AdultDVDMarketPlace with getting past the enetr button on the first one and searching on the gay section of the second one... also controlled by a damn button....

Cheers

Jason

**Comment by nyethi** [comment]
could you resend that pdf to "contact@vigue.me" please, i DID in fact lose my copy :)

**Comment by CodyBerenson** [comment]
@nyethi 

Hi A.  Hope you're well.  Looking forward to testing your work.  Take care.

Cody

**Comment by JPH71** [comment]
@Nyethi

Have you found out how - to get past this enter site buttons?? 
Do let me know either way....
AdultDVDTalk also has the bloody thing on it - and thus i can't get to the search results as i have to click enter.....

**Comment by acvigue** [comment]
I have been pretty swamped these past couple of days working on a personal project (on my github profile if you're interested) But, I have the Node agent working. I do not know how to do the site enter buttons in Python. I tried but it always made you click the button

**Comment by CodyBerenson** [comment]
@acvigue 
hi A, 

@JPH71 and I are excited to give your Agent a whirl.  :) 

Looking forward to it.  Hope you're well and safe.

**Comment by acvigue** [comment]
About to open it up, need to make a few performance improvements then it will be ready.
