### ISSUE TITLE
Director ".fusion-body..." for sites without Director Data

### ISSUE THREAD

**Issue by CodyBerenson** [CodyBerenson/PGMA-Modernized#141]
### Discussed in https://github.com/CodyBerenson/PGMA-Modernized/discussions/138

<div type='discussions-op-text'>

<sup>Originally posted by **jfreiman** March 11, 2022</sup>
I have an annoying issue that some videos which get matched (multiple sites) do not contain a Director and instead of leaving the Director Tab blank, it leaves a long string of code beginning with, ".fusion-body..." and continues for several lines.

below are screen captures of what I'm referring to

[https://1drv.ms/u/s!AqXiusoHW-XfxMBk3YvhylCymQ4mjw?e=9dG5AR](url)
[https://1drv.ms/u/s!AqXiusoHW-XfxMBk3YvhylCymQ4mjw?e=4jLoUX](url)

I'm hoping there is a simple solution that doesn't require me to manually delete the Plex Director tab manually.
Thank you in advance,
John</div>

**Comment by JPH71** [comment]
The gayworld.org site has been taken down.
so no need to fix this agent.
Fix has been applied to GayMovie.Org

**Comment by jfreiman** [comment]
Here is another Director issue -- after using today's build.
**Pulse Distribution) - Top To Bottom 4 (2018).mp4**

`https://www.iafd.com/title.rme/title=top+to+bottom+4/year=2018/top-to-bottom-4.htm`

`.fusion-body .fusion-builder-nested-column-2{width100% !important;margin-top 0px;margin-bottom 20px;}.fusion-builder-nested-column-2 > .fusion-column-wrapper {padding-top 0px !important;padding-right 0px !important;margin-right 0.98%;padding-bottom 0px !important;padding-left 0px !important;margin-left 0.98%;}@media only screen and (max-width1024px) {.fusion-body .fusion-builder-nested-column-2{width100% !important;}.fusion-builder-nested-column-2 > .fusion-column-wrapper {margin-right 0.98%;margin-left 0.98%;}}@media only screen and (max-width640px) {.fusion-body .fusion-builder-nested-column-2{width100% !important;}.fusion-builder-nested-column-2 > .fusion-column-wrapper {margin-right 0.98%;margin-left 0.98%;}}`

**Comment by JPH71** [comment]
Darned it... I will look at it now...
What agent scrapped the title?

**Comment by jfreiman** [comment]
How cani tell ech which agent actually scrapped the title?
I for this Collection I have it set up ton use the Gay Adult Films selected - but I think you are wanting to know which 'additional' agent was used: Internet Movie Film Database, be HomoActive, etc.
How can determine which was used on a per title basis?
Is there someplace on GitHub or a forum I can view/participate on that well help me get smarter at how the Agents work?

Sent from my T-Mobile 5G Device (yeah, it's really THAT fast)
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by jfreiman** [comment]
Well, I think I included that information with my previous post.
IAFD
https://www.iafd.com/title.rme/title=top+to+bottom+4/year=2018/top-to-bottom-4.htm

**Comment by JPH71** [comment]
When you click on the movie and bring up its poster it will show the
website the information was retrieved from... at the end of the green tick,
red Cross legend...

**Comment by jfreiman** [comment]
Well, many of my matches don't actually have the Cast Legend inserted into the Description - even though they are fully matched.
But with regards to this title, (Pulse Distribution) - Top To Bottom 4 (2018). I removed the match, cleared the bundles, rematched and it is fine - still matched with IADF's link in the Tagline. However, it doens't have the Cast Legend inserted.
I'm going through each Agent (sub-agent?) and verifying that they all have the, Place Cast Legend at Start of Summary?" checked.

**Comment by JPH71** [comment]
If theblegend is notat the start it should be at the end....

**Comment by jfreiman** [comment]
I discovered where the (some) of the logs are, but I want able to find one for that incuded the erroneous Director data.
However here are three logs from the same tile, Top to Bottom 4, which I think are relevant.

Maybe they show why the Legend isn’t appearing?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

________________________________

**Comment by JPH71** [comment]
Cheers man... I will look into this also... raise an issue in github xxx

**Comment by jfreiman** [comment]
I’m referring to the, “:: Film on IAFD 👎 :: ✅ / ❌ Actor on Cast List? :: GayHotMovies ::”

What are you referring to … that should be at the end?

***@***.******@***.***

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by JPH71** [comment]
Thats what I was referring too as you can see that title was scrapped by GayHotMovies...

That line can either be at the top or at the bottom of the film summary text...

**Comment by jfreiman** [comment]
🌝 I later realized that the box I was checking in the Plex Settings, Agents was to move the legend to the top, not it 'included.'
Thank you for your patience and eagerness to follow-up on my inquiries.

Sent from my T-Mobile 5G Device (yeah, it's really THAT fast)
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by JPH71** [comment]
mark as solved!
