### ISSUE TITLE
Actor Thumbnails and metadata aren't retrieved in IAFD

### ISSUE THREAD

**Issue by jfreiman** [CodyBerenson/PGMA-Modernized#144]
Cast Legends are not downloading for all titles.
Refreshing the Title/video does not retrieve the Legend.
It does download for many videos, but about 10-20% do not include the Legend even though it has a link left in the Tagline
I have attached the log for one of the Titles which isn't downloading the Legend 
![Screenshot 2022-03-13 171213](https://user-images.githubusercontent.com/10014964/158085960-3d27ee7e-b9ac-4ee7-8460-9a1ded6832ad.jpg)
![Screenshot 2022-03-13 170519](https://user-images.githubusercontent.com/10014964/158085961-3268eb13-9006-4f84-9e5f-0bf7f0083a46.jpg)
![Screenshot 2022-03-13 171156](https://user-images.githubusercontent.com/10014964/158085963-bd5ceda9-2af4-4f5f-839c-891540d262b1.jpg)
.

**Comment by JPH71** [comment]
Cheers xxx

**Comment by CodyBerenson** [comment]
@jfreiman:
The most recent release of IAFD fixes this issue.  Please retest.
