### ISSUE TITLE
GEVI has implemented CAPTCHA and has broken our agent

### ISSUE THREAD

**Issue by CodyBerenson** [CodyBerenson/PGMA-Modernized#147]
GEVI has implemented CAPTCHA, likely to stop services such as ours.  The GEVI agent is now broken.

**Comment by ScoBoXxX** [comment]
I noticed this several days ago.  Was hoping it would auto-resolve but I guess not.  DO you think there will be a fix for this or is GEVI going to be a bust going forward?  That would suck as it is my main agent for films :(

**Comment by vampirelayer** [comment]
Experiencing the same here.
Offending title is `(Lucas Entertainment) - Cuckolds & Alpha Cocks (2022)` if you would like to test.

**Comment by fivedays555** [comment]
There is an easy fix for that. Just add the referer in the header, it will work.

gevi_headers['referer'] = 'https://www.gayeroticvideoindex.com/new'
scraper.headers.update(gevi_headers)

**Comment by JPH71** [comment]
You are a star... going to implement this now xxxxxx

**Comment by CodyBerenson** [comment]
Huge KUDOS and THANKS @fivedays555.  GEVI is back in business!

**Comment by CodyBerenson** [comment]
@fivedays555:

Hope this finds you well!  @JPH71 wanted to once again say THANKS!  You're quick solution above is going to allow him to add an enhancement to IAFD.....for films, IAFD provides links to index sites that have the film's cover artwork, so Jason will be working on an enhancement that should allow the IAFD agent to crawl to film Film covers, since IAFD itself doesn't contain artwork other than Actor headshots.  

THANKS!
