### ISSUE TITLE
"Fix Match" Doesn't Clear Existing Data

### ISSUE THREAD

**Issue by jfreiman** [CodyBerenson/PGMA-Modernized#158]
I have many videos, both Scenes and Features which I have included Model Names in their Metadata -- Before discovering PGMA-M this is how ALL my videos were searchable for Studio, Model, Date, etc, but now I continue to use it - and other metadata fields for Titles which aren't in either IAFD or GEVI.
But I also use this data in other Fields not used by Plex to do searching and editing of my extensive Library in Windows Apps.
Enough about that....

**Problem**
When I have a title where Metadata, for example, Models is already listed in Plex, but with a black circle (firt letters of the model name) for the Model and I clear out the metadata from the video file and select "Fix Match..." in Plex, it does match and link and pull data via PGMA-M, but the Model circles are unchanged -- they don't replace/update the Model's circle with their image/photo.

**Current Solution**
I have been getting around this by "Unmatch"ing each video and in a second browser with Plex opened to the  Troubleshooting page, I Clean Bundles.  Then I can go back to the Videos page and do a new Match that forces PGMA-M to rebuild the metadata.

I'm sure there are other instances where this is an issue for other users as well, so I would appreciate a fix or a simpler workaround since I have a large collection and going through each video in Plex one by one is painful and time-consuming task.

**Comment by JPH71** [comment]
@jfreiman

Please be more specific about what these other fields are?
I do not know of any other metadata fields that are used to store actors
names etc other than the ones used by plex.
The fastest way to get the titles to match - is to take the video files out
of the library, run a scan against the same library, then put all the
videos back in.
This will force Plex to do a full refresh, sorting your issue out.

Plex sometimes locks fields after you have edited them, this could also be
a reason your fields are not updating, however this is unlikely with actors
as the fields are not directly accessible when editing a film's
properties...

Jason

**Comment by CodyBerenson** [comment]
"The fastest way to get the titles to match - is to take the video files out of the library, run a scan against the same library, then put all the videos back in. This will force Plex to do a full refresh, sorting your issue out. "

@jfreiman in case you aren't familiar, Jason is referring to The Plex Dance.  There's much written about it in the Plex Forums.  Here are the specific official steps:

**The Plex Dance**

1.    move all files for the media item out of the directory your Library is looking at, so Plex will not “see” it anymore
2.    scan the library (to detect changes)
3.    empty trash
4.    clean bundles (in menu next to server name, when accessed under ‘More’)
5.    double check naming schema and move files back
6.    scan the library

**Comment by JPH71** [comment]
Correct!!!!! Xxx

**Comment by jfreiman** [comment]
Thanks for this tip. I tried it last night and worked as you stated – saved me some time.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by CodyBerenson** [comment]
@jfreiman Please close this issue if resolved.  Thanks
