### ISSUE TITLE
Thumbor Update?

### ISSUE THREAD

**Issue by j-ktz** [CodyBerenson/PGMA-Modernized#161]
It seems  like  posters have stopped  fetching.  Do we have to update Thumbor?

**Comment by CodyBerenson** [comment]
@j-ktz it is our 90 day anniversary (again)....what did you get me???

Here's the new Thumbor address:  http://35.199.37.186:8888/unsafe

Please manually update your scenes agents settings:  

![image](https://user-images.githubusercontent.com/40373801/167206988-fe3d2242-baab-48c1-84af-b9c7a75c1ba0.png)

@jph71 Please update the four scenes agents.  If you'd like to me quickly do it and push to the master repository, I'm happy to....just let me know.

**Comment by j-ktz** [comment]
I'd happily get you  a coffee every 90 days if it means poster art. :) THANK YOU CODY

**Comment by CodyBerenson** [comment]
Deal....if by coffee you mean barrel aged from Kentucky.

**Comment by j-ktz** [comment]
I was thinking a Sbux email gift card, but your idea sounds way better.
