### ISSUE TITLE
IAFD ignoring Length and matches Film to Scene (same title)

### ISSUE THREAD

**Issue by jfreiman** [CodyBerenson/PGMA-Modernized#162]
For some reason video length settings aren't being honored and/or the production Year is being skipped over?

The movie I'm having issues with tonight is Men.com's, (The) Cock Stop 2022
This is a film that also has a scene with the same name from the previous year (the movie is created with scenes CS, CS2 & CS3)

Cock Stop Film (2022) [https://www.iafd.com/title.rme/title=cock+stop/year=2022/cock_stop.htm]
Cock Stop Scene (2021) [https://www.iafd.com/title.rme/title=cock+stop/year=2021/cock-stop.htm]

- My video files name: **(Men.com) - Cock Stop (2022).mp4** 
- Match against site's recorded length is set for both IAFD (4m) and "Sites" (6m)
- Video file length 74 minutes as reported correctly by Plex; the length reported by IAFD is 73 minutes - well within the above allowance for error.
- The Title is in both IAFD and GEVI and I have tried to match the file to either site by changing the order listed in Agents.
- I have stopped and restarted Plex Server and cleaned bungles as well before creating this trouble ticket.

Thanks in advance,

John

PS. I have had similar errors before for Scenes/Films in the **same year** but this has a different year! -- funny how PGMA(?) always blocks matches when GEVI and IAFD Years are not in alignment.  🤔

**Comment by JPH71** [comment]
I have just matched it today..
We have a power cut at the moment...
I named it as follows
(MEN) - The Cock Stop (2022)

You do not need the .com and the folm has a THE in front of it

Jason

**Comment by jfreiman** [comment]
Interesting, one of the filename permeations I used yesterday was, "(Men.com) - The Cock Stop (2022).mp4" and that didn't work.

So, I renamed the file as you referenced and it still isn't matching with the movie - still the scene.  However, just like my other attempts yesterday, adding "The" to the filename somehow breaks something and the Director is throwing up garbage and the background art shows a thumbnail page.

Yes.... I cleaned Plex's Bundles during each matching attempt - even though the filename physically changed.

When you matched it with the above filename did your result return 2 Cast members or 5?
Strangly, the cover art and background (back cover) are for the Film, not  the scene.
<img width="1117" alt="image" src="https://user-images.githubusercontent.com/10014964/167523454-669f7fd7-c2b7-4256-a998-f05f2e0b1bf1.png">
<img width="406" alt="image" src="https://user-images.githubusercontent.com/10014964/167523691-c8fb5833-5f47-47b1-a4a9-ef2bab9acc43.png">
<img width="334" alt="image" src="https://user-images.githubusercontent.com/10014964/167524096-05bde184-df13-4fa8-9f55-5b47e365a9b3.png">

**Comment by jfreiman** [comment]
Update: I used the same file name (no changes) and used the PGMA profile which matches to GEVI before IAFD.
This did match the Film title properly but did not correct the Director's garbage.
[https://www.gayeroticvideoindex.com/video/68531](url)

**Comment by JPH71** [comment]
I got the garbage too with the director...
I have sorted that bit out...
Looking at sorting the matching out so it picks the movie rather than the
scene..
Could you send a screen shot of your preferences for duration matching etc
for GEVI

**Comment by jfreiman** [comment]
Thanks for continuing to work on this issue.

The Preferences are the same for both -  6/4 (see image below)  Let me know if you think accuracy could be improved if I lower or raise the length -- I trim credits/warning from all Films (can't be bothered with the Scenes)

<img width="324" alt="image" src="https://user-images.githubusercontent.com/10014964/167536120-b453b11c-ad3f-4cbc-9121-b4032b1fd44c.png">

**Comment by JPH71** [comment]
Nearly done!

**Comment by jfreiman** [comment]
Thank you for the updates to the code.
I just left for 2 weeks and will have limited access while I'm away.
I'm sorry I can't test the fixes immediately.
I'll update this thread after I have been able to update PGMA.


Sent from my T-Mobile 5G Device (yeah, T-Mobile's Internet is really fast)
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
