### ISSUE TITLE
Cast Legend Doesn't Always Get Downloaded with Matches

### ISSUE THREAD

**Issue by jfreiman** [CodyBerenson/PGMA-Modernized#163]
I have the "Cast Legend" checked to always be at the start of Summary - so I can verify matches in both Film and Scene Detail View.

The trouble is, that even when matched with IAFD and others, the Legend doesn't always download (I like the 👍, etc).

Here is one recent example (out of too many) which matched IAFD, downloaded all the expected content, but didn't download/add the Legend Bar to the Summary.

Scrolling in the Detail View makes reviewing matches quite fast, as stopping to manually verify matches for each Title w/o the Legend adds a lot of time - and also means that over time, I have to re-verify each title manually.

**Comment by JPH71** [comment]
I am going to look at this one - let me know exactly how you named it on
disk and I will test it out and see what is happening. There was a time
back when I had an error in the legend code - it did not always work...
when you refresh this film does the legend re-appear?
I like this detailed view - I think I am going to start using it more...I
also prefer the legend at the top...

**Comment by jfreiman** [comment]
Top is always preferred.... But not necessary. 🤣

Refreshing does not add the legend.

I need to unmatch, clear Plex database and match again.

After that, the legend is added.

One thing I did with the first 12,000 (not joking) videos was to manually copy and paste the description into every scene and film -- before I discovered PGMA.
That was and ifi great and still great if metadata doesn't match or exist. However, matches and matched videos in Detail View look identical Everet ever except for the Legend.
Solving this issue will help me immensely, but I don't think it's as important to other/most order users -- so I understand if this isn't a priority.


Sent from my T-Mobile 5G Device (yeah, T-Mobile's Internet is really fast)
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by jfreiman** [comment]
Photos edited.

Sent from my T-Mobile 5G Device (yeah, T-Mobile's Internet is really fast)
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by jfreiman** [comment]
> @jfreiman I don't want this repository flagging any of Github's flags re: inappropriate images. I removed the image from your earlier post. When you post screen captures, please redact nudity. Thanks.

noted and images replaced.

**Comment by JPH71** [comment]
Checked the missing legend and this works... maybe you are using an old
version of the Agent?? I used a standard video file - so do not worry about
the length...
[image: image.png]

**Comment by jfreiman** [comment]
Well, for many of my videos added over the past year or more, they certainly were old versions of PGMA
I hate to refresh videos if I don't have to because I then have to change the background artwork from the PGMA back cover and/or the thumbnail page.
I MUCH PREFER the default thumbnail that Plex generates.

Sent from my T-Mobile 5G Device (yeah, T-Mobile's Internet is really fast)
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by JPH71** [comment]
Checked this - code works for the film title mentioned.
send me a list of other movies to confirm that the code is working.

**Comment by CodyBerenson** [comment]
@jfreiman Closing this issue.  If this issue persists, please open a new issue using the BUG template, and provide all information requested (e.g., site URL(s), upload logs, etc.).  Thanks
