### ISSUE TITLE
Collection by country not being created

### ISSUE THREAD

**Issue by joca879** [CodyBerenson/PGMA-Modernized#169]
Hello everyone, I hope you are well.

I had to redo my xxx library and I'm using the collections feature. 

I've detected, at least for the AEBN agent, that he is not creating the collection for the country of production, although the respective field has the data inscribed and the option for creating the collection enabled in the agent settings.

For studios, series, directors and genres, collections are being created correctly. Will it be a bug?

For example, the film World Of Spurt (2009), by the UK Naked Men studio, has the indication that the country is U.K. but the collection is not created.

**Comment by JPH71** [comment]
I will sort this out...

**Comment by joca879** [comment]
Thanks @JPH71 

I´m not sure if it happens also with the other agents, like GEVI or GayDVDEmpire. I only use this ones when the title is not in AEBN.

Another thing I remembered. If I want to add or remove another type of collection in the agents settings, do I need to eliminate and redo the all library again? I remember that I had not selected the collection for director in the agents settings, and after selecting it and refreshing the data, the collection was not created. I had to delete the library and clean the metadata, cache and plugins folders and recreate the library so that the collection was finally created... is that normal?

**Comment by JPH71** [comment]
Working on AEBN at the moemnt...

**Comment by JPH71** [comment]
AEBN - Film listings do not have a tag related to country of manufacture like GEVI has. And that is why this field is never updated...

However, 
1. I have looked through the categories i.e. genres and found only 3 which can be used to identify a country, namely British, Japanese Unmosaic and Russian.
2.  There was also French Speaking and Spanish Speaking, but these languages are spoken in multiple countries and also there are not many movies under this category.

AEBN's code has been updated to reflect this...
Wait for cody to notify you when he gets the code from me ....

**Comment by joca879** [comment]
Thanks for the info @JPH71 

I hadn't noticed that AEBN didn't have those tags related to the country.

I'll wait for Cody's indication then. Regards

**Comment by JPH71** [comment]
I have just sorted aebn...
It will pick up country 8nfo for the 3 categories I mentioned and will now
have chapets so you can skip to scene 3 if you want...
Just need two more routines in utils.py then I will send gevi, aebn,
gayhotmovies, dvdgayempire...

**Comment by joca879** [comment]
Thanks @JPH71!

Two questions: 

1. Following your indication, the countries that will be detected for collections are the United Kingdom, Russia and Japan, right? No collection will be created for films produced in the USA, is that it?

2. To create the missing collections, do i have to delete and recreate all the libraries again or just request an update of the metadata already with the new versions of the agents?

Regards

**Comment by JPH71** [comment]
Sorted - Code will be Cody soon..... This will be a testing release - versions will be updated when all agents are updated...

**Comment by JPH71** [comment]
Please mark as sorted...
