### ISSUE TITLE
Gevi was not pulling the full summary

### ISSUE THREAD

**Issue by JPH71** [CodyBerenson/PGMA-Modernized#17]
@CodyBerenson 

GEVI only scrapped the first paragraph of the summary. 
This has being corrected, it also now includes scene breakdowns if they are found.
I also came across some titles that had ratings - so these are now also scrapped.
I have tested against 80+ titles
Will send it in tomorrow - after I have checked the cast pictures....

**Comment by CodyBerenson** [comment]
Tested and fixed.  Thanks!
