### ISSUE TITLE
[BUG]: Manual Cast List in Filename Not Functioning

### ISSUE THREAD

**Issue by jocklover** [CodyBerenson/PGMA-Modernized#172]
When adding Cast List to filename, it does not show in Plex.

File Name: (Active Duty) - Below Deck (2007) - [Adam Wells, Kaden Saylor, Levi]
I did also test the cast list on another filename and it still showed the IAFD cast list instead of the manual list.

IAFD Agent Log:
[Manual Cast List not Working.txt](https://github.com/CodyBerenson/PGMA-Modernized/files/8784293/Manual.Cast.List.not.Working.txt)

I do reference this bug #171 but I don't think they are related so I have opened them separately. THANK YOU

**Comment by JPH71** [comment]
What agent are you using to scrape?

**Comment by jocklover** [comment]
Both test were done w/ results returned via IAFD using Scenes.

**Comment by JPH71** [comment]
Cheers...
Now iafd works slightly different because if it finds the film it will also
get the cast... so there is no need to have the cast appended to the file
name..
But I will add the code in to do this properly... this us an exercise that
will affect all the agents....

**Comment by jocklover** [comment]
If IAFD works differently, I totally understand. The only reason I was even trying to utilize this was because of #171 - maybe that should be more of the focus and then this won't be as much of an issue.
... However, I do see a use case where if I only have one scene of a movie, this could allows the cast list to be limited to just that of the scene vs all of the scenes.

**Comment by JPH71** [comment]
... However, I do see a use case where if I only have one scene of a movie, this could allows the cast list to be limited to just that of the scene vs all of the scenes. - **This should be sorted by Duration checking**, but at times there is no duration listed so I have sorted this out.
You will get the update soon!!!

**Comment by JPH71** [comment]
Please check if sorted....
