### ISSUE TITLE
[BUG]: GayHotMovies search may require capitalization

### ISSUE THREAD

**Issue by jocklover** [CodyBerenson/PGMA-Modernized#175]
It appears that site GayHotMovies may require correct capitalization to return search results for some titles.

Title: (Active Duty Productions;Active Duty) - Fraternizing Forces 2 (2012) - Scene 1
Site: https://www.gayhotmovies.com/video/224492/Fraternizing-Forces-2/

Log: [com.plexapp.agents.GayHotMovies.log](https://github.com/CodyBerenson/PGMA-Modernized/files/8839336/com.plexapp.agents.GayHotMovies.log)
 
As you will see, the search URL was: https://www.gayhotmovies.com/search.php?num_per_page=48&&page_sort=relevance&search_string=fraternizing+forces+2&find_with=all&searchtype_value=video_title - this returns no results. However, https://www.gayhotmovies.com/search.php?num_per_page=48&&page_sort=relevance&search_string=Fraternizing+Forces+2&find_with=all&searchtype_value=video_title does return the desired result.

**Note: I am having trouble repeating this with other titles - not sure why this one is being stubborn. Let me know if you have thoughts I can try instead. THANKS

**Comment by JPH71** [comment]
Cheers Man,

I am so glad that the community has taken on the testing with gusto

Jason xxx

**Comment by JPH71** [comment]
Darned it... you are right... this is so strange!
It pulls nowt from the website even when typed in manually.....

You could get away without having to have an IAFD studio by naming it like
this  *(Active Duty) - Fraternizing Forces 2 (2012) - Scene 1*

**Comment by jocklover** [comment]
Yeah, the dual studio was a result of trying to solve the match failure - I wasn't sure if "Production" was needed for a match (trying to be thorough). Didn't work with just Active Duty either.

**Comment by JPH71** [comment]
Studio matching was a big irritation for me...
So it works either by full match or partial match...

this was extremely useful for Next Door films, as they are registered as
either Next Door Studios, Next Door Taboo, Next Door Ebony on different
websites... So just entering Next door makes sure it matches on all
websites...

With Sean Cody and Men, you can also drop the *.com* * basically (Men.com)
becomes (Men)*

Hope this helps

Jason

**Comment by jocklover** [comment]
Appreciated - I do typically go short hand, clean studios.
However the issue here really came down to the a quirk w/ GayHotMovies - I couldn't even on-site query the title w/out caps in the title.

**Comment by JPH71** [comment]
Yes same here, it needed capitalisation to search on site...!!!!

As soon as I have finished AEBN, I will move on to GayHotMovies...

**Comment by JPH71** [comment]
Fixed - code will be with Cody soon
Note versions will not be updated until current rework of all agents is complete...
Please test and report all errors back!

**Comment by JPH71** [comment]
can we close this??

**Comment by CodyBerenson** [comment]
@JPH71 Closed!
