### ISSUE TITLE
Matching issue (Fagalicious)

### ISSUE THREAD

**Issue by ScoBoXxX** [CodyBerenson/PGMA-Modernized#177]
Can only report on fagalicious as that's where I found my match today.  But it's not matching.  Log attached.

Filename: (Next Door Studios) - Brandon Anderson takes Shane Cook’s girthy cock raw in “Busting Buddies” (2022)

Matched URL: https://fagalicious.com/next-door-studios-brandon-anderson-shane-cook-busting-buddies/

[com.plexapp.agents.Fagalicious.log](https://github.com/CodyBerenson/PGMA-Modernized/files/8910667/com.plexapp.agents.Fagalicious.log)

**Comment by CodyBerenson** [comment]
@jph71 FYI, I just tested, and I get the same result.

**Comment by j-ktz** [comment]
Same result here, no match.

**Comment by CodyBerenson** [comment]
Hi, @jph71 Just in case you need another test title that's not matching:

(HotHouse) - Max Lorde takes Max Konnor’s massive cock raw in “Sgt. Dick” (2021)

https://fagalicious.com/hothouse-max-konnor-max-lorde-sgt-dick/

[com.plexapp.agents.Fagalicious.log](https://github.com/CodyBerenson/PGMA-Modernized/files/8928597/com.plexapp.agents.Fagalicious.log)

Cheers!

**Comment by JPH71** [comment]
Cheers man...

**Comment by JPH71** [comment]
Can this be marked as fixed

**Comment by ScoBoXxX** [comment]
I think we can close this yeah.  Thanks for all your help.sent from iThumbs; please pardon iTyposOn Dec 20, 2022, at 3:25 PM, JPH71 ***@***.***> wrote:﻿
Can this be marked as fixed

**Comment by CodyBerenson** [comment]
@JPH71 Closed!
