### ISSUE TITLE
Create IAFD Agent for both Films and Scenes

### ISSUE THREAD

**Issue by CodyBerenson** [CodyBerenson/PGMA-Modernized#18]
Create a new agent to scrape both Films and Scenes from IAFD.  Although IAFD doesn't offer posters, it is a HUGE indexing site that has metadata that many of the other indexed sites do not.   It can be used as a 'last resort' when a film or scene can't be found anywhere else (and if not on IAFD, one can always manually update thru Plex itself).  Although IAFD has no posters to pull in, one can manually update the poster artwork if something better is found on Google.

@JPH71 I don't recall where the agent's development stands.  Are there updates you still wish to make?

**Comment by JPH71** [comment]
@CodyBerenson 
IAFD is good to go!
It may be a good idea if it is placed last at the bottom of the agents list as it seems to have more summary/scene information and it won't overwrite any artwork...
Think about it....

**Comment by CodyBerenson** [comment]
Right you are.  I forgot that you made the Synopsis then Scene Breakdown edit.  I'll push to the master repository in a bit.

**Comment by JPH71** [comment]
I was just going to place the zip here, as i think it was mixed up with the other scene agents... but as you have it no need.....

**Comment by JPH71** [comment]
Cool!
I need to start hunting for some more blogs to scrape....
I can't believe there is just fagalicious, quuerclick and waybig.....
