### ISSUE TITLE
[BUG]: IAFD Not Matching w/ TWO Secondary Titles

### ISSUE THREAD

**Issue by jocklover** [CodyBerenson/PGMA-Modernized#180]
Seeing issues where there are **two** secondary titles on IAFD. No issues matching when there is only one secondary title in IAFD.
Seen this with a few titles (all KinkMen, but I don't think that it is studio exclusive).

Sample:
(30 Minutes of Torment) - One Of The Most Intense 30MT To Date! (2014)
https://www.iafd.com/title.rme/title=30+minutes+of+torment+35311/year=2014/30_minutes_of_torment_35311.htm
You will see the scene is titled as the following **3** titles:
30 Minutes Of Torment 35311
Beg Me to Hit You Again
One of the most intense 30MT to date!

Log:
[IAFD Tertiary Title - Failure.txt](https://github.com/CodyBerenson/PGMA-Modernized/files/8937334/IAFD.Tertiary.Title.-.Failure.txt)

**Comment by JPH71** [comment]
This is not a failure: This is how info is retrieved
One puts in a search string
a list of titles is returned
each film name in the list is matched to your filename on the disk
if it matches it opens the films page from the list - where it then collates all the info needed for plex.

IAFD can search on alternate titles - but it does not show these on the search results list.
And it would be too much of a strain on IAFD - if we have to load each page in the list to view its alternate title...
As it stands IAFD introduced cloudflare to protect itself... we can not overwhelm it with requests.

The logical suggestion is to use the title on the search return list as your filename.

In this case use either
(Kink) - 30 Minutes Of Torment 35311 (2014)
(30minutesoftorment) - 30 Minutes Of Torment 35311 (2014)

**Comment by JPH71** [comment]
Not a Bug....

**Comment by jocklover** [comment]
When I use an alternate title for a film where IAFD only lists **one** alternate title, a match is successful. However, when IAFD lists **two** alternate titles, matching fails. Querying IAFD manually for the either alternate title still returns the film.
You can see in the originally attached Log File that IAFD returned the film to PGMA based on the alternate title, however PGMA was unable to handle it. It appears the disconnect was that IAFD returned the Site Title as "Beg Me to Hit You Again / One of the most intense 30MT to date!" which is both alternate titles on IAFD combined (see line 75 for log).
Can we add handling to PGMA to match to the title before _and_ after the "/"? (Maybe to ensure matching, PGMA matches against the entire title _and_ either half when a "/" is present.)

**Comment by JPH71** [comment]
Yes iafd will return a search result based on the alternate title...
However when you use this alternate title, the search results do not show
the alternate title in the search results...
The IAFD then goes through the search results matching the filename against
this list.
When it finds a match it opens the films page where it can then see the
alternate titles...
Yes this can be coded... but iafd in the past few months have introduced
cloudscape to protect themselves from scraping..
You can also see at times that the iafd agent will fail on iafd when a lot
of requests are made as cloudscape starts to be suspicious of the
activity...
This stops scraping all together...
By getting the agent to open each link on the list will at minimum double
the request to iafd ... this will then notify the Web owners to pit in more
stringent controls further causing more issues for us...
It would make more sense just to use the name that appears on the search
list to avoid this...
As you mat have noticed a couple of months ago GEVI also enhanced its
protection to counter scraping...
We need to maintain as small a footprint as possible...
That is my concern...

**Comment by JPH71** [comment]
I will look through your log tomorrow to see if there is any other way to
affect your needs... but from what I looked at with the title you mentioned
in the issue... that was the result of my investigations... naming it with
its prime name matched..
I have sent the updated code to Cody... it should be available soon for you
to test...
I have also sorted out the other issues with IAFD.. un regard to ampersands
and brackets roman numerals

Jason xxx

**Comment by JPH71** [comment]
Treat IAFD like waybig and fagalicious... the name of the film has to match
with the main title....

**Comment by CodyBerenson** [comment]
I've retested and can confirm that films with multiple AKAs match properly when matching using the primary title.  Per the discussion above, we won't modify the agent to match on AKAs when there are multiple AKAs.  I will open a new enhancement to capture the AKAs in the metadata for IAFD.
