### ISSUE TITLE
[BUG]: IAFD Not Matching w/ "&" in Title (Secondary Title?)

### ISSUE THREAD

**Issue by jocklover** [CodyBerenson/PGMA-Modernized#181]
IAFD not matching when "&" in scene title. I am specifically working w/ secondary titles so not sure if this applies to primary titles as well.

Reviewing LOG, PGMA is converting "&" to "and" in the query URL however this does not return matches. Adjusting query URL to "&" returns the desired title.

Samples Title:
(30 Minutes of Torment) - Straight Southern Boy Endures A Hard Beating & Humiliating Ass Fuck (2016)
https://www.iafd.com/title.rme/title=30+minutes+of+torment+39622/year=2016/30-minutes-of-torment-39622.htm
LOG Query URL: https://www.iafd.com/results.asp?searchtype=comprehensive&searchstring=Straight+Southern+Boy+Endures+A+Hard+Beating+and+Humiliating+Ass+Fuck
Working Query URL: https://www.iafd.com/results.asp?searchtype=comprehensive&searchstring=Straight+Southern+Boy+Endures+A+Hard+Beating+&+Humiliating+Ass+Fuck
LOG:
[IAFD & not matching.txt](https://github.com/CodyBerenson/PGMA-Modernized/files/8937394/IAFD.not.matching.txt)
 
Additional titles:
(Men On Edge) - Online Hookup Ends With Tickling & Edging In Bondage For A Hung Ginger (2017)
https://www.iafd.com/title.rme/title=men+on+edge+41628/year=2017/men-on-edge-41628.htm
(Bound in Public) - Hung Stud Has His Balls Stretched, Ass Gang Fucked, & Prostate Milked (2014)
https://www.iafd.com/title.rme/title=bound+in+public+34888/year=2014/bound-in-public-34888.htm

**Comment by JPH71** [comment]
Code will be with Cody soon...

**Comment by JPH71** [comment]
Sorted - code will be with Cody soon

**Comment by JPH71** [comment]
If sorted please mark as fixed

**Comment by jocklover** [comment]
Apologies for falling off, retried the titles exactly as above and no match. Using version from 1/12/23, removed and replaced all plugin files then restarted Plex.
Does the "&" need to be represented as "%26" (instead of as "and") to yield IAFD match?:
https://www.iafd.com/ramesearch.asp?searchtype=comprehensive&searchstring=Online+Hookup+Ends+With+Tickling+%26+Edging+In+Bondage+For+A+Hung+Ginger&FirstYear=2014&LastYear=2018&Submit=Filter

[IAFD Log - & Matching.txt](https://github.com/CodyBerenson/PGMA-Modernized/files/10443198/IAFD.Log.-.Matching.txt)
