### ISSUE TITLE
No Match - Too Many Results - QueerClick

### ISSUE THREAD

**Issue by jocklover** [CodyBerenson/PGMA-Modernized#182]
Seeing issues where I am not getting a result due to too many results returned. I am specifically seeing this in QueerClick and it appears to be a limitation of QueerClick not PGMA.
The titles I am seeking to match are unfortunately 1 word titles - Radek; Carl; Greg, William.

Sample:
(19Nitten) - Radek (2013)
https://www.queerclick.com/twinks/2013/02/19nitten_radek.php
Log: [QueerClick - Too Many Results.txt](https://github.com/CodyBerenson/PGMA-Modernized/files/9060134/QueerClick.-.Too.Many.Results.txt)
 
Does PGMA need to utilize the studio in the search URL? Will this break other functionality? (Searching QueerClick.com for "19nitten Radek" does yield the desired result.)

**Comment by JPH71** [comment]
Could you check if I have sorted this out???

**Comment by jocklover** [comment]
Sorry for dropping off, the above title is working, thanks.

**Comment by JPH71** [comment]
No worries man!!!
