### ISSUE TITLE
https://cdn.vigue.me/unsafe seems to be offline

### ISSUE THREAD

**Issue by CodyBerenson** [CodyBerenson/PGMA-Modernized#19]
@acvigue 

Hi A.  The thumbor instance seems to be offline.  Can you give it a check, please?  

Thanks!

**Comment by CodyBerenson** [comment]
@acvigue 

Hi A.  Hope you're well.  Not sure you got the earlier ping.  Can you give the thumbor instance a check please?  The instance is offline.  Please help!

Thanks!

**Comment by CodyBerenson** [comment]
@acvigue

Pinging you again.  Hi A. Hope you're well. Not sure you got the earlier ping. Can you give the thumbor instance a check please? The instance is offline. Please help!

Thanks!

**Comment by acvigue** [comment]
Hey it should be fixed now, had to focus on schoolwork for the next year (still in college :p) I'll try to be more active now as I had email notifications off. I forgot to renew the certificate for the thumbor. Sorry for any troubles.

**Comment by CodyBerenson** [comment]
@acvigue 

Hi A.  Glad to hear you're well.  Really appreciate the support.  Good luck in your studies!
