### ISSUE TITLE
[Feature Request}: Capture IAFD AKA(s) in the Metadata

### ISSUE THREAD

**Issue by CodyBerenson** [CodyBerenson/PGMA-Modernized#192]
**Is your feature request related to a problem? Please describe.**
See #180 for more context

![image](https://user-images.githubusercontent.com/40373801/184548270-62984b05-fca7-4237-9d61-1f15d09c67a2.png)

**Comment by JPH71** [comment]
I will find out how to put the AKAs in the metadata...

**Comment by CodyBerenson** [comment]
The coding for the enhancement is complete and in the Release Testing repository.  Per @JPH71:

Hi Cody

Here is the latest IAFD:

Original Title populated with AKA from IAFD - thanks for this suggestion as there also loads of movies that have this...
image.png

**Comment by JPH71** [comment]
Can we close this as done?

**Comment by CodyBerenson** [comment]
@JPH71 Closed!
