### ISSUE TITLE
Matching Issue - YMAC Studio; YMAC

### ISSUE THREAD

**Issue by dodecaphone** [CodyBerenson/PGMA-Modernized#193]
GEVI has the movie as "YMAC Video - Memories of Eighteen"
https://gayeroticvideoindex.com/video/713
Tried "(YMAC Video) - Memories of Eighteen (1988) Scene 1.avi" - _No match_.

However, IAFD has it as "YMAC - Memories of 18"
https://www.iafd.com/title.rme/title=memories+of+18/year=1988/memories-of-18.htm
Tried "(YMAC Video;YMAC) - Memories of 18 (1988) Scene 1.avi" - Again, _no match_.

Can someone advise as to why I may not be getting a match? Is my file nomenclature wrong?

**Comment by CodyBerenson** [comment]
Hi @dodecaphone,

You're just missing a dash (i.e. "-") preceding Scene 1.avi

Recall the instructions for labeling files:

![image](https://user-images.githubusercontent.com/40373801/190711619-72e19927-9d5b-407f-b2e8-c326e0b3d153.png)

So, when the file is properly named:  (YMAC Video) - Memories of Eighteen (1988) - Scene 1.avi it matches correctly:

![image](https://user-images.githubusercontent.com/40373801/190711916-4a01d554-0a2b-4e86-b7e6-3a7f3b572921.png)

Cheers!

**Comment by dodecaphone** [comment]
D'oh. Thank you!!!

**Comment by JPH71** [comment]
Believe you me _ I eff up a load of times and I set up the programming
rules to detect the patterns:
(studio) - Film title (year) - (parts No.) etc ......
