### ISSUE TITLE
[BUG]: WayBig Matching Error (Search Query Failure)

### ISSUE THREAD

**Issue by dodecaphone** [CodyBerenson/PGMA-Modernized#194]
# Mandatory #

## Describe the bug: ## 
WayBig log notes that it is dropping a word; leads to failed match

## Specific Agent(s) Causing the Issue: ##
WayBig

## Index Site URL(s) Attempting to Match: ##
https://www.waybig.com/blog/2022/08/08/helix-studios-aiden-garcia-and-dante-clark-flip-fuck-in-bowling-lesson/

## Log Attached: ##
Yes
[com.plexapp.agents.WayBig.log](https://github.com/CodyBerenson/PGMA-Modernized/files/9591759/com.plexapp.agents.WayBig.log)

# Optional #

## Screenshot(s) with all nudity redacted: ##
![aiden-garcia-dante-clark-bowling-lesons-helixstudios-01](https://user-images.githubusercontent.com/20006508/190859032-a9710e38-105a-485a-9d7b-251b1576a025.jpg)

## Additional Context: ##
![Screenshot 2022-09-17 062028](https://user-images.githubusercontent.com/20006508/190859074-cd243891-2c47-4da1-a9de-0c70f2bd4f94.png)

## Desktop (please complete the following information): ##
 - OS: [e.g. iOS] - Windows 10 Pro
 - Browser [e.g. chrome, safari] - Firefox
 - Version [e.g. 22] - 104

**Comment by CodyBerenson** [comment]
Hi @dodecaphone 

Waybig changed their approach recently, including how it handles apostrophes.  I just tested this title using the Waybig agent that is in our Release Testing repository and it matches as expected.  

![image](https://user-images.githubusercontent.com/40373801/190860961-8b714440-5e4f-471b-a1cb-1efc53a00953.png)

You may consider downloading the agents in our Release Testing version, and swapping them (or at least Waybig) out for the agents in your current plug-ins.  

Cheers!

**Comment by dodecaphone** [comment]
Thank you! I will do that.

**Comment by JPH71** [comment]
Phew....
