### ISSUE TITLE
Cover Art?

### ISSUE THREAD

**Issue by MaseSpace** [CodyBerenson/PGMA-Modernized#195]
maybe im doing something wrong or maybe Im misunderstanding the metadata agents. NONE of my media will match with a Poster/Cover Art, no matter how thoroughly I follow the guide posted. it won't change any studios or anything either, its just as blank as before I added the agents. Can you point me in the right direction? I've tried with media from a few different studios

**Comment by JPH71** [comment]
Assuming that you are on a windows system:

1. Download the latest Agents
2. Install all the agents to the plug-in folder:  C:\Users\**Your User Name**\AppData\Local\Plex Media Server\Plug-ins
3. The agents all end with **.bundle**
4. Make sure that you also copy the **_PGMA** folder to the same folder, at the same level as the bundles
5. Restart your plex server
6. When plex reloads go to **Settings** then **Agents**
7. Select **Gay Adult Films** - you will see the list of agents
8. For each agent - click on the **Gear** symbol to load the agent's preferences.
9. Make your choices and save.
10. After finishing this click on **Gay Adult Scenes** and do the same for the scene agents.
11. Restart the Plex app
12. Select on film title and refresh its metadata

Sorry, for the delay in replying to you. Let me know if you have any other issues....

**Comment by CodyBerenson** [comment]
@JPH71 @MaseSpace 
Can this issue be closed?
