### ISSUE TITLE
[BUG]: Films with same name

### ISSUE THREAD

**Issue by XanderKwan** [CodyBerenson/PGMA-Modernized#198]
# Mandatory #

## Describe the bug: ## 
There are 2 movies with the same name and released one year apart. One is Hole Buster 1 (2010) and another is Hole Buster (2011). Both are from the same studio (Hot House Entertainment). Plex only pulled the information of Hole Buster (2011) for Hole Buster 1 (2010). I tired to change names but it still doesn't work.
I checked the AEBN to see if they only have one film on their database but they have both.
## Specific Agent(s) Causing the Issue: ##
AEBN iii
## Log Attached: ##

# Optional #

## Desktop (please complete the following information): ##
 - MacOS
 - Safari

**Comment by JPH71** [comment]
You hit the same issue as I did...
I think this is sorted in the latest release of GEVI...

I will look at it in another hour to see how I named them and let you
know...

**Comment by JPH71** [comment]
This is how I named them
[image: image.png]

[image: image.png]

[image: image.png]

**Comment by XanderKwan** [comment]
Thank you, I'm new here. Not sure why I can't see pictures...

**Comment by JPH71** [comment]
@XanderKwan

The pictures only showed that they had scraped....

Jason

**Comment by JPH71** [comment]
I just did a blondy here and realised i had put pictures....
here is how i named
(Club Inferno) - Hole Busters (2010).avi
(Hole Busters) - Hole Busters 1 (2011).avi
(Hole Busters) - Hole Busters 2 (2011).avi

**Comment by JPH71** [comment]
Please mark as closed...
