### ISSUE TITLE
[BUG]: No Metadata downloaded

### ISSUE THREAD

**Issue by eugenvontrotta** [CodyBerenson/PGMA-Modernized#199]
# Mandatory #

## Describe the bug: ## 
The Movie seems to be recognized correctly, but then seems to fail to write the metadata to the database.
Plugin downloaded and installed today.

## Specific Agent(s) Causing the Issue: ##
All Agents I've tried, mainly GEVI and AEBN

## Index Site URL(s) Attempting to Match: ##
https://gay.aebn.com/gay/movies/249554/lords-of-paris
https://gayeroticvideoindex.com/video/65137

## Log Attached: ##
[com.plexapp.agents.GEVI.log](https://github.com/CodyBerenson/PGMA-Modernized/files/9995506/com.plexapp.agents.GEVI.log)
[com.plexapp.agents.AEBNiii.log](https://github.com/CodyBerenson/PGMA-Modernized/files/9995507/com.plexapp.agents.AEBNiii.log)

Database-Entry:
[Info.xml.txt](https://github.com/CodyBerenson/PGMA-Modernized/files/9995508/Info.xml.txt)

# Optional #

## Desktop: ##
 - PMS: 1.29.2.6334 on Synology DS720+, DSM7.1.1-42962 Update 2
 - OS: MacOS Monterey 12.5.1
 - Browser: Chrome Version 107.0.5304.87 (Official Build) (arm64)

**Comment by JPH71** [comment]
@eugenvontrotta

Firstly there is a later version in PGMA.
I see that it is failing when it tries to process the genres.
Ensure that you also have the _PGMA folder in the plugins folders where
GEVI, AEBN, GayDVDEmpire and the rest reside.
Without the _PGMA folder - the agents can't tidy up the numerous genres
that are different on the various sites. This folder and its contents are
necessary for the new style agents to work


Jason xxx

**Comment by eugenvontrotta** [comment]
@JPH71 thank you very much for your quick reply. I'm not really sure what you mean with there was a later version in PGMA. I've downloaded the most recent version today. I've also copied the _PGMA folder with all files and subfolders to the plugin folder:

![Screenshot 2022-11-12 21 03 43](https://user-images.githubusercontent.com/95425331/201492546-42338d78-0d9b-48bc-9bdc-126dcc9775ac.png)

Lothar xxx

**Comment by JPH71** [comment]
@ eugenvontrotta

Could you run a metadata refresh again against one file and send me the log
to look through.
Now that we have established that you have the latest version and the _PGMA
folder....

Could you check that the _PGMA folder has sub-folders beneath it also -
just to make sure....

I am working on GEVI at the moment - so if there are any errors, I can fix
them then send the latest release to Cody...

Cheers

Jason x

**Comment by eugenvontrotta** [comment]
@JPH71 

Jason, I've rerun a metadata refresh. Please find the log data here:
[com.plexapp.agents.GayAdult.log](https://github.com/CodyBerenson/PGMA-Modernized/files/9996011/com.plexapp.agents.GayAdult.log)
[com.plexapp.agents.AEBNiii.log](https://github.com/CodyBerenson/PGMA-Modernized/files/9996012/com.plexapp.agents.AEBNiii.log)
[com.plexapp.agents.GEVI.log](https://github.com/CodyBerenson/PGMA-Modernized/files/9996013/com.plexapp.agents.GEVI.log)

And this is what my _PGMA folder looks like:
![Screenshot 2022-11-12 22 33 11](https://user-images.githubusercontent.com/95425331/201495630-33d4e2f6-bf78-4527-8074-fe7eaeaff068.png)

Thanks a lot for your efforts!
Cheers,
Lothar-

**Comment by JPH71** [comment]
Hi Eugen,

Could you send me your email...

I see you are using Linux, whilst I develop in Windows....

I can then send you a utils.py, that I am currently working on and we can
get the process to go past the setup.....

We will test it first in GEVI.

Cheers

**Comment by eugenvontrotta** [comment]
@JPH71 it's tristanphil@gmx.net

**Comment by JPH71** [comment]
Brilliant - I will send it in a couple of minutes....

I would like to see if you get the setup part working.... do not worry if
it fails further down the line, as it's work in progress...

Jason

**Comment by JPH71** [comment]
Cheers!
