### ISSUE TITLE
GEVI Update

### ISSUE THREAD

**Issue by JPH71** [CodyBerenson/PGMA-Modernized#21]
@CodyBerenson 
I have made a number of changes to GEVI's search string. 
These were the issues for a number of files...
if the title had a digit in it - it split the search string at the point of the digit...
for example
**(All Worlds Video) - Thr3 The Hard Way (2010).avi**
the search title after processing returned th instead of thr as intended.. this **th** was passed to GEVI as the search string...
In addtion to this GEVI searched for all files containing the search string, in this case all words containin th would be picked up and searched through.... in this case it got to 165 pages before i cancelled...

I have changed the search so that if the first word of a movie is numerical it will search on this number,
If the first word contains mixed alpha and numeric it will search on this 
if there is a standalone digit for example **hard cocks 2 - ouch**.... it will take hard cocks as the search and thr3 the hard way will be processed as Thr3 The Hard Way

lastly GEVI now searchs on strings starting with the search string rather than containing the search string, this means fewer results are returned and processing is faster.

if the search returns no titles it quits immediately, this did not allows happen as there was an error in the code, in relation to the newly enhanced multiple page processing.

**Comment by CodyBerenson** [comment]
mui complicado....I'll do my best to test...i'll reread (once i'm not a few vodkas in) to see if i can find good test cases.  More likely, I'll just test to make sure that normal stuff works.

**Comment by JPH71** [comment]
I just realised I did not attach the code - oooops

[GEVI.bundle.zip](https://github.com/CodyBerenson/PGMA-Modernized/files/4576197/GEVI.bundle.zip)

**Comment by CodyBerenson** [comment]
you did.  i downloaded and deleted.  I always do that so there aren't version control issues for folks out there in case the bundle has issues.

Now you see it, now you don't

**Comment by JPH71** [comment]
Use the latest one I made a slight change... I changed replace "'s " to ""
to "'s " to " " as a jet set film Anthony's Weener turned to Anthonysweener
and couldn't be found on GEVI

**Comment by CodyBerenson** [comment]
1.  The google cloud crapped out.  perhaps its better to attempt it when I
drink.

2.  because its down, the WayBig agent got so crapped out on locked up
processes it was creating that it just wouldn't fire.  Fag and QC still
worked, but WayBig dies when processing lots of files.  Can you see if
there's any difference between the way WayBig is firing off the vbs and the
other two...that is hanging up all these processes?
[image: image.png]

**Comment by JPH71** [comment]
Hi Cody

I will look into that - but the only difference between waybig and the
other two is the way it searches for clips...
the update section is rather bog standard...
Waybig does up to 4 searches per title depending on the way waybig presents
its titles....
I will look into harmonising that aspect....

**Comment by JPH71** [comment]
latest GEVI
sorted out accented letters when building http strings to search on IAFD for actor pages
hopefully sorted out numerics in titles
here it is ... thirdy fourth time lucky...


[GEVI.bundle.zip](https://github.com/CodyBerenson/PGMA-Modernized/files/4578533/GEVI.bundle.zip)

**Comment by CodyBerenson** [comment]
ok, i'm testing now.  i'm primarily going to make sure it still functions as expected....not sure how to get my arms around all the specific issues you've addressed and how to find test cases for them...

I'll report back.

**Comment by CodyBerenson** [comment]
@JPH71 
I threw about a dozen movies at it.  all perfectly matched, quickly too.  i don't think i tested any of the peculiar circumstances although i did have an actor with an accent in their name that matched and returned a photo.

I'll go ahead and push the code to the master repository
