### ISSUE TITLE
[BUG]: Cannot Match (Falcon) - The Best of Jeff Palmer

### ISSUE THREAD

**Issue by fourstix** [CodyBerenson/PGMA-Modernized#214]
# Mandatory #

## Describe the bug: ##   
I'm trying to match a file named (Falcon) - The Best of Jeff Palmer.  It appears to find a match, but it takes along time and apparently then quits without updating the Plex entry with the Meta-Data.  The log files appear to break of abruptly.  One thing to note is that actor list for this movie is very long.  I think that it's either timing out or going past some limit.

## Index Site URL(s) Attempting to Match: ##
https://gayeroticvideoindex.com/video/44954
https://www.gaydvdempire.com/1547581/best-of-jeff-palmer-the-gay-porn-movies.html?partner_id=56800950

## Log Attached: ##
[com.plexapp.agents.GayEmpire.log](https://github.com/CodyBerenson/PGMA-Modernized/files/10374394/com.plexapp.agents.GayEmpire.log)
[com.plexapp.agents.GEVI.log](https://github.com/CodyBerenson/PGMA-Modernized/files/10374395/com.plexapp.agents.GEVI.log)

# Optional #

## Screenshot(s) with all nudity redacted: ##
The movie just appears with the directory name "Jeff Palmer" and the metadata is not updated.
![image](https://user-images.githubusercontent.com/5274281/211341570-5e4c00ae-28a5-4b65-8c7c-e09d7369bc3f.png)

## Additional Context: ##
1) One thing to note is that actor list for this movie is very long.   The movie is not found on IAFD.
2) The GayEmpire agent is failing with:
2023-01-09 09:54:46,328 (7f9636e66b38) :  INFO (sandbox:19) - GayEmpire  - SEARCH:: Reading Site URL page         http://www.gaydvdempire.com/1547581/best-of-jeff-palmer-the-gay-porn-movies.html
2023-01-09 09:54:46,361 (7f9636e66b38) :  DEBUG (networking:138) - Fetching 'http://www.gaydvdempire.com/1547581/best-of-jeff-palmer-the-gay-porn-movies.html' from the HTTP cache
2023-01-09 09:54:46,384 (7f9636e66b38) :  CRITICAL (agentkit:1018) - Exception in the search function of agent named 'GayEmpire (IAFD)', called with keyword arguments {'id': '1498', 'guid': 'com.plexapp.agents.GayAdultFilms://1498?lang=en', 'force': True, 'primary_agent': 'com.plexapp.agents.GayAdultFilms', 'parentID': None} (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/PlexMediaServer/Resources/Plug-ins-629d58034/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/api/agentkit.py", line 1011, in _search
    agent.search(*f_args, **f_kwargs)
  File "/share/CACHEDEV1_DATA/.qpkg/PlexMediaServer/Library/Plex Media Server/Plug-ins/GayEmpire.bundle/Contents/Code/__init__.py", line 293, in search
    return FILMDICT['Status']
UnboundLocalError: local variable 'vReleaseDate' referenced before assignment

3) The GEVI agent simply stops while trying to match actors.
2023-01-09 09:55:18,268 (7f405389cb38) :  INFO (sandbox:19) - GEVI  -       ----------------------------------------------------------------------------------------------------
2023-01-09 09:55:18,269 (7f405389cb38) :  INFO (sandbox:19) - GEVI  - UTILS :: Unmatched Cast Name           25 - Jason Branch/jasonbranch
2023-01-09 09:55:18,272 (7f405389cb38) :  INFO (sandbox:19) - GEVI  - UTILS :: CloudScraper Request:         https://www.iafd.com/ramesearch.asp?searchtype=comprehensive&searchstring=Jason+Branch
(End of File)

4) I am using the latest test version of agents, but the error also occurred in the current version of agents in the main branch.
  

## Desktop (please complete the following information): ##
 - OS: [e.g. iOS]  Windows 11 Home 22H2
 - Browser [e.g. chrome, safari]  Firefox
 - Version [e.g. 22] Firefox 108.02 (65-bit)

## Server: ##
- NAS: QNAP T-251+
 - OS:  QNAP QTS 5.0.1.2248 (Ubuntu)
 -  Plex: Plex Media Server 1.30.0

**Comment by JPH71** [comment]
Thanks for finding that error on GayEmpire.... I always date my films your
leaving out the (2010) - made me realise I had not fully tested all the
agents properly with none-year names.

In regards to GEVI, I have an issue though this seems to be a Plex
issue for the past 6/7 versions
I can only seem to scrape 10-20 films at a go before plex crashes out
I get this error, in windows from the event viewer.... this is an issue
that has been highlighted by many - but I have not found a solution to
it....

Could you look into the equivalent on your system??











*Faulting application name: Plex Media Server.exe, version: 1.30.0.6486,
time stamp: 0x6391a3aaFaulting module name: ucrtbase.dll, version:
10.0.19041.789, time stamp: 0x2bd748bfException code: 0xc0000409Fault
offset: 0x000000000007286eFaulting process ID: 0x3280Faulting application
start time: 0x01d92464ba0cb4c9Faulting application path: C:\Program
Files\Plex\Plex Media Server\Plex Media Server.exeFaulting module path:
C:\WINDOWS\System32\ucrtbase.dllReport ID:
c1be2ba3-96c1-48fe-b5fb-d2fcd29f34a4Faulting package full name: Faulting
package-relative application ID:*

**Comment by fourstix** [comment]
Hi Jason,
I don't see any errors in the QNAP system logs.  That's not unusual since QNAP has them locked down and generally only system functions can log errors.  Individual applications have to log in their own logs.  I re-ran the Match and attached the Plex Media Server log.  I don't see any errors there, but I attached the log in case it's helpful.
[Plex Media Server.log](https://github.com/CodyBerenson/PGMA-Modernized/files/10382471/Plex.Media.Server.log)

Jeff was a very busy boy, and his "Falcon The Best of..." movie  listing has 38 actors.  That's why I suspect the meta-data has gone over some limit.  Maybe it's a Plex Media Server limit and the meta-data update request is just being ignored.

Another movie I had a similar problem was with Falcon Best of the 1970s Vol 1.  It has a huge cast list.  It would fail the same way, the GEVI agent would run without errors, but the meta-data wasn't updated.  Then I found that Falcon had re-released the movie under a different name (Falcon Icons: The 1970s) with a smaller cast list, 24 actors vs 45.

I was able to rename the movie and match it on that name.  Then again, it might be something else.  

Best regards,
Gaston

**Comment by JPH71** [comment]
I will try it on my system and let you know...
Are you enabling collections...
I haven't looked at the log as I sm at work, but I sm assuming you are
using GEVI...

Jason

**Comment by fourstix** [comment]
Hi Jason,
I have all collections turned off.

Gaston

**Comment by JPH71** [comment]
That is strange... as that is the largest overhead...

**Comment by JPH71** [comment]
I will try it shortly

**Comment by JPH71** [comment]
I have managed to scrape the film
[image: image.png]

I made no significant changes to the code that would affect this.
It failed the first time just like yours did....
This is as you suggest because there are loads of actors and genres....
I got it to work by rebooting my computer and scrapping the title as soon
as it rebooted....

I have made changes to GayEmpire to cater for the error that arose when a
date was not included in the file name.

I will send the code to Cody to upload into the repository.

I have also put in code to try and retrieve the Plex Token on MAC OS

Jason

**Comment by JPH71** [comment]
By the way, I did not turn off the collections - so in addition to the
Genres and Actors, I had an extra 71 collections to add to the metadata

Jason

**Comment by fourstix** [comment]
Well. I just can't seem to get that lucky.  I can try starting and stopping
Plex but I'm not sure if that will help.

 Could it be possible to have a setting to limit the cast to a maximum
number or zero for unlimited?

Best regards,
Gaston

**Comment by JPH71** [comment]
Yes it is possible to limit the number of cast...
I will start rhinking about that...
I did not restart the plex servir, I rebooted the whole computer...

**Comment by fourstix** [comment]
Yes.  Rebooting the whole computer is more drastic in a Linux system like QNAP.   Linux has tools to manage that, the trick is that QNAP hides them behind their own tools.

Here's what I did in QNAP:

First I stopped Plex Media Server, then I ran the utility program (QBoost) to clean any unused, un-returned memory, then I restarted Plex Media Server, and re-ran the match.  

Then I went out for a walk, and when I came back an hour later, the GEVI agent had matched successfully!  Hooray!

Thanks,
Gaston

**Comment by JPH71** [comment]
Could you mark this as closed.....

**Comment by fourstix** [comment]
Closed.  Able to match after freeing memory

**Comment by JPH71** [comment]
Cheers man!!!
