### ISSUE TITLE
Cannot match first movie 

### ISSUE THREAD

**Issue by AussieGuy64** [CodyBerenson/PGMA-Modernized#216]
Hi
I have just found this Plex scanner and am unable to match my first movie - (Falcon Studios) - Splash Shots 1 Memories of Summer (1984). 

I am using PMS on WIn10. I am sure it is something I have set incorrectly but have tried several times and checked (I think) but it is probably something obvious.

This is the link to the movie: https://gayeroticvideoindex.com/video/588
[com.plexapp.agents.GEVI.log](https://github.com/CodyBerenson/PGMA-Modernized/files/10407644/com.plexapp.agents.GEVI.log)

Can someone have a quick look and let me know where I am messing it all up! TIA

**Comment by JPH71** [comment]
Have you set up your oreferences for the agent?
Click on the gear at the top right... them on the left hand column click on
Agents

On the right hand go to gayadult films and select the gear on GEVI...

Set your preferences and then you must click save whether you change any or
not...

Quit plex completely... then restart plex...
Refresh the metadata on the particular film... and send me the gevi log
file... but that should be enough to get it working..

I would also place a space hyphen space after the 1

Jason x

**Comment by AussieGuy64** [comment]
Thanks for the quick reply, I still cannot get it to work :-(

- I opened the preferences for GEVI - I am unsure what I needed to change but I then Saved it. Quit PMS, renamed the file to 
(Falcon Studios) - Splash Shots 1 - Memories of Summer (1984) but still nothing.
I then also added another film just to see, but still no luck

I noticed in the log under PLEX TOKEN it said MISSING and I read another issue and so I found the Plex token and added it. 

But still no luck

I attach the logs, as well as what my Agents Screen looks like and the GEVI preferences.

TIA again

**Comment by AussieGuy64** [comment]
[com.plexapp.agents.GEVI.log](https://github.com/CodyBerenson/PGMA-Modernized/files/10407891/com.plexapp.agents.GEVI.log)
![screenshot-127 0 0 1_32400-2023 01 13-14_03_11](https://user-images.githubusercontent.com/122583569/212229630-44313a84-1c4f-4c37-83ed-b2cf199e857c.png)
![screenshot-127 0 0 1_32400-2023 01 13-14_15_25](https://user-images.githubusercontent.com/122583569/212229634-323417c4-a781-4323-837f-ea855d603ffc.jpg)

**Comment by JPH71** [comment]
Those settings look right...
Now clear the log and scrape just one film and send that log to me..

I have just gone to bed... its 04h00 here and I need to get up for work in
4 hours time xxx

**Comment by AussieGuy64** [comment]
Hi! I tried again today - still no luck :-( - I attach the log after I re-did it all

[com.plexapp.agents.GEVI.log](https://github.com/CodyBerenson/PGMA-Modernized/files/10416708/com.plexapp.agents.GEVI.log)

Thanks again!

**Comment by JPH71** [comment]
You have a none standard installtion of Plex.
I guess your plex player is installed in C:\Program Files\...... as normal...
As you are installing to F:\ and the Player is installing to its normal location....
The Agent therefore picks the F:\ drive path and thinks that Plex is also installed to this Drive
Go to %LOCALAPPDATA%\plex\plex media server and you will find the preferences.xml file there...
You can get the Token from there or click on View XML on any film and extract the Token from the last bit of the http::/ address...

I am going to change the code to extract the token for Windows users from the registry... This will make it independent of where it is installed...

Jason xxxx

**Comment by JPH71** [comment]
I have tested  (Falcon Studios) - Splash Shots 1 - Memories of Summer
(1984)
This scraped with no issues....
I just noticed that you are using the agent for libraries with both full
films and scenes. Gay Adult
Edit your library and make sure that it is also set to Gay Adult - rather
than Gay Adult Films

If your library only contains full films and no scenes, it is preferable to
use Gay Adult Films rather than Gay Adult...

[image: image.png]

My settings for GEVI are as follows:
[image: image.png]

Attached is the log file and here is the result:
[image: image.png]

Jason xxx

**Comment by AussieGuy64** [comment]
Hi!Thanks for the update. As per your last suggestion as well - with different drive for the Plex database, I had to anyway so I replaced my C drive yesterday and am trying again.Thanks for checking though, I will go through the setup again and make sure it is all set correctly.It will be great to get a scraper that scrapes all the films and also scenes etc where possible.Thanks againOn Sat, 21 Jan 2023 at 12:14, JPH71 ***@***.***> wrote:

I have tested  (Falcon Studios) - Splash Shots 1 - Memories of Summer

(1984)

This scraped with no issues....

I just noticed that you are using the agent for libraries with both full

films and scenes. Gay Adult

Edit your library and make sure that it is also set to Gay Adult - rather

than Gay Adult Films



If your library only contains full films and no scenes, it is preferable to

use Gay Adult Films rather than Gay Adult...



[image: image.png]



My settings for GEVI are as follows:

[image: image.png]



Attached is the log file and here is the result:

[image: image.png]



Jason xxx

**Comment by JPH71** [comment]
Hi AussieGuy64...

Your issue is that you installed plex in a non standard location and
therefore it can not find the preferences file.
The preferences file if you have installed PlexMedia Player is found under
%LOCALAPPDATA%\Plex\Plex Media Server.....

If you haven installed the player - you can get the token by
[image: image.png]

Clicking on the View XML - it will open a window in the browser... the
token will be found at the end of the address: take this token and put it
in your preferences for all your agents and click Save:
I am going to make a change so that the Token is retrieved from the
registry for Windows system users, irrespective of the install
directory......

Jason xxx

**Comment by JPH71** [comment]
Sorry for the delay in getting back to you - but my Plex servers failed and
it took me a number of days to sort my stuff out....

**Comment by AussieGuy64** [comment]
Hi!I have reinstalled the PMS now in the default location (after the drive replacement) - under LOCALAPPDATA - so it should now work. --Sorry for the delay in getting back to you - but my Plex servers failed--It is good to see that Plex can be temperamental with other people as well :-)On Sat, 21 Jan 2023 at 12:20, JPH71 ***@***.***> wrote:

Hi AussieGuy64...



Your issue is that you installed plex in a non standard location and

therefore it can not find the preferences file.

The preferences file if you have installed PlexMedia Player is found under

%LOCALAPPDATA%\Plex\Plex Media Server.....



If you haven installed the player - you can get the token by

[image: image.png]



Clicking on the View XML - it will open a window in the browser... the

token will be found at the end of the address: take this token and put it

in your preferences for all your agents and click Save:

I am going to make a change so that the Token is retrieved from the

registry for Windows system users, irrespective of the install

directory......



Jason xxx

**Comment by JPH71** [comment]
After the installation, don't forget to save your preferences as these
would have been reset.....
I have had many issues with my Plex setup as I usually use my server for
all the testing and such... too lazy to set up a separate test server....


Jason

**Comment by JPH71** [comment]
Please mark as closed!!!

**Comment by AussieGuy64** [comment]
Thank you for all your help I got it to scrape I had to change the agent to AEBN from GEVI. I also uploaded the lastest release of the plugin so am unsure if that also helped. Thanks again this plugin will become very useful

**Comment by JPH71** [comment]
You are very welcome.
When I am scrapping a few titles I have gevi as first followed by aebn,
third gayhotmovies then gayempire...

That grabs up to 95% of the available film titles...

The others I use for the rarer or newly released titles...

Using system collections, you can review them later and re scrape using the
big 4....

Jason xxx

**Comment by JPH71** [comment]
Please mark as closed!
