### ISSUE TITLE
[BUG]: Duplicate System Collections Created

### ISSUE THREAD

**Issue by jocklover** [CodyBerenson/PGMA-Modernized#218]
# Mandatory #

## Describe the bug: ## 
Getting duplicate Studio Collections, sometimes 20 or 30 of them. Does not occur with all Studios but seen a variety of Studios with duplicate collections. Sometimes duplicates collections will appear with "0 items", blank instead a # of items, or a random # of items that does not match the expected total. Opening the collections shows the # of items it states it contains. I have tried deleting all copies of the duplicate collections, running Optimize & Clean Bundles, and Refreshing Metadata. Logs below generated duplicate "|4| Bound in Public" collections across 4 titles. 

## Specific Agent(s) Causing the Issue: ##
Seems to be all Agents, included sample logs from GEVI & IAFD matches. 

## Log Attached: ##
[Dup Collection - GEVI.txt](https://github.com/CodyBerenson/PGMA-Modernized/files/10442902/Dup.Collection.-.GEVI.txt)
[Dup Collection - IAFD.txt](https://github.com/CodyBerenson/PGMA-Modernized/files/10442967/Dup.Collection.-.IAFD.txt)

# Optional #

## Screenshot(s) with all nudity redacted: ##
![image](https://user-images.githubusercontent.com/57208899/213102992-477b32ad-453a-426d-adf9-0975b50cc1d6.png)

## Additional Context: ##
First time back to matching in awhile, not sure if most current version could have spawned problem.

## Desktop (please complete the following information): ##
 - OS: QNAP QTS
 - Browser: Firefox 108.0.2 (64-bit)
 - Version: 1/12/23 - full replacement of all plugin files w/ restart of Plex

**Comment by JPH71** [comment]
First if all you haven't updated your preferences and saved them...
You are having collections like |4|... this are the sorting titles...
Update your preferences....

Duplicates sometimes occur... this is usually due to lock fields...
I am awaiting some code on how to unlock a titles particular metadata field
to prevent this...

So if you get 2 collections one with titles and 1 without, to correct this
do the following

For the one with titles and a hyphen within the collection title between 2
letters and save.

Then delete the one without film titles assigned to it...

Go back to the hyphenated one and remove the hyphen you put in
previously....

**Comment by jocklover** [comment]
I understand the functionality of the collections and love the "new" format w/ the |1| & |4| prefixes. 
The duplicates are studio only collections, not "Studio: Series" collections. In the logs provided it created two collections for the Studio "Bound In Public". When I refreshed all the metadata it originally created 30 "Bound In Public" collections (plus the additional, expected "Bound In Public: Series" collections). I also had 20 "Kristen Bjorn" and a few other studios that duplicated out.
Based on your response, it could be the locking issue, I can do some testing to see if one by one refreshes help.

**Comment by JPH71** [comment]
That also happened to me... just on the studio collections...
I have looked at the code and nowt stupid jumps out at me...

**Comment by JPH71** [comment]
Did you refresh your preferences??
The |1| etc should dissapear, they are used for sorting the collections in the background, so that you have them in the following order
System - including Agents
Genres
Countries
Studios + Series
Directors
Cast

**Comment by jocklover** [comment]
I'm not sure what you mean by the |1| disappearing - should the |1| not be in the label or should the collection not be created?

With the update from 11hrs ago I am still seeing duplicate "|4| _Studio_" collections

**Comment by JPH71** [comment]
The |!| is the sort title... it is used for ordering the collections...

This is how your collections should look....

[image: image.png]

This is from scraping one title....

As you can see all sorted in groups....

**Comment by JPH71** [comment]
And this is how the sort title is used
[image: image.png]
[image: image.png]
[image: image.png]

**Comment by jocklover** [comment]
Unfortunately your images didn't post.
Here is what I am seeing:
![image](https://user-images.githubusercontent.com/57208899/214994261-ae9b2809-cc2d-475d-ae0f-1c0d1cf61300.png)
I get "|4| _<studio>_" & "|4| _<studio>_: _<series>_", as well as "|1| IAFD", etc.
I don't mind the |4| & |1| prefixes as it helps sort everything out. However, the issue, as shown above, is that I get duplicates of some of the "|4| _<studio>_" collections, then nothing actually shows inside them either.

**Comment by JPH71** [comment]
I hate technology at times...
But if you are seeing a |1| type collections this means that you have not
set and saved your preferences... these should not be seen but should be in
effect to sort your collections...

The duplication of studio collections does occur, but I explained a manual
work around until I can find some code to unl9ck metadata fields... which 9
think causes this...

**Comment by jocklover** [comment]
Apologies, I see a few references to updating the preferences but I am not sure what I should set. Was this shown in one of the images that github isn't displaying?

The other suggestion I see is about a Collection w/ & w/out title - not what I am seeing.
If you are working on it, I don't mind waiting.

**Comment by JPH71** [comment]
Talking about preferences
Go to settings
Agents
Select gay adult
For each agent.. click the gear
The preferences for the agent will show up...
Set up your choices
Click save...
Them select which agents you want to use
Drag them to put them in order of preference
You are then ready to scrape
This information has been detailed by Cody in the setup literature...
