### ISSUE TITLE
IAFD not matching w/ "&" in Title

### ISSUE THREAD

**Issue by jocklover** [CodyBerenson/PGMA-Modernized#219]
Apologies for falling off, retried the titles referenced in #181 and still no match. 
I am using version from 1/12/23, removed and replaced all plugin files then restarted Plex.

Does the "&" need to be represented as "%26" (instead of as "and") to yield IAFD match?:
https://www.iafd.com/ramesearch.asp?searchtype=comprehensive&searchstring=Online+Hookup+Ends+With+Tickling+%26+Edging+In+Bondage+For+A+Hung+Ginger&FirstYear=2014&LastYear=2018&Submit=Filter

[IAFD Log - & Matching.txt](https://github.com/CodyBerenson/PGMA-Modernized/files/10443254/IAFD.Log.-.Matching.txt)

**Comment by JPH71** [comment]
Ampersand are coverted to %26 by the code...
I will be looking at iafd in the next couple of days to sort out a few
niggling issues and will check if leaving out ampersand in searches will
help.....

What did you name this file on disk... can you send it to me?

Jason

**Comment by JPH71** [comment]
Darned it ......
You can not drop the & within the search string....
The search string will work up to the & only....
We will leave it as is for the time being...

**Comment by jocklover** [comment]
I'm not sure I'm following...
The Log shows the search URL PGMA used included "and":
**BAD:** https://www.iafd.com/ramesearch.asp?searchtype=comprehensive&searchstring=Online+Hookup+Ends+With+Tickling+and+Edging+In+Bondage+For+A+Hung+Ginger&FirstYear=2014&LastYear=2018&Submit=Filter
If PGMA had instead converted the "&" into "%26" IAFD is happy with that and returns the result:
**GOOD:** https://www.iafd.com/ramesearch.asp?searchtype=comprehensive&searchstring=Online+Hookup+Ends+With+Tickling+%26+Edging+In+Bondage+For+A+Hung+Ginger&FirstYear=2014&LastYear=2018&Submit=Filter

Can you not have PGMA convert "%" into "%26" instead of "and"?

**Comment by JPH71** [comment]
& is equal to %26 in the search string.... just as a space is equivalent to
+

In the other agents I drop both and and & as film titles can still be found
with these strings missing in the search string...

But I will look more closely just in case I am misunderstanding you...

Just to clarify... your title has an & and not an 'and'...

**Comment by jocklover** [comment]
File name and IAFD title both contain an "&"

File named "(Men On Edge) - Online Hookup Ends With Tickling **&** Edging In Bondage For A Hung Ginger (2017)".

Log file extract (from log included above) showing Cloud Scraper request, swaps the "&" into "and":
![image](https://user-images.githubusercontent.com/57208899/213848888-d1539155-0e1d-4019-bcc3-931acbb96cb6.png)

**Comment by JPH71** [comment]
I will lo9k at this today as I have to work on iafd...

**Comment by JPH71** [comment]
Could you send me your email address?

mine is jp dot hudson at gmail dot com

I want to send you the utils.py to test this title....

**Comment by JPH71** [comment]
Please test and mark as closed....
