### ISSUE TITLE
[BUG]: Plex not recognizing PGMA

### ISSUE THREAD

**Issue by jocklover** [CodyBerenson/PGMA-Modernized#221]
# Mandatory #

## Describe the bug: ## installed latest code and Plex is not recognizing PGMA at all. Removed and replaced all files. Restarted Plex twice. Restarted QNAP. Restarted Plex. PGMA not showing on Agents page at all.

# Optional #

## Screenshot(s) with all nudity redacted: ##
![image](https://user-images.githubusercontent.com/57208899/214485086-f2f14086-ad07-46c4-a747-2cca17fd2b02.png)
![image](https://user-images.githubusercontent.com/57208899/214485175-827dae5f-63e2-49b9-a21b-509d9237a697.png)

## Desktop (please complete the following information): ##
 - OS: [e.g. iOS] QNAP QTS
 - Browser [e.g. chrome, safari] Firefox
 - Version [e.g. 22] 1/23/23 release (update to utils.py 210)

**Comment by jocklover** [comment]
Tested with roll back to Jan 12 version and Jan 12 version works.

**Comment by JPH71** [comment]
This should be solved with the zip I sent in last night.
This was due to importing the winreg module on Linux/MAC OS.

**Comment by jocklover** [comment]
Not seeing the "Internet Adult Film Database" agent under "Gay Adult".
Should we be using "Gay Adult Films" for all matching?

**Comment by JPH71** [comment]
That part of the code has not changed in ages
class IAFD(Agent.Movies):
    ''' define Agent class '''
    name = 'Internet Adult Film Database'
    languages = [Locale.Language.English]
    primary_provider = False
    preference = True
    media_types = ['Movie']
    contributes_to = ['com.plexapp.agents.GayAdult',
'com.plexapp.agents.GayAdultFilms', 'com.plexapp.agents.GayAdultScenes']
    accepts_from = ['com.plexapp.agents.localmedia']


However, use GayAdultFilms if the library you are scraping is a full film
library... and GayAdultScenes for video clips...

GayAdult should only be used for mixed content....

Jason

**Comment by jocklover** [comment]
Apologies, looks fine today - maybe I'm crazy. Thanks for your work.
