### ISSUE TITLE
[BUG]: Unable to use *Any* PGMA Agents on QNAP NAS (Scrapping Parameters Not Set Up! Error)

### ISSUE THREAD

**Issue by fourstix** [CodyBerenson/PGMA-Modernized#225]
# Mandatory #

## Describe the bug: ##   
All agents are failing with the message similar to this one from the GEVI agent: "ERROR (sandbox:19) - GEVI - SEARCH:: Error: <QUIT: Scraping Parameters Not Set Up!>"  on my Plex box.  

This is for the most recent code downloaded from Google Drive on Feb 9th.

## Specific Agent(s) Causing the Issue: ## 
GEVI, AEBN, GayHotMovies, GayEmpire, IAFD, etc.

## Index Site URL(s) Attempting to Match: ##
https://gayeroticvideoindex.com/video/31720
## Log Attached: ##
[com.plexapp.agents.GEVI.log](https://github.com/CodyBerenson/PGMA-Modernized/files/10710554/com.plexapp.agents.GEVI.log)
(All agent log files have a similar error as the GEVI logs)
# Optional #
I verified that all agents have the Plex Token set in the Plex Token field.

## Screenshot(s) with all nudity redacted: ##
![Agent Plex Token](https://user-images.githubusercontent.com/5274281/218179383-d0c4d46d-d04e-418c-a5bc-38d9cb46c19f.jpg)

## Additional Context: ##
All PGMA agent logs have the same error.

## Desktop (please complete the following information): ##
 - OS: QTS 5.0.1.227   on a QNAP  T-251+ NAS  (QTS is based on Linux Ubuntu)
 - Browser: Firefox
 - Version: 109.0.1

**Comment by JPH71** [comment]
If you look through the logs your error is here

*2023-02-10 14:16:53,364 (7f9cfe058808) :  INFO (sandbox:19) - GEVI  -
START :: Invalid Format Row            Row 403 -*

Look through GayTidy.txt and see what is wrong it should be *Old Genre::New
Genre*

I will amend the code so that it gives a clearer error in which file the
error has been found.....
And also put in the Operating system Name

Jason

**Comment by fourstix** [comment]
Hi Jason,
The file has only 402 lines.   
The last line is:

Gym / Locker Room::Jocks

Which looks okay to me.   How should the file end?  I only remapped A-G as a test.  Does one have to do them all?

Gaston

**Comment by fourstix** [comment]
For the OS information, the file was created under Windows 11 and then sent via FTP to the Plex server which is a QNAP NAS box running QTS 5.0.1.2277 (based on Ubuntu Linux).

**Comment by JPH71** [comment]
There should be no empty last line...

send the file to me to check - jp at gmail dot com

this is most likely in your UserGayTidy.txt file - as I have looked through
GayTidy.txt - in which I found one duplicate

Jason x

**Comment by fourstix** [comment]
I found the issue.  It's a Windows to Linux thing.  I created the UserGayTidy.txt file in Windows Notepad, the default editor for *.txt files in Windows.

Windows Notepad puts a ^Z at the end of a text file. On Linux, this is appears as an empty line as the last line in the file.  Editing the file in Linux, and removing the last line fixed the problem.

**Comment by JPH71** [comment]
Brilliant!

**Comment by fourstix** [comment]
I'm still struggling with this.  I copied the new GayTidy.txt file as UserGayTidy.txt and edited the file.  I made sure there's no EOF character at the end.  From the log file it looks like it reads the entire thing, but the GEVI Agent doesn't match and gives me an error in the log.

2023-02-11 13:11:07,452 (7fabdc9cbb38) :  INFO (sandbox:19) - GEVI  - ********************************************************************************************************************************************
2023-02-11 13:11:07,453 (7fabdc9cbb38) :  ERROR (sandbox:19) - GEVI - SEARCH:: Error: <QUIT: Scraping Parameters Not Set Up!>
2023-02-11 13:11:07,454 (7fabdc9cbb38) :  INFO (sandbox:19) - GEVI  - ********************************************************************************************************************************************
Here's the log file and the UserGayTidy.txt file that I'm using:

[com.plexapp.agents.GEVI.log](https://github.com/CodyBerenson/PGMA-Modernized/files/10714401/com.plexapp.agents.GEVI.log)

[UserGayTidy.txt](https://github.com/CodyBerenson/PGMA-Modernized/files/10714404/UserGayTidy.txt)

**Comment by fourstix** [comment]
I found 1 bad line at the top.  I deleted it, along with the next line for Mac's Bath's copied from the original UserGayTidy.txt.
But it still doesn't work for me.  

Here's the updated UserGayTidy.txt file.
[UserGayTidy.txt](https://github.com/CodyBerenson/PGMA-Modernized/files/10714464/UserGayTidy.txt)

Do I need to add lines to Genres.txt if I create new Genres like Cowboys, Uniforms, Socks, etc. ?  Should I remove the lines for Genres I don't use?

**Comment by JPH71** [comment]
You need to create new lines in the genres.txt for new genres that you have
added.
Then you will need to add icons for those new genres.
You don't have to remove any lines in genres.txt

Now you have mentioned it... I need to create a UsersGenres.txt file as
your file will be overwritten every time a new one is sent out...

Email me the file - I can look through it and test it...

Jason

**Comment by fourstix** [comment]
Thanks. It was painful, but I figured it out and fixed the missing lines.   It would be really nice if the errors in processing these files were simply ignored.  

I'll send you my UserGayTidy.txt Genres.txt with a zip file of the icons I created.  Feel free to re-use anything that you wish.

**Comment by JPH71** [comment]
When errors are ignored at this stage - it gets worse further down the line.
Then I will keep getting asked why something new that has been added is not
working....

Just about to test the UserGenres....

Jason

**Comment by fourstix** [comment]
That makes sense,   Thanks.  

I sent you a note with the files.  Should I close this issue?  With your help, it's working fine now, so I think it's done.

**Comment by JPH71** [comment]
Yes - please close the issue as we have sorted out the reason it was
failing...

I will let Cody know about this linux vs windows issues with the blank
lines....

Jason xxx

**Comment by fourstix** [comment]
Great, Thanks!
