### ISSUE TITLE
[BUG]: IAFD search fails on long titles

### ISSUE THREAD

**Issue by minielim** [CodyBerenson/PGMA-Modernized#227]
# Mandatory #

## Describe the bug: ## 
When the title is too long the IAFD search fails to return anything. Truncating the title search string to 73 characters allows the search to work properly.

## Specific Agent(s) Causing the Issue: ##
IAFD

## Index Site URL(s) Attempting to Match: ##
Attempting to search for: https://www.iafd.com/title.rme/title=eastender+danny+dyer+lookalike+double+fucked+by+skinny+n+thick+gigantic+dick+boy/year=2020/eastender-danny-dyer-lookalike-double-fucked-by-skinny-n-thick-gigantic-dick-boy.htm
The agent generated the search string: https://www.iafd.com/ramesearch.asp?searchtype=comprehensive&searchstring=Eastender+Danny+Dyer+Lookalike+Double+Fucked+by+Skinny+N+Thick+Gigantic+Dick+Boy&FirstYear=2017&LastYear=2021&Submit=Filter
Which failed to find any results.
Attempting this search manually reproduced the search failure and then manually adjusting the search to: https://www.iafd.com/ramesearch.asp?searchtype=comprehensive&searchstring=Eastender+Danny+Dyer+Lookalike+Double+Fucked+by+Skinny+N+Thick+Gigantic&FirstYear=2017&LastYear=2021&Submit=Filter
Allowed the title to be found.

Similarly:

Attempting to search for: https://www.iafd.com/title.rme/title=19yr+midlands+bendy+scally+boi+passed+fucked+every-way+left+creamed+up+and+frothy+with+spunk/year=2019/19yr-midlands-bendy-scally-boi-passed-fucked-every-way-left-creamed-up-and-frothy-with-spunk.htm
fails: https://www.iafd.com/ramesearch.asp?searchtype=comprehensive&searchstring=19yr+Midlands+bendy+scally+boi+passed+fucked+every-way+left+CREAMED+up+and+frothy+with+spunk&FirstYear=2016&LastYear=2020&Submit=Filter
92 character searchstring
fails: https://www.iafd.com/ramesearch.asp?searchtype=comprehensive&searchstring=19yr+Midlands+bendy+scally+boi+passed+fucked+every-way+left+CREAMED+up+and&FirstYear=2016&LastYear=2020&Submit=Filter
74 character searchstring
works: https://www.iafd.com/ramesearch.asp?searchtype=comprehensive&searchstring=19yr+Midlands+bendy+scally+boi+passed+fucked+every-way+left+CREAMED+up+an&FirstYear=2016&LastYear=2020&Submit=Filter
73 character searchstring

Which suggests that 73 characters is the maximum length of the searchstring.

Attempting to search for: https://www.iafd.com/title.rme/title=wow+watch+dustin+hazel+tear+18yo+troy+daniel%27s+ass+up+in+some+wild+positions/year=2019/wow-watch-dustin-hazel-tear-18yo-troy-daniel%27s-ass-up-in-some-wild-positions.htm
fails: https://www.iafd.com/ramesearch.asp?searchtype=comprehensive&searchstring=Wow+Watch+Dustin+Hazel+Tear+18yo+Troy+Daniel's+Ass+Up+in+Some+Wild+Positions&FirstYear=2017&LastYear=2021&Submit=Filter
works: https://www.iafd.com/ramesearch.asp?searchtype=comprehensive&searchstring=Wow+Watch+Dustin+Hazel+Tear+18yo+Troy+Daniel's+Ass+Up+in+Some+Wild+Positi&FirstYear=2017&LastYear=2021&Submit=Filter

# Optional #

## Desktop (please complete the following information): ##
commit 9b92b12

**Comment by JPH71** [comment]
Thanks for finding out this and providing the solution - I will implement
it and get it submitted to Cody to upload to the repository...

Cheers

Jason

**Comment by JPH71** [comment]
Tested new code - here are the results...
[com.plexapp.agents.IAFD.log](https://github.com/CodyBerenson/PGMA-Modernized/files/10834736/com.plexapp.agents.IAFD.log)

**Comment by JPH71** [comment]
Please mark as closed after you have tested....

Cheers
