### ISSUE TITLE
[BUG]: IAFD connection broken?

### ISSUE THREAD

**Issue by jfreiman** [CodyBerenson/PGMA-Modernized#230]
As of the last couple of days, (4/1/2023?) IAFD scenes have not been matching - even after verifying the Title, Year, and Dist.

here is one of over 50 scenes that have not matched 

(rawfuckclub.com) - Time to Feed My Ass Their Dick Latinrelax Lucasgaroto (2023).mp4
[https://www.iafd.com/title.rme/title=time+to+feed+my+ass+their+dick+latinrelax+lucasgaroto/year=2023/time-to-feed-my-ass-their-dick-latinrelax-lucasgaroto.htm]

I am using the Internet Adult Film Database Agent

Windows 11 Pro x64
PMS Version 1.32.0.6865
MS Edge Dev [Version 112.0.1722.31 (Official build) dev (64-bit)]

I am only seeing logs as recent as yesterday (2023-04-03) none for today's date - even though I've added about 50 scenes today using this agent.

[com.plexapp.agents.AdultFilmDatabase.log](https://github.com/CodyBerenson/PGMA-Modernized/files/11153825/com.plexapp.agents.AdultFilmDatabase.log)

**Comment by JPH71** [comment]
Darned it... I will look at this tomorrow... as its quite late now... bear
with me...

Jason

**Comment by jfreiman** [comment]
Have you discovered what's wrong?

**Comment by JPH71** [comment]
Sorry man... yesterday was a right Biatch of a day.... stupid useless
meetings at work.....
I will look at it today.... but if you have time ..... send another nag
email to remind.....

Cheers man

Jason

**Comment by jfreiman** [comment]
Friendly reminder.

**Comment by JPH71** [comment]
This one is matching:

[image: image.png]
[image: image.png]
The agents are quite forging when it comes to Studi Names - You could get
away with naming it as this
*(rawfuckclub) - Time to Feed My Ass Their Dick Latinrelax Lucasgaroto
(2023)*
OR
*(Raw Fuck Club) - Time to Feed My Ass Their Dick Latinrelax Lucasgaroto
(2023)*
The agents strip away .com, .net etc when it comes to matching and ignore
spaces....

[image: image.png]
[image: image.png]


I don't know what can be affecting your system...
Just try and do some cleanup... like empty your %TEMP%, delete all the log
files.... then CLean Bundles, Empty Trash and Optimise your database...
Reboot then try again....

Jason....

**Comment by jfreiman** [comment]
Thanks for checking it out.

I've cleaned out the TEMP folder(s) and deleted the Log Files.
I clean Plex Bundles and Optimize Database frequently - but I'll do it again to cover the bases.

I also re-copied PGMA files into the Plug-Ins folder just in case something, somehow got screwed up (even though it is appearing in the Agents Menu) - I've also individually opened each separate agent and saved them.

Rebooted the computer.....  Completed

Videos that have a clear match with IAFD are still not matching.


I have attached a new log file for the one video I have tried to match
(Raging Stallion) - Parking In The Rear (2023).mp4
[https://www.iafd.com/title.rme/title=parking+in+the+rear/year=2023/parking-in-the-rear.htm](url)

With regards to using the option .com. -- I use that for myself to designate if the video is a clip/scene and matched with the Scene Agent and without .com for Features which I match with the Gay Adult Films agent.  It also helps me sort/filter and identify a video in my management software.

[com.plexapp.agents.AdultFilmDatabase.log](https://github.com/CodyBerenson/PGMA-Modernized/files/11174990/com.plexapp.agents.AdultFilmDatabase.log)

**Comment by jfreiman** [comment]
I looked at the log file and thought the Token might be the issue.  

As it turns out, my Plex token has changed (or is different than the one used by the Agent) so I updated them all and I am still having the same issue..

**Comment by jfreiman** [comment]
> NEW PMS BUILD?
> The last 2 PMS builds for Windows and Mac state they have new minimum OS requirements -- Which my Windows 11 system meets. Is it possible something changed with regards to Agents? Are you running a current (Beta) Windows build of PMS?
> 
> (Windows) The minimum supported Windows client operating system is now Windows 10 Version 1607
> (Windows) The minimum supported Windows server operating system is now Windows Server 2016
> (macOS) The minimum supported version is now macOS 10.13
> 
I uninstalled PMS 1.32.0.6865
I installed the older (non Beta) PMS 1.31.3.6868 

When I restated PMS the PGMA was able to match the example given above as well as others!!! :)
I'll see how it does when I match around 80? vids from the past several days.

**Comment by JPH71** [comment]
I will check the version of the plex server agent and let you know...

**Comment by JPH71** [comment]
This is the version I am using
[image: image.png]

Jason

**Comment by jfreiman** [comment]
```
This is the version I am using
[image: image.png]

```
FYI, I haven't been able to see any of you image.png attachments -- so I can't see what version PMS you are using.

**Comment by JPH71** [comment]
let me post it from within github
![image](https://user-images.githubusercontent.com/43102249/230698610-0cea14bb-be91-4674-81df-db41bfbe4637.png)

**Comment by JPH71** [comment]
Close issue - then we can re-open if this happens again....
See my notes in the discussion section.....
