### ISSUE TITLE
It won't work.

### ISSUE THREAD

**Issue by maaya1989** [CodyBerenson/PGMA-Modernized#231]
Sorry for the vague title. I'm not new to plex and I've installed 3 party plugins for subtitles and scrapping before and I did exactly (or I think...) as your well written guide but it just won't work.
I've tried it on my mac server (ventura with plex 4.100.1) and my nas server (qnap) and _it just seems like the plugin isn't...starting_. I think I did something wrong I just can't figure it out myself.（BTW my normal movie & tv collections are working fine.）
I saw that people were having similar issue and did put in the token
<img width="569" alt="截屏2023-04-07 19 04 00" src="https://user-images.githubusercontent.com/13052129/230599253-637c339e-78ea-4543-b072-a710cc301733.png">
Here's the log, I've tried both scenes and movies and none of them is working.
[com.plexapp.agents.WayBig.log](https://github.com/CodyBerenson/PGMA-Modernized/files/11178474/com.plexapp.agents.WayBig.log)
[com.plexapp.agents.GEVI.log](https://github.com/CodyBerenson/PGMA-Modernized/files/11178613/com.plexapp.agents.GEVI.log)

Movie / scene I've tried are:
https://gayeroticvideoindex.com/video/27528
and
https://www.waybig.com/video/blake-jackson-fucks-sean-costin-gayhoopla-302388.html

Thank you for your amazing work.

**Comment by JPH71** [comment]
@maaya1989

As you can see in the logs here:
2023-04-07 18:36:20,979 (1dc0d1b40) :  INFO (sandbox:19) - GEVI  - START ::
3. PGMA Usage Folder Locations
2023-04-07 18:36:20,980 (1dc0d1b40) :  INFO (sandbox:19) - GEVI  - START ::
PGMA Folder Location         ** FAIL **
2023-04-07 18:36:20,980 (1dc0d1b40) :  INFO (sandbox:19) - GEVI  - START ::
             System         ** FAIL **
2023-04-07 18:36:20,980 (1dc0d1b40) :  INFO (sandbox:19) - GEVI  - START ::
             Genres         ** FAIL **
2023-04-07 18:36:20,980 (1dc0d1b40) :  INFO (sandbox:19) - GEVI  - START ::
        Country Art         ** FAIL **
2023-04-07 18:36:20,980 (1dc0d1b40) :  INFO (sandbox:19) - GEVI  - START ::
Country Poster Flags         ** FAIL **
2023-04-07 18:36:20,980 (1dc0d1b40) :  INFO (sandbox:19) - GEVI  - START ::
Country Poster Maps         ** FAIL **
2023-04-07 18:36:20,980 (1dc0d1b40) :  INFO (sandbox:19) - GEVI  - START ::
         Cast Faces         ** FAIL **
2023-04-07 18:36:20,980 (1dc0d1b40) :  INFO (sandbox:19) - GEVI  - START ::
       Cast Posters         ** FAIL **
2023-04-07 18:36:20,980 (1dc0d1b40) :  INFO (sandbox:19) - GEVI  - START ::
     Director Faces         ** FAIL **
2023-04-07 18:36:20,980 (1dc0d1b40) :  INFO (sandbox:19) - GEVI  - START ::
   Director Posters         ** FAIL **

You need the PSMA folder in the same location as the Plex agents - in
windows they are here
C:\Users\jphud\AppData\Local\Plex Media Server\Plug-ins

there should be a folder called: _PGMA too...
C:\Users\jphud\AppData\Local\Plex Media Server\Plug-ins\_PGMA

This folder has the flags, genre art etc that all the agents use...

Kind Regards

Jason

**Comment by maaya1989** [comment]
OMG I knew it was something simple that I did wrong. That fixed it, thanks Jason!
For someone as stupid as me, on NAS you may have to manually set the folder permission to read and *write* , or it will fail too.
I'm closing the issue now;)

**Comment by JPH71** [comment]
Anytime you have an issue - reach out... We will be there to help!
I work on a Windows system... but there are members in the Group who are on
Linux, MACOS and various NAS systems...
If you think of any enhancements or find a good website that is not been
scraped let me know!


Jason xxxx
