### ISSUE TITLE
Matching failing - multiple agents

### ISSUE THREAD

**Issue by ScoBoXxX** [CodyBerenson/PGMA-Modernized#233]
Hi to the PGMA-Mod Masters!  Sadly, I need to report that matching is failing on several agents.  Attached are logs for a GEVI (film) failure and a Fagalicious (scene) failure.  I have others if necessary.  Can't say when this started but I know I've seen matching failures for at least a week now and I'm just getting around to troubleshooting.  I've got the most recent PGMA code.  

GEVI:
(Staxus) - The Torch (2022)
should match to: https://gayeroticvideoindex.com/video/69020

Fagalicious:
(Next Door Studios) - Brandon Anderson, Andrew Miller and Jayden Marcos in “Just 2 Curious” (‘Next Door Films’ Series) (2023)
should match to: https://fagalicious.com/next-door-studios-brandon-anderson-andrew-miller-jayden-marcos-just-2-curious-next-door-films-series/

and a 3rd for good measure
(Disruptive Films) - Jack Bailey and Cliff Jensen - A Cowboy and A Gentleman (2023)
should match to: https://www.queerclick.com/qc/2023/04/disruptive-films-jack-bailey-and-cliff-jensen-a-cowboy-and-a-gentleman.php

Thanks,
ScoBoXxX

[com.plexapp.agents.QueerClick.log](https://github.com/CodyBerenson/PGMA-Modernized/files/11243134/com.plexapp.agents.QueerClick.log)
[com.plexapp.agents.Fagalicious.log](https://github.com/CodyBerenson/PGMA-Modernized/files/11243135/com.plexapp.agents.Fagalicious.log)
[com.plexapp.agents.GEVI.log](https://github.com/CodyBerenson/PGMA-Modernized/files/11243136/com.plexapp.agents.GEVI.log)

**Comment by CodyBerenson** [comment]
Please review #232 

This may likely be the issue, and the resolution is described there as well

**Comment by ScoBoXxX** [comment]
Yup that did it - sorry I didn't search before opening my mouth ;)  We can close this.  Thanks!

**Comment by JPH71** [comment]
Aye... it caught me out too...
