### ISSUE TITLE
[BUG]: Fagalicious not scraping one title

### ISSUE THREAD

**Issue by vampirelayer** [CodyBerenson/PGMA-Modernized#234]
# Mandatory #

## Describe the bug: ## 
I'm not able to scrape this particular title
`NakedSword Originals - Diego Sans fucks Cole Connor bareback in "The Swords – Content House, Scene 1" (2023)`

 - I have replaced the quotes with ""
 - Have managed to scrape other Fagalicious titles successfully

## Specific Agent(s) Causing the Issue: ##
Fagalicious

## Index Site URL(s) Attempting to Match: ##
https://fagalicious.com/nakedsword-originals-diego-sans-cole-connor-the-swords-content-house-scene-1/
## Log Attached: ##
[](url)
[com.plexapp.agents.Fagalicious.log](https://github.com/CodyBerenson/PGMA-Modernized/files/11322851/com.plexapp.agents.Fagalicious.log)

# Optional #

## Desktop (please complete the following information): ##
 - OS: macOS Ventura 13.3.1
 - Browser : N.A, I'm using Plex app to scrape
 - Version: Version 1.67.2.3705-db506a00

**Comment by JPH71** [comment]
I am looking at waybig... possibly will be the same issue...
I will look at the new code I introduced to standardise all, single and
double quotes and get back to you on this one xxx

**Comment by CodyBerenson** [comment]
@JPH71 @vampirelayer 
Confirmed, the updated agents resolves this issue.  I left the quote marks as is.

(NakedSword Originals) - Diego Sans fucks Cole Connor bareback in “The Swords – Content House, Scene 1” (2023).mp4

![image](https://user-images.githubusercontent.com/40373801/235354146-f1350ac5-6927-464e-a98d-849060dbd793.png)

**Comment by JPH71** [comment]
Sweet...
Sorry for that fuck up...
I sorted it on the files but forgot to carry it through to the websites
entry...

Jason xxx

**Comment by vampirelayer** [comment]
Hm it still doesn't work.
I'm using the latest plugins published on 29 April.
Looking at the logs it seems that the agent is matching the title (with the correct apostrophes) against multiple pages of search entries, and none of the entries matches the title.
Could it be an issue with Fagalicious search algorithm?[](url)
[com.plexapp.agents.Fagalicious.log](https://github.com/CodyBerenson/PGMA-Modernized/files/11363179/com.plexapp.agents.Fagalicious.log)

**Comment by JPH71** [comment]
I will look at the title against fagalicious later today....

And get back to you

Jason xx

**Comment by CodyBerenson** [comment]
> Hm it still doesn't work. I'm using the latest plugins published on 29 April. Looking at the logs it seems that the agent is matching the title (with the correct apostrophes) against multiple pages of search entries, and none of the entries matches the title. Could it be an issue with Fagalicious search algorithm? [com.plexapp.agents.Fagalicious.log](https://github.com/CodyBerenson/PGMA-Modernized/files/11363179/com.plexapp.agents.Fagalicious.log)
> 
> ** ignore the above, I found a matching search result but with different apostrophes used that are causing the mismatch **
> 
> ![image](https://user-images.githubusercontent.com/81353722/235395006-137bbd4b-09e3-4700-855d-da8a29bdac08.png)

above you said that you changed the quotation marks. I did not, left them exactly as they are on the site, and it matched perfectly.

**Comment by JPH71** [comment]
You misunderstood me...
You copy the title of fagalicious, waybig, or queerclick...

Put the brackets round the studio followed by a dash and add the year at
the end...

The scrapper will then for matching purposes convert all apostrophes
whether curved or not not into standard ones...

The scraper also converts the search result entries in the same way...

Then it compares the two to find a match...

Could you let me know the scene in which you changed the apostrophes ...
that refused to match... I might not have considered something that needs
looking into....

Jason xxx

**Comment by jiaher** [comment]
It is this title: https://fagalicious.com/nakedsword-originals-diego-sans-cole-connor-the-swords-content-house-scene-1/

in the logs, it now looks like this. I didn't change the apostrophes...
![image](https://user-images.githubusercontent.com/691698/235819888-ca65809d-8e55-4fed-a7e2-f3e5ad1fba8c.png)

**Comment by vampirelayer** [comment]
It is this title: https://fagalicious.com/nakedsword-originals-diego-sans-cole-connor-the-swords-content-house-scene-1/

Looking at the logs it looks like this. I didn't change the apostrophes.
![image](https://user-images.githubusercontent.com/81353722/235820166-a5cc2cfc-8511-40b7-8de5-198624be6d97.png)

**Comment by JPH71** [comment]
I have just tested this, and it matches:
![image](https://user-images.githubusercontent.com/43102249/235984869-8e254768-9c9f-45a3-a863-a36e9e05a192.png)

There is an issue with the Genres been selected as Cast, so I am just going to work on that now.

From my log - I confirm I am using:**Fagalicious v.2020.01.18.36**

Are you using windows or Linux??

If you are on the same version I am, but not using Windows - the only thing that I could think that could cause this would be how the hyphen is processed....

As I am working on the genre vs cast, adding the new thumbor - I will standardise hyphens along with the apostrophes....

Jason

**Comment by JPH71** [comment]
And this is how I named it
![image](https://user-images.githubusercontent.com/43102249/235987479-1064431f-a91c-4dff-aacb-3775d7604a73.png)

**Comment by ScoBoXxX** [comment]
Hi all.   Not sure if it is related, but I also have a single title that won't match on Fagalicious.  Link below and log attached showing failure but not sure why. 

File name: (Twink Pop) - Jake Preston creampies Jordan Lake in “Twink Trip, Part 3” (2023).mp4
URL: https://fagalicious.com/twink-pop-jake-preston-fucks-jordan-lake-in-twink-trip-part-3/

[com.plexapp.agents.Fagalicious.log](https://github.com/CodyBerenson/PGMA-Modernized/files/11385232/com.plexapp.agents.Fagalicious.log)

**Comment by JPH71** [comment]
This is a strange one - a manual search for Jake Preston does not bring the page up.
In addition when in Chrome/Edge - when you click on the tab of the page - you can see that it is a different name to the the Title of the scene...
The only thing would be to check for it on QueerClick, WayBig, or BestExclusivePorn....

Sorry man....
Latest Code is with  Cody to fix outstanding issues with matching and the new Thumbor Address....

Jason xxxxx

**Comment by JPH71** [comment]
Please close issue - as this has to do with the website and not the code....
