### ISSUE TITLE
PLEASE READ DISCUSSION TOPIC #232.  DO NOT UPGRADE PMS

### ISSUE THREAD

**Issue by CodyBerenson** [CodyBerenson/PGMA-Modernized#237]
PMS Versions after 1.31.0.6654 break PGMA Agents.  Please see discussion topic #232

**Comment by JPH71** [comment]
Just Checked

Latest Windows version that works is  1.31.2.6868

**Comment by fourstix** [comment]
Hi,
I've been trying to follow this issue on the Plex forums.  It seems to have broken most 3rd party plug-ins. There's a forum post here for the issue: https://forums.plex.tv/t/1-32-x-breaks-plugins-on-windows-openssl/838323

 At any rate there is now a beta version of Plex Media Server posted recently with a possible fix: 

https://forums.plex.tv/t/plex-media-server/30447/576

I'm not in the Beta program and I'm not on Windows, so I can't download and test the fix.  But I thought I'd pass this information along in case someone is able to give it try.

**Comment by jfreiman** [comment]
> At any rate there is now a beta version of Plex Media Server posted recently with a possible fix:
> 
> https://forums.plex.tv/t/plex-media-server/30447/576
> 
> I'm not in the Beta program and I'm not on Windows, so I can't download and test the fix. But I thought I'd pass this information along in case someone is able to give it try.

The above listed version 1.32.1.6999 did not fix the issue - but there were improvements.

I saved all my log files from 6999 into a zip and posted them on the forum last night -- but here they are again.
[PMS Plugin Logs.zip](https://github.com/CodyBerenson/PGMA-Modernized/files/11360383/PMS.Plugin.Logs.zip)

IAFD does not work, from my experience and Agent settings, I could only get HFGPM to match and when that did succeeded, it wasn't able to match Cast images from IAFD and only placed the "no image available" jpg.

**Comment by JPH71** [comment]
I am on the beta... I will download and check...

**Comment by fourstix** [comment]
For what it's worth, Plex Media Server 1.32.1.6999 seems to be working okay with the PGMA agents on QNAP.  I am using the GEVI, IAFD, GayHotMovies, GayEmpire and AEBN agents and I don't see any errors.

**Comment by JPH71** [comment]
@fourstix - you are a star!

**Comment by JPH71** [comment]
I will update mine tomorrow - and try it out!

**Comment by JPH71** [comment]
Latest version, downloaded 10 minutes ago now scrapes.
This issue can now be closed:
![image](https://github.com/CodyBerenson/PGMA-Modernized/assets/43102249/17632c9f-4707-443c-b0a8-68f3228dbf23)

**Comment by kellys297** [comment]
> Latest version, downloaded 10 minutes ago now scrapes.
> This issue can now be closed:
> ![image](https://user-images.githubusercontent.com/43102249/240441749-17632c9f-4707-443c-b0a8-68f3228dbf23.png)

Upgrading Plex 1.31.2.6868 to 1.32.2.7100 seems to have broken it for me. I'm back to getting "ERROR (logkit:22) SEARCH:: Error: <QUIT: Scraping Parameters Not Set Up!>" messages again. 

I'm certain that I'm missing something. Is there a trick to getting it to work or would it be best if I open a new issue?

**Comment by kellys297** [comment]
> Make sure you have saved the preferences for the scrapers you use... I jiggle whilst saving... change one default then save, then change back and select your real choices, then save again. Restart PMS refresh metadata for one film... Then send me the logs... Jason xxx
> […](#)

The jiggling seems to have done it! I'd have never thought to do something so simple. So far, everything I've thrown at it seems to be tagging correctly with the latest PGMA and Plex updates. Thank you!

**Comment by jfreiman** [comment]
I've jiggled, I've shaken, I've changed my default Agent(s), I've restarted PMS
I've uninstalled PMS, rebooted Windows, and Installed PMS (1.31.3.6868 x64) -- and had to manually change the newly generated token
I've cleared out the Plug-Ins folder, re-copied. I've copied over the existing files in Plug-Ins\ - and restarted PMS
I've jiggled and shaken again, etc.
I've searched the logs for the "answer" of how to repair/fix PGMA/PMS and I'm either missing something or don't understand something.
Could someone please examine the
 attached logs and steer me towards a solution or tell me what I've been doing wrong so I can match my video collections (neither Features or Scenes are matching).

[Logs - At Wits End.zip](https://github.com/CodyBerenson/PGMA-Modernized/files/11580204/Logs.-.At.Wits.End.zip)

**Comment by CodyBerenson** [comment]
@jfreiman I believe the answer is right in your log.  You do not have a checkmark for Genre.  You actually have to make a selection.  Then stop your PMS, restart it.  Please try it just for one GEVI title.  The log is telling you:  SEARCH:: Error: <QUIT: Scraping Parameters Not Set Up!>

![image](https://github.com/CodyBerenson/PGMA-Modernized/assets/40373801/77a86f76-6c74-4014-8024-e2aa81aeace6)

**Comment by JPH71** [comment]
I changed it from iIndigo to Red, then saved it and quit PMS
Then went back into it and changed it to what I wanted...
Quit PMs then restarted it and it worked....
Plex is a right pain in the arse... And I hate having to do the Plex
Dance....

**Comment by JPH71** [comment]
I will have to think of a way to force the Set As to be the default.....

**Comment by JPH71** [comment]
If not set....

**Comment by JPH71** [comment]
Just a really stupid question here... after you change from indigo to
No.... are you scrolling to the end of the preferences and clicking SAVE???
I made this mistake once during one omy very special sessions!!!!

**Comment by jfreiman** [comment]
I did not make any changes to the Genre Colors and left it as is -- Indigo must have been the default because all of the Agents were set to that Genre Color.
I changed them all to "No" 

Yes, I am pressing "Save" at the bottom of every Agent preferences.

I can't restart PMS at the moment because too many users are currently streaming.

Hopefully a restart of PMS will "allow" PGMA to properly connect and add movie metadata results again.

**Comment by JPH71** [comment]
A restart is necessary unfortunately.... and sorry for asking the real
stupid question....

**Comment by jfreiman** [comment]
_The only 'stupid question' is the question unasked_ - trust me, I was a Technical Support Rep in the late '80s - there are NO stupid questions. :)

**Comment by vampirelayer** [comment]
“What do you mean I have to plug in the keyboard for it to work?”True story.Sent from my iPhoneOn 29 May 2023, at 10:45 AM, John Freiman ***@***.***> wrote:﻿
The only 'stupid question' is the question unasked - trust me, I was a Technical Support Rep in the late '80s - there are NO stupid questions. :)
