### ISSUE TITLE
FG and WB Won't match this file

### ISSUE THREAD

**Issue by j-ktz** [CodyBerenson/PGMA-Modernized#24]
Trying to match the latest Pop-Up video from Sean Cody but neither Waybig or Fagalicious will match. Other files will match fine.

FG: Sean Cody: Tanner, Bryce, Coleman, David, Andy and Noel’s hot bareback orgy in “Mountain Getaway – Day 4” (‘Pop‑Up’ Edition)

https://fagalicious.com/sean-cody-mountain-getaway-day-4-pop%e2%80%91up-edition-tanner-bryce-coleman-david-andy-noel-bareback-orgy/

I named the file "(Sean Cody) - Tanner, Bryce, Coleman, David, Andy and Noel’s hot bareback orgy in “Mountain Getaway – Day 4” (‘Pop‑Up’ Edition) (2020).mp4"

**Comment by j-ktz** [comment]
Fixed! It was the —, had to change to a hyphen. Ignore me! 😆

**Comment by JPH71** [comment]
I was just going to look at it - as i had just finished watching the last
15 minutes of Eurovision...
