### ISSUE TITLE
Please update the Agents to use either Studio or Distributor 

### ISSUE THREAD

**Issue by CodyBerenson** [CodyBerenson/PGMA-Modernized#25]
@JPH71
Some indexing sites such as Gay Erotic Video Index (GEVI) and Internet Adult Film Database (IAFD) include both Studio and Distributor (often different) metadata.  It is easy for someone to use one rather than the other, which hampers matching.  Without changing the file naming convention, i.e. (Studio) - Title (YYYY).ext please update the logic so that the Agent will search and match the file regardless if a user utilized Studio or Distributor in the (Studio) portion of the file name.

**Comment by JPH71** [comment]
@CodyBerenson 

Here it is! 
[GEVI.bundle.zip](https://github.com/CodyBerenson/PGMA-Modernized/files/4706651/GEVI.bundle.zip)

@ Everyone else - let Cody test and upload this to the repository....

**Comment by CodyBerenson** [comment]
This enhancement was tested and pushed to the master repository.
