### ISSUE TITLE
[BUG]:  Lucas Entertainment - Fagalicious (unmatched)

### ISSUE THREAD

**Issue by dimitrimahiro** [CodyBerenson/PGMA-Modernized#250]
## Describe the bug: ## 
This video file can't be matched tru Fagalicious =/

## Specific Agent(s) Causing the Issue: ##
Fagalicious

## Index Site URL(s) Attempting to Match: ##
https://fagalicious.com/lucas-entertainment-max-arions-bareback-double-penetration-orgy-with-benjamin-gomez-braxton-boyd-dakota-payne-jeffrey-lloyd-and-jesse-santana-in-seeded-man-whores/

## Log Attached: ##
[com.plexapp.agents.Fagalicious.log](https://github.com/CodyBerenson/PGMA-Modernized/files/11712545/com.plexapp.agents.Fagalicious.log)

## Screenshot(s) with all nudity redacted: ##
![Screenshot 2023-06-10 095121](https://github.com/CodyBerenson/PGMA-Modernized/assets/20586368/197a2cea-8373-40d3-a9bc-71560ac9a0bb)
![Screenshot 2023-06-10 095205](https://github.com/CodyBerenson/PGMA-Modernized/assets/20586368/52e6bae2-bcc4-4b7a-8834-35d0a2c83f12)
![Screenshot 2023-06-10 095243](https://github.com/CodyBerenson/PGMA-Modernized/assets/20586368/bb772003-a384-493e-9830-3adf1e032d32)

## Additional Context: ##
Finaly on the right Issues section ;)

## Desktop (please complete the following information): ##
 - OS: Win 11
 - Browser: Plex for Windows
 - Version: 1.69.1.3755-e00242c8
 - Server: Version 1.32.2.7100

**Comment by dimitrimahiro** [comment]
Is the updated code fixing it? 

goodnight!

**Comment by JPH71** [comment]
Yes, this one is fixed by the code...

**Comment by JPH71** [comment]
please close this issue... after testing
