### ISSUE TITLE
Thumbor was offline

### ISSUE THREAD

**Issue by CodyBerenson** [CodyBerenson/PGMA-Modernized#251]
Hi folks, I got notified that the Cloud service was down.  It is back up now, but since it isn't a static IP address, it requires an update:

http://34.150.135.138:8888

@JPH71 Can you tweak?

**Comment by JPH71** [comment]
Fixed!

**Comment by ms52538** [comment]
While I have you, might I ask what version of Plex we should be running? Are we still holding at the version from earlier this year or is it ok to upgrade to the latest and greatest?  Thanks!

**Comment by JPH71** [comment]
YES YOU CAN!!!

The error I found earlier which prevented scraping has now been resolved!

Cheers

Jason

**Comment by j-ktz** [comment]
Did I just hear that we can update Plex to the latest release w no issues?

**Comment by JPH71** [comment]
yeppity yep!!!!

**Comment by ms52538** [comment]
I implemented the latest release download, with the latest Thumbor address
change, and then upgraded plex. I then tested a couple of matches, and can
report that everything worked well. In addition, all of the blacked-out
actor images returned back to normal and now show the actors faces
accordingly. Please close my issue. :)  Thank you for the Happy Meal!

**Comment by JPH71** [comment]
Happy Meal.... Good one!

**Comment by JPH71** [comment]
Please close this issue....
