### ISSUE TITLE
Thumbor section within Scene Agents is not showing

### ISSUE THREAD

**Issue by ms52538** [CodyBerenson/PGMA-Modernized#252]
Thumbor option is no longer appearing for me, in an attempt to update to the new IP address.

I had recently changed the location of my libraries on Windows 11 back to default settings, and went through and updated the Plex-Token captured from the "Get Info - XML url link generated" in all agents. 

Additionally, the actor images are no longer appearing, just seeing blacked out spots.

Windows 11 
Plex Server: Version 1.31.3.6868

![2023-06-13 (4)](https://github.com/CodyBerenson/PGMA-Modernized/assets/20614244/6a41e7cb-9b44-4707-8e27-eea850563d3a)

[com.plexapp.system.log](https://github.com/CodyBerenson/PGMA-Modernized/files/11738070/com.plexapp.system.log)
[com.plexapp.agents.IAFD.log](https://github.com/CodyBerenson/PGMA-Modernized/files/11738072/com.plexapp.agents.IAFD.log)
[com.plexapp.agents.BestExclusivePorn.log](https://github.com/CodyBerenson/PGMA-Modernized/files/11738077/com.plexapp.agents.BestExclusivePorn.log)
[com.plexapp.agents.QueerClick.log](https://github.com/CodyBerenson/PGMA-Modernized/files/11738079/com.plexapp.agents.QueerClick.log)
[com.plexapp.agents.Fagalicious.log](https://github.com/CodyBerenson/PGMA-Modernized/files/11738081/com.plexapp.agents.Fagalicious.log)
[com.plexapp.agents.GayAdultScenes.log](https://github.com/CodyBerenson/PGMA-Modernized/files/11738082/com.plexapp.agents.GayAdultScenes.log)
[com.plexapp.agents.localmedia.log](https://github.com/CodyBerenson/PGMA-Modernized/files/11738084/com.plexapp.agents.localmedia.log)
[com.plexapp.agents.none.log](https://github.com/CodyBerenson/PGMA-Modernized/files/11738085/com.plexapp.agents.none.log)
[com.plexapp.agents.WayBig.log](https://github.com/CodyBerenson/PGMA-Modernized/files/11738087/com.plexapp.agents.WayBig.log)
[com.plexapp.agents.imdb.log](https://github.com/CodyBerenson/PGMA-Modernized/files/11738088/com.plexapp.agents.imdb.log)
[com.plexapp.plugins.plextools.log](https://github.com/CodyBerenson/PGMA-Modernized/files/11738090/com.plexapp.plugins.plextools.log)

**Comment by JPH71** [comment]
Thumbor is no longer a preference.
It is updated in the _PGMA folder - a file called thumbor.txt
I am currently working on issues raised by 403 IAFD errors - the blanked
out pictures will be sorted soon...

This will be the new defaults:
if an Actor is on IAFD but has no picture - he will have the No Picture
Icon as on IAFD, with a green tick
if he is on IAFD with a picture - it will show with a green tick
if not on IAFD - Actors Initials - Red Cross
if IAFD 403 Error - Actor's Initials - Question Mark

Bare with me.... Hopefully should get this finished in the next few days....

Cheers

Jason xx




Cheers

Jason

**Comment by ms52538** [comment]
Thanks Jason! I'll wait for you to complete your efforts on this pesky issue. Much appreciated.

**Comment by JPH71** [comment]
You are welcome....

**Comment by JPH71** [comment]
Please close this issue when you get time!!!
