### ISSUE TITLE
Coming Soon!  New GEVI Scenes Agent

### ISSUE THREAD

**Issue by CodyBerenson** [CodyBerenson/PGMA-Modernized#253]
@ms52538 @carylee 

As requested in #155 

Great news!  Jason @JPH71 has created a GEVI Scenes matching agent.  I'm testing it now, so stay tuned.  The unique scene # is part of the file name.  The GEVI Scenes agent will scrape the GEVI Scene, return the GEVI Scene Image and rotate it 90 degrees so that it is portrait vs. landscape/cropped. 

![image](https://github.com/CodyBerenson/PGMA-Modernized/assets/40373801/54ffb2cc-d6eb-40c1-a5d7-4b76fd5b8f84)

_Originally posted by @CodyBerenson in https://github.com/CodyBerenson/PGMA-Modernized/discussions/155#discussioncomment-6169581_

**Comment by j-ktz** [comment]
This is awesome! I've been hoping for this. Thanks boys!!!

**Comment by dimitrimahiro** [comment]
Congrats guys!!!! =D

**Comment by JPH71** [comment]
Updated as Cody found an error! some scenes had 5 numbers instead of 6...
3 Options for rotating the image
L - rotate left
R - rotate right
N - no rotation
Regex updated....

**Comment by CodyBerenson** [comment]
Please see updated Usage Guide on how to name the files and minimal system requirements.  

Everyone:  get indexing on your scenes that aren't blogged anywhere, such as RFC, TIM, etc!

**Comment by JPH71** [comment]
We can close this one too.....
