### ISSUE TITLE
Fagalicious: Error 403 - Forbidden

### ISSUE THREAD

**Issue by ScoBoXxX** [CodyBerenson/PGMA-Modernized#254]
Hey guys.  Creating this to move it off a related issue.

I keep receiving the HTTP Error 403: Forbidden when trying to match Fagalicious titles.  None are matching anymore and every attempt fails.  This has been going on for a couple weeks now.  Apparently I have been labeled a scraper agent or something?

2023-06-16 08:17:32,414 (8a8) :  ERROR (logkit:22) - Fagalicious - SEARCH:: Error: Search Query did not pull any results: HTTP Error 403: Forbidden

Is there any way to fix this?  I have tried restarting and waiting; I've powered down for a couple days and left it alone.  I've updated the .py code as suggested in another post.  I just downloaded the most recent PGMA today and still the issue persists.  I am Forbidden lol.  I swear I can't be the most active machine trying to scrape </shrug>.  

Most recent log is attached for reference.  Waybig, Queerclick, GEVI - all match fine.  It's just Fagalicious.

Anyway - just wanted to create an issue specific to this so I don't get lost in a related issue :)  Thanks for all you do!

sb

[com.plexapp.agents.Fagalicious.log](https://github.com/CodyBerenson/PGMA-Modernized/files/11771832/com.plexapp.agents.Fagalicious.log)

**Comment by JPH71** [comment]
You are the second guy with this issue..
I am scraping just fine with fagalicios ..

Try also clearing out your Internet cache...
Rebooting your modem as sometimes you end up with a new ip address... look
into how to change this...

A vpn may also help...

Also if you are on windows delete everything in the %TEMP% folder

This is not guaranteed to work....

**Comment by ScoBoXxX** [comment]
Well I guess I am sorta glad it's not just me - ha!

I've cleared cache - but will try temp files.  I've tried a VPN a couple times but the issue persists.   I can try rebooting the modem...hadn't done that yet.  Or maybe look into changing IP with fiber provider.  Will try these later and report back.  </crossfingers>

sb

**Comment by JPH71** [comment]
Cheers... hopefully a workable solution will be found

I know you can ask your ISP to change your IP address...

**Comment by ScoBoXxX** [comment]
No luck after deleting cache/temp files.  Tried VPN again and no luck.  Still 403 Forbidden.
I have another Plex server on a different machine on my same local network.  I just added a video to that server and tried to match on Fagalicious - same 403 Forbidden on that machine as well.  So I feel like we can eliminate a machine-specific issue and probably is related to my IP.  But weird that a VPN wouldn't solve that.  I'll try to call Ziply later and see what they can do.

**Comment by ms52538** [comment]
Do those machines share the same software for Firewall? Anti virus? Malware
client or extensions?

**Comment by JPH71** [comment]
I don't know of any sharing...

I saw the stuff about the cache deletion when I was looking at 403 errors
on Google...

I think the following idea is well and truly wrong but... can you also
change your computers local ip???

The vpn in my opinion should have been the thing to make it work...

Within the next week or so, I will convert all the read url code to go
behind the cloud flare script, I was given by one of the groups users...

I will have to reach out again and see how we can make the code more
efficient at getting around cloudflare

Just give me 2...4 days

Jason xxx

**Comment by ScoBoXxX** [comment]
They are both Windows machines.  One is Windows 11 and the other is Windows 10.  They both use Windows Defender built-in AV and one of them also has Malware Bytes.  They are both logged into MS Edge browser with the same username but not sure why that would matter.

I can try to static-assign an IP on my local machine.  But like you I think that will be fruitless ;)

**Comment by ms52538** [comment]
A simple test would be if you can access the sites normally without being
denied access through using your browsers with the fagxxx.com URL. For
example, I use ESET for A/V and Malware; it has a tendency of deciding what
sites I can and cannot access until I make exceptions and override
standards. Stand-alone Malware client packages and browser extensions
(AdGuard for example for the former, and uBlock for the latter) can also
prevent URL connectivity to certain sites.  I've not seen the log files, so
Jason/Cody would know better if in fact the code is reaching the fagilicous
domain. I was trying to think outside the box. I will leave it to you
gents. Good luck!

**Comment by ScoBoXxX** [comment]
Understand what you mean.  I said on the related post that I can indeed access the site URLs fine on a browser.  I can take the URL right from the failing log file and paste into Edge and it works fine.  Same as Cody.

**Comment by JPH71** [comment]
We will have to find a solution... it,  however,  scrapes fine for me.
hence the suggestions I am giving...

**Comment by JPH71** [comment]
Anyone in the group - who is a scraping guru.... could you look at the code in utils.py
function getHTTPRequest - I have updated this in the new waybig bundle tht Cody will put into the repository.....
Any other ideas will be gratefully received.....

**Comment by JPH71** [comment]
OR if anyone knows of a good website with Porn Actors that we can start using....

**Comment by ScoBoXxX** [comment]
Hi all.  Just following up on this to see if there's been any progress.  I am still getting the same 403 Forbidden error on all Fagalicious match requests.  I've tried the newest PGMA code, new VPN (Nord), clearing all temp files, different machines.  Pretty much everything I can think of.  It fails every time.

**Comment by JPH71** [comment]
This has not been sorted out... I will work with Cody as he gets this error
whilst I dont

**Comment by CodyBerenson** [comment]
I only get an error on the first scan, every single time. The subsequent fix scan matches and scrapes beautifully, every single time.

**Comment by ScoBoXxX** [comment]
Awesome - so it's just me then :)  I attached a log again in case anything new jumps out.  It's only Fagalicious and unlike Cody mine fails every time.  First match and all subsequent Fix Match attempts.  Maybe I will ask my neighbor if I can hop on to their wifi and see if that has any different result.

[com.plexapp.agents.Fagalicious.log](https://github.com/CodyBerenson/PGMA-Modernized/files/12413606/com.plexapp.agents.Fagalicious.log)

**Comment by JPH71** [comment]
Yea try that... it looked like some IPs were blacklisted... as I have never
had this issue... but I generally scrape full films rather than wee
videos...

**Comment by CodyBerenson** [comment]
are you able to use your cell (with vpn enabled) as a wifi hotspot and connect to it?

**Comment by ScoBoXxX** [comment]
I tried once before with no luck but it was over remote desktop and lost connection and blah blah.  I’m away from home for a few days so i’ll report back next week after I try again (not on RDP) 👍🏻On Aug 23, 2023, at 3:29 PM, Cody Berenson ***@***.***> wrote:﻿
are you able to use your cell (with vpn enabled) as a wifi hotspot and connect to it?

**Comment by ScoBoXxX** [comment]
Update: I've tried on multiple networks - error 403 Forbidden every time.  Neighbor's wifi, iPhone hotspot, no luck at all.

**Comment by JPH71** [comment]
Darned it - I have just got back from holidays hence the silence.
I have scraped **(Falcon Studios) - Newcomer Ashley Stones makes his debut flip-fucking with Alpha Wolfe in “Falcon’s Endless Summer” (2023)** successfully....

Lets try the following:
1. Open the utils.py of the fagalicious agent for editing
2.  change line 160: From delayList = [1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0] to **delayList = [5.0, 6.0, 7.0, 8.0, 9.0, 10.0]**
3.  Open __init__.py and edit line 184: From html = HTML.ElementFromURL(searchQuery, cacheTime=4, timeout=30, sleep=utils.delay()) to **html = HTML.ElementFromURL(searchQuery, cacheTime=8, timeout=60, sleep=utils.delay())**

Fagalicious seems to be running slow, even when used manually it takes a longer time to return results....

I will need to think about another solution... I really can not understand what else could be stoping your scrape...
Attached is my log
[com.plexapp.agents.Fagalicious.log](https://github.com/CodyBerenson/PGMA-Modernized/files/12741483/com.plexapp.agents.Fagalicious.log)

**Comment by ScoBoXxX** [comment]
Hope you had a great holiday!  I was also on one provided by my employer framed as a lay-off :)  Luckily am back to work @ same job doing same thing for more $!

I made those changes and the result is the same 403 Forbidden error.  I agree Fagalicious is slow but it's pretty quick to come back with my failure lol.  
Note: I had different values in my init.py file (which is actually named __init__.py with the underscores).  Mine was:
html = HTML.ElementFromURL(searchQuery, cacheTime=3, timeout=20, sleep=utils.delay())
but I've updated it to the larger values as you said and no change.

I wish I was a coder and could help scrape the logs...but most of it is jibberish to me :( 

Thanks for all you do!

**Comment by JPH71** [comment]
Delete the fagalicious agent completely...
Restart plex... make sure its completely gone..
Then redownload from the repository...
Then we are sure we are at the same level...

**Comment by ScoBoXxX** [comment]
Did that.  No change.  But, interestingly....my other Plex server suddenly started matching with Fagalicious again.  Random.  It used to give me the same 403 Forbidden error but today it did not...and matched the title that was erroring out prior.  Sadly my adult server still doesn't.  I even copied over the Fagalicious.bundle folder from that working server and still nope.

Logs attached in case you want to compare. (1)=failing (2)=working

[com.plexapp.agents.Fagalicious(2).log](https://github.com/CodyBerenson/PGMA-Modernized/files/12769588/com.plexapp.agents.Fagalicious.2.log)
[com.plexapp.agents.Fagalicious(1).log](https://github.com/CodyBerenson/PGMA-Modernized/files/12769589/com.plexapp.agents.Fagalicious.1.log)

**Comment by ScoBoXxX** [comment]
I almost don't wanna say it for fear the Meta Gods will cast judgement upon me - but...I'm matching on Fagalicious again.  I'm not sure what changed but it's working!
I set up a new PMS on another machine to test scraping.  It worked fine on all agents.  So then I went back to my problematic PMS and did a Fix Match on one title that has been erroring for months and it matched.  No f'ing clue why.  </shrug>

**Comment by JPH71** [comment]
What!!!????

**Comment by ScoBoXxX** [comment]
Yes...imagine MY surprise!  I added all the files I had been keeping aside that were not matching - they all are now matched via Fagalicious.  Hard to believe after all this time.  Maybe F did have me flagged and released it for some reason??  I don't know.  But all is well as of this moment.  Let me know if you want logs.  I hesitate to say close this, though - ya know?

**Comment by JPH71** [comment]
Close it!!

Let's not hex it!

**Comment by JPH71** [comment]
Close this issue as its not been hexed!
