### ISSUE TITLE
[BUG]: WayBig fails to match title containing U+2022 (BULLET)

### ISSUE THREAD

**Issue by minielim** [CodyBerenson/PGMA-Modernized#257]
The filename `(CockyBoys) - Kiss•Hug•Fuck•Love (Justin Matthews, Colby Keller & Duncan Black) (2014).mp4` fails to match using the WayBig agent.

Should some transformation be applied to the unicode characters in the blog post title when naming the file?

## Specific Agent(s) Causing the Issue: ##
WayBig

## Index Site URL(s) Attempting to Match: ##
https://www.waybig.com/blog/2014/04/17/cockyboys-kiss-hug-fuck-love-justin-matthews-colby-keller-duncan-black/

## Log Attached: ##
[com.plexapp.agents.WayBig.log.txt](https://github.com/CodyBerenson/PGMA-Modernized/files/11782531/com.plexapp.agents.WayBig.log.txt)

**Comment by JPH71** [comment]
Damn!!! There is always someone who has to go and pick a scene I have not catered for....
Who is handing out hands for a smack bottom fest!!

I will look into this and sort it out for you - I have never come across a scene named thus... I think they have go a new pot head on staff!!!

**Comment by JPH71** [comment]
I take that comment back - they must have fired him.... its a scene from 2014!!!!

**Comment by JPH71** [comment]
Code will be with Cody in a few minutes.
Let me know if it works for you as you are on linux.
When I convert the bullet into ASCII I get an asterisk*, I hope this works the same for you...
If it doesn't we will work something out....

**Comment by JPH71** [comment]
Give me the url of the scene you are trying to match... and we will try and
sort it out

**Comment by JPH71** [comment]
You are right asterisks can't be used as file names...

**Comment by JPH71** [comment]
I worked on this some weeks ago... don't change the text or replace with
asterisks...

Just copy and paste it together with the bullet points...

It should work...

Jason xx
