### ISSUE TITLE
Please include Language Preferences in Agents

### ISSUE THREAD

**Issue by CodyBerenson** [CodyBerenson/PGMA-Modernized#26]
@JPH71
A user has requested that we offer Language Preferences to that returned summaries are translated from the native site's metadata.

**Comment by CodyBerenson** [comment]
On 6/12/20, this enhancement was enabled in the following agents:  WayBig, Fagalicious, QueerClick, and IAFD.  Testing is now underway for the remaining agents.

**Comment by CodyBerenson** [comment]
@JPH71

Hi Jason, Here's the status so far:

AEBN Fully passes.

All test cases fail in CD Universe.  I think there's an error.  Please look at the log.  The agent is leaving a '/' out of the search results:

Requesting 'https://www.cduniverse.comsresult.asp?HT_Search_Info=the+best+of+joey+stefano&HT_SEARCH=TITLE&style=gay&thx=1'

[com.plexapp.agents.CDUniverse.log](https://github.com/CodyBerenson/PGMA-Modernized/files/4772455/com.plexapp.agents.CDUniverse.log)

**Comment by JPH71** [comment]
I will look at that in half an hour xx

**Comment by CodyBerenson** [comment]
Updated Status.  GayDVDEmpire, GayHotMovies GayMovie and GayWorld all pass.

RadVideo and HomoActive:  4 out of 5 test files pass each. However, both of these sites' search is jacked.  e.g. on HomoActive, a file right on the main page (Rainbow Media - Boys Days) cannot be found on the search.  So, I consider each of these a pass as well.  

All that's left now for me to test is GEVI...and then retest CD Universe once you look into it.  :)

**Comment by JPH71** [comment]
I have sent you CDUniverse back for testing!

HomoActive is a bit of a weird site.... the obvious stuff canny be found
yet its right in front of your eyes....
it must have some special search rules....

J

**Comment by CodyBerenson** [comment]
Ok, I'll try it out and let you know.

Since, personally, GEVI and AEBN are mostly my go-to Agents, I did alot more file testing for those than the others.  As I mentioned, AEBN fully passed.  One file out of 20 for GEVI didn't match.  Perhaps it is the "&" symbol.

https://www.gayeroticvideoindex.com/V/1/24651.html
(Bacchus Releasing) - 35 & Up 10 (2005)

Not sure if you want to take a look or not.  I consider it a pass if you don't want to deal with it.  ;)

**Comment by JPH71** [comment]
I will look at it.... Lots of titles have ampersands and I for one am tired
of converting the ampersands to 'and's

**Comment by CodyBerenson** [comment]
So CDUniverse got farther...it will make a match but then it craps out.

[com.plexapp.agents.CDUniverse.log](https://github.com/CodyBerenson/PGMA-Modernized/files/4772978/com.plexapp.agents.CDUniverse.log)

**Comment by JPH71** [comment]
I will look at it again... I think there is an error raised when it tries
to get the title and I have not logged it...
What file were you testing it against... Send me the log

**Comment by JPH71** [comment]
I am being dumb... You sent the log file

**Comment by CodyBerenson** [comment]
All agents tested 100% passed.  Well done.  Updated agents including optional language translation functionality has been pushed to the maaster repository.
