### ISSUE TITLE
[BUG]: CRITICAL (runtime:1299) - Exception getting hosted resource hashes (most recent call last)

### ISSUE THREAD

**Issue by j-ktz** [CodyBerenson/PGMA-Modernized#263]
# Mandatory #

## Describe the bug: ## 
CRITICAL (runtime:1299) - Exception getting hosted resource hashes (most recent call last)

## Specific Agent(s) Causing the Issue: ##
WayBig, GEVI

## Index Site URL(s) Attempting to Match: ##
https://www.waybig.com/blog/2023/07/05/cockyboys-dan-evans-cody-seiya-outdoor-flip-fuck/

## Log Attached: ##
[com.plexapp.agents.WayBig.log](https://github.com/CodyBerenson/PGMA-Modernized/files/11981935/com.plexapp.agents.WayBig.log)

# Optional #

## Additional Context: ##
I searched repo and based on advice rebooted  Mac and Synology and  PMS but still no luck.

**Comment by j-ktz** [comment]
I reinstalled plugins again and it seems to be working.

**Comment by JPH71** [comment]
OK... close the issue xx

**Comment by pantherman007** [comment]
I'm getting the same "exception getting hosted resource hashes" error and have not been able to fix is with reinstalling the plugins.  I'm also running PMS on a NAS: QNAP TS-873A.  QNAP firmware is 5.1.0.2444, PMS version is 1.43.4. Trying to match against https://gayeroticvideoindex.com/video/69227 with filename (Corbin Fisher) - Hot, Young and Hung 2 (2022).mp4.  Log is attached.  Any suggestions would be appreciated.  :-)

[com.plexapp.agents.GEVI.log](https://github.com/CodyBerenson/PGMA-Modernized/files/12044475/com.plexapp.agents.GEVI.log)

**Comment by JPH71** [comment]
I have just scraped this title and all works well.
However you have made me look into the code closely at this point and I
have re-organised it a bit and explained it more.
However, there's nowt wrong with the code.

I have zipped it all up and forwarded the code to Cody - he will upload it
all to the repository as soon as he can.

I will include my log file for you to look at

Jason

**Comment by pantherman007** [comment]
Thanks. I figured it was my setup or maybe something NAS specific versus the code.  I am back up and running, but had to do a pretty hard wipe on the plugins and related components.  Deleted and replaced all of the plugins and all of the PGMA related content in Plug-in Support folder - Cache, Data, and Metadata Combination/,and Preferences.  Haven't had to do that for prior updates, but it worked and that's what counts.  :-)

**Comment by JPH71** [comment]
phew! - Saved my arse - i don't have to look at the code now!!!!

any problems - let me know quick quick!
