### ISSUE TITLE
[BUG]: Starting do undestand GeviScenes

### ISSUE THREAD

**Issue by dimitrimahiro** [CodyBerenson/PGMA-Modernized#264]
# Mandatory #

## Describe the bug: ## 

Title matched, but some info are confusing me. 

- Film on IAFD 👎 :: Actor on IAFD? ✅ Yes / ❌ No / ❔ Err403 :: GEVIScenes :: - 

What "Err403" means? The actors's pics also are not there.

Also, the summary of shows up on GEVI, but not are migrated to Plex 

![Screenshot 2023-07-10 152247](https://github.com/CodyBerenson/PGMA-Modernized/assets/20586368/631b0aa8-2b66-46fc-86db-5167b6d1f82f)
![Screenshot 2023-07-10 151746](https://github.com/CodyBerenson/PGMA-Modernized/assets/20586368/51e99c68-1b85-45fa-8454-ce9b75ef87f6)

Another thing, the year also does not go to plex too

## Specific Agent(s) Causing the Issue: ## 

GeviScenes

## Index Site URL(s) Attempting to Match: ##

https://gayeroticvideoindex.com/episode/15103
https://gayeroticvideoindex.com/episode/12187

## Log Attached: ##

[com.plexapp.agents.GEVIScenes.log](https://github.com/CodyBerenson/PGMA-Modernized/files/12005932/com.plexapp.agents.GEVIScenes.log)

# Optional #

## Screenshot(s) with all nudity redacted: ##

![Screenshot 2023-07-10 152709](https://github.com/CodyBerenson/PGMA-Modernized/assets/20586368/5ab51458-b0fe-438e-9481-abffc1bd6b30)
![Screenshot 2023-07-10 152808](https://github.com/CodyBerenson/PGMA-Modernized/assets/20586368/2537fb81-51fd-4e42-85e7-e833d1466eb9)
![Screenshot 2023-07-10 151207](https://github.com/CodyBerenson/PGMA-Modernized/assets/20586368/2dd7467d-7f06-4170-b88a-df3443ac33ee)
![Screenshot 2023-07-10 151216](https://github.com/CodyBerenson/PGMA-Modernized/assets/20586368/5ceb3e32-177d-4723-b281-db1c74886b45)

## Desktop (please complete the following information): ##
 - OS: Windows 11 Desktop
 - Browser Opera GX
 - Server Version Version 1.32.4.7195
 - Plex for Windows Version 1.69.1.3755-e00242c8

**Comment by JPH71** [comment]
403 error means that information retrieval from iafd was blocked by
cloudflare protection.

And thus the actors picture was not got. Therefore only the initials
appear...

A question mark will only appear if the agent can't get the actors oage or
is unable to search for the actor due to the above mentioned protection...

I will be improving this to show the question mark if it gets the info but
fails to get the photo...

That's if I don't find a way to get round the protection...


Jason x

**Comment by fourstix** [comment]
Hi,
Err403 indicates HTTP Response code 403 "Forbidden" This means the server understood the request, but will not fulfill it.   It's used by IAFD and other servers that use CloudFlare to do rate limiting on automated requests.

There's an issue open #243 to improve the agent handling for this response.

**Comment by JPH71** [comment]
Looked at your log file for https://gayeroticvideoindex.com/episode/15103
You have the studio name wrong it should be Bulldog XXX not Bulldog Pit and the file should be named
(Bulldog XXX) - Innocence Lost - {15103N} (2016)

the second one should be named:
(Bare Adventures) - Sony White and Lucas Pribyl - {12187N} (2015)

I have tested and they work....

Please close the issue.....

Jason x

**Comment by dimitrimahiro** [comment]
As mentioned, the summary from GEVI itself isn't read by Plex

**Comment by JPH71** [comment]
I will look at the cide tonight and get back to you... they might have also
changed that and I missed that...

I can be quite thick at times!!!

Sorry...

**Comment by JPH71** [comment]
Please call this issue as it is related to the IAFD Error which is now resolved
