### ISSUE TITLE
[BUG]: Film scrapers not working (AEBN, GEVI, GayEmpire, GayHotMovies)

### ISSUE THREAD

**Issue by vampirelayer** [CodyBerenson/PGMA-Modernized#272]
# Mandatory #

## Describe the bug: ## 
I just downloaded the latest scrapers to test. All four scrapers stopped at this *Critical* error:

`2023-08-06 12:32:46,759 (16e377000) :  CRITICAL (agentkit:1018) - Exception in the search function of agent named 'GayHotMovies (IAFD)', called with keyword arguments {'id': '57424', 'guid': 'com.plexapp.agents.GayAdultFilms://57424?lang=en', 'force': True, 'primary_agent': 'com.plexapp.agents.GayAdultFilms', 'parentID': None} (most recent call last):
  File "/Applications/Plex Media Server.app/Contents/Resources/Plug-ins-91e1e2e2c/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/api/agentkit.py", line 1011, in _search
    agent.search(*f_args, **f_kwargs)
  File "/Users/duchess/Library/Application Support/Plex Media Server/Plug-ins/GayHotMovies.bundle/Contents/Code/__init__.py", line 119, in search
    AGENTDICT = copy.deepcopy(utils.setupAgentVariables(media))
  File "/Users/duchess/Library/Application Support/Plex Media Server/Plug-ins/GayHotMovies.bundle/Contents/Code/utils.py", line 7606, in setupAgentVariables
    pass
  File "/Applications/Plex Media Server.app/Contents/Resources/Python/python27.zip/posixpath.py", line 68, in join
    if b.startswith('/'):
AttributeError: 'NoneType' object has no attribute 'startswith'
`

## Specific Agent(s) Causing the Issue: ##

- AEBN
- GEVI
- GayEmpire
- GayHotMovies

## Index Site URL(s) Attempting to Match: ##

[https://gayeroticvideoindex.com/video/2000](https://gayeroticvideoindex.com/video/2000)

## Log Attached: ##
[com.plexapp.agents.GayHotMovies.log](https://github.com/CodyBerenson/PGMA-Modernized/files/12268705/com.plexapp.agents.GayHotMovies.log)
[com.plexapp.agents.GayEmpire.log](https://github.com/CodyBerenson/PGMA-Modernized/files/12268706/com.plexapp.agents.GayEmpire.log)
[com.plexapp.agents.AEBN.log](https://github.com/CodyBerenson/PGMA-Modernized/files/12268707/com.plexapp.agents.AEBN.log)
[com.plexapp.agents.GEVI.log](https://github.com/CodyBerenson/PGMA-Modernized/files/12268708/com.plexapp.agents.GEVI.log)

# Optional #

## Screenshot(s) with all nudity redacted: ##
![image](https://github.com/CodyBerenson/PGMA-Modernized/assets/81353722/6a0b6c1b-236c-4be6-afb4-cf85070765fb)

## Desktop (please complete the following information): ##
 - OS: MacOS Ventura 13.4.1(c)
 - Browser: N.A. as I'm using the native Plex app for Mac
 - Version 1.75.0.3920-8b50876d

**Comment by JPH71** [comment]
Could you try saving the preferences and see if that sorts it out... As i
have scraped over 200 titles using GEVI with no issues...

Also i have removes one of the preferences...

I will look at this later today...

Jason x

**Comment by JPH71** [comment]
Could you send me the whole log file, if you don't mind.
Have you saved the preferences then restarted Plex Media Server??

Cheers

Jason x

**Comment by JPH71** [comment]
The agent preferences....

**Comment by JPH71** [comment]
This will be the place where you choose whether to have collections or
not... etc

**Comment by JPH71** [comment]
I was having a senior moment in regards to the logs...

**Comment by vampirelayer** [comment]
> This will be the place where you choose whether to have collections or not... etc
> […](#)

No love, I saved GEVI preferences.

**Comment by JPH71** [comment]
Sorry for quoting the obvious but time and time again I have also had this
issue... and the saving 0references and more importantly exiting then
restarting plex media server has solved this issue...

Cheers

Jason x

**Comment by CodyBerenson** [comment]
@vampirelayer can this be closed?  It looks from the logs as @JPH71 that the agents do not see the _PGMA folder.  Please verify and close.  Thanks.

**Comment by vampirelayer** [comment]
I’ll check this later tonight. Sent from my iPhoneOn 14 Aug 2023, at 1:38 AM, Cody Berenson ***@***.***> wrote:﻿
@vampirelayer can this be closed?  It looks from the logs as @JPH71 that the agents do not see the _PGMA folder.  Please verify and close.  Thanks.

**Comment by vampirelayer** [comment]
![image](https://github.com/CodyBerenson/PGMA-Modernized/assets/81353722/30e24121-ffc1-4434-818a-a5bc9dc3fd73)

**Comment by JPH71** [comment]
That is correct
U can remove nynmedia...the website went down

**Comment by vampirelayer** [comment]
I will close this bug.
Had to clean out my Plex Support File and also decided to scrape my entire collection again.
