### ISSUE TITLE
[BUG]: Fagalicious Not Scraping  - The read operation timed out

### ISSUE THREAD

**Issue by j-ktz** [CodyBerenson/PGMA-Modernized#275]
# Mandatory #

## Specific Agent(s) Causing the Issue: ##

File: __init__.py, Line: 284, Function: _process_function_call -> _search -> search
Error: Search Query did not pull any results: ('The read operation timed out',)

## Index Site URL(s) Attempting to Match: ##
https://fagalicious.com/sean-cody-cam-crawford-fucks-kyle-denton-bareback/

## Log Attached: ##
Yes
[com.plexapp.agents.Fagalicious.log](https://github.com/CodyBerenson/PGMA-Modernized/files/12383344/com.plexapp.agents.Fagalicious.log)

# Optional #

**Comment by JPH71** [comment]
This worked for me with no problems - I named the file thus:(Sean Cody) -
Cam Crawford fucks Kyle Denton bareback (2023)

Jason xxx

**Comment by j-ktz** [comment]
Ah you're right. Worked for me when I tried again. My bad!
