### ISSUE TITLE
[BUG]: Full Film Scraping Errors with GEVI

### ISSUE THREAD

**Issue by vampirelayer** [CodyBerenson/PGMA-Modernized#276]
# Mandatory #

## Describe the bug: ## 
I have cleaned out my plugins and plug-in support folder to re-scrape my collections.
I started with just one film to make sure my settings are in order before proceeding with the remaining - about 1K+!

Three major observations I made:

1. Missing cast information and truncated poster

![image](https://github.com/CodyBerenson/PGMA-Modernized/assets/81353722/56809fe9-114a-4be2-9c08-ef08a9cdc312)
a. There used to be a cast gallery right after Summary, it's gone now.
b. The film poster is now truncated in some places e.g. in Recently Added
![image](https://github.com/CodyBerenson/PGMA-Modernized/assets/81353722/5e9883eb-490a-4667-ae27-924295a90b82)

2. Missing actor profile pic in Collections
![image](https://github.com/CodyBerenson/PGMA-Modernized/assets/81353722/b940a196-5a60-4f85-996d-305158252ed6)

3. Missing token - this is a minor issue, which I resolved by manually entering the token, but if there's a way to resolve it elegantly let me know.

![image](https://github.com/CodyBerenson/PGMA-Modernized/assets/81353722/efa931da-e4bb-4521-a0bc-9d2bc5ef0832)

## Specific Agent(s) Causing the Issue: ##

- GEVI

## Index Site URL(s) Attempting to Match: ##

https://gayeroticvideoindex.com/video/29636

## Log Attached: ##
[com.plexapp.agents.GEVI.log](https://github.com/CodyBerenson/PGMA-Modernized/files/12567589/com.plexapp.agents.GEVI.log)

# Optional #

## Desktop (please complete the following information): ##
 - OS: macOS Ventura
 - Browser: N.A.
 - Version: 13.4.1

**Comment by JPH71** [comment]
Currently Film Cast and Director collections are not scraping the performances images. So keep these disabled until I can get a way to overcome cloudflare issues...
these cause failures which exit the scraping process.
Change these options, restart PLEX and try scraping again...

**Comment by vampirelayer** [comment]
Thanks. I unchecked those two attributes but I'm still getting the same results. 
Could it be an issue with the Plex app?

**Comment by vampirelayer** [comment]
This is due to incorrect Plex library settings. Should have set my agent to `Gay Adult`
