### ISSUE TITLE
[BUG]: Matching Issue with Waybig

### ISSUE THREAD

**Issue by Davijon31** [CodyBerenson/PGMA-Modernized#277]
# Mandatory #

## Describe the bug: ## 
Can't get a match with Scene agent and Waybig.

## Specific Agent(s) Causing the Issue: ##
WAYBIG

## Index Site URL(s) Attempting to Match: ##
https://www.waybig.com/blog/2007/02/08/popboys-oliver-strelly-george/

## Log Attached: ##
[com.plexapp.agents.WayBig.log](https://github.com/CodyBerenson/PGMA-Modernized/files/12573388/com.plexapp.agents.WayBig.log)

# Optional #

## Additional Context: ##
This is how I named my file :
(PopBoys) - Oliver Strelly Fucks George (2007).mp4

## Desktop (please complete the following information): ##
 - OS: [e.g. iOS] Ventura 13.5.2 
 - Browser [e.g. chrome, safari] Safari
 - Version [e.g. 22] 16.6

**Comment by CodyBerenson** [comment]
@Davijon31 

Hello.  Your log indicates that you have not made a preference check for genre collection.  Please go into the settings for the agent and make a selection.  Save the settings.  Stop and restart PMS.  

![image](https://github.com/CodyBerenson/PGMA-Modernized/assets/40373801/55afcdb3-7019-4f06-b3fb-f71f5dc5a804)
