### ISSUE TITLE
[BUG]: Posters not pulling in

### ISSUE THREAD

**Issue by j-ktz** [CodyBerenson/PGMA-Modernized#284]
Hey boys, it looks like URL might have expired. The link isn't working and Plex won't pull in posters.

**Comment by CodyBerenson** [comment]
Thanks for letting us know.  New thumbor address established:
![image](https://github.com/CodyBerenson/PGMA-Modernized/assets/40373801/2cff0a94-301a-4bba-864e-e4e71bfc9a2a)

@jph71 Please update the agents.  Thanks!

**Comment by CodyBerenson** [comment]
In case anyone is interested for their own purposes, here's how to do this on Google's Cloud, which gives 90 days for free:

1.  Disconnect VPN
2.  https://cloud.google.com
4.  Setup Project
5.  Create a VM.  Change operating system to Container Optimized OS and disk size to 20 GB, Allow http traffic
6. Use SSH to install docker:
docker run -p 8888:80 minimalcompact/thumbor 
7.  Setup Firewall Rule:  
+ Create Firewall Rule
All instances in the network
Range:  0.0.0.0/0
Port: 8888

**Comment by JPH71** [comment]
Cheers xxx
