### ISSUE TITLE
[BUG]: Unable to add metadata to one file

### ISSUE THREAD

**Issue by Jay-Mega** [CodyBerenson/PGMA-Modernized#286]
# Mandatory #
Just following instructions in Read Me

## Describe the bug: ## 
Metadata for file doesn't appear to be loading, no poster, no movie information

## Specific Agent(s) Causing the Issue: ##
Using GayEmpire (IAFD), AEBN (IAFD), Internet Adult Film Database in Gay Adult, 

## Index Site URL(s) Attempting to Match: ##
https://gay.aebn.com/gay/movies/210458/take-that-black-dick-white-boy
https://www.gaydvdempire.com/3272248/take-that-black-dick-white-boy-porn-videos.html

## Log Attached: ##
[com.plexapp.agents.AEBN.log](https://github.com/CodyBerenson/PGMA-Modernized/files/13479295/com.plexapp.agents.AEBN.log)
[com.plexapp.agents.GayEmpire.log](https://github.com/CodyBerenson/PGMA-Modernized/files/13479296/com.plexapp.agents.GayEmpire.log)

# Optional #

## Screenshot(s) with all nudity redacted: ##
https://pic.aebn.net/dis/t/210458/210458_00000009.jpg?s=180h
https://caps1cdn.adultempire.com/r/9896/1920/3269896_06900_1920c.jpg

## Desktop (please complete the following information): ##
 - OS: Windows 10
 - Browser: Firefox
 - Version: 120.0 (64-bit)

**Comment by Jay-Mega** [comment]
I am trying to scrape the film Take That Black Dick White Boy as a test: https://gay.aebn.com/gay/movies/210458/take-that-black-dick-white-boy

Here is how I'm naming the file: (Treasure Island Media) - Take That Black Dick White Boy (2016)

**Comment by JPH71** [comment]
You have named it correctly.
Let me take a look at the logs...

**Comment by JPH71** [comment]
Your error as said in the log file was that the filename was not in the
expected format - spacing is important
(Treasure Island Media) *-T*ake That Black Dick White Boy (2016)

should be

(Treasure Island Media) - Take That Black Dick White Boy (2016)

Hope this helps!

**Comment by Jay-Mega** [comment]
That's interesting, it is written like this in my test folder:

(Treasure Island Media) - Take That Black Dick White Boy (2016)

I tried (Treasure Island Media)-Take That Black Dick White Boy (2016) with no spaces and nothing. I tried Fix Match and this is what comes up: 
![image](https://github.com/CodyBerenson/PGMA-Modernized/assets/152198431/79488c0b-d70a-44c2-882b-dbff7be34095)

Do you think that it might just be a case of that movie not having the metadata or do I need to use a different scraper?

**Comment by JPH71** [comment]
There have to be spaces..
In the logs you sent before the aebn it complained that it was not in the
correct format.

You should use GEVI, it's the best of the sites...

Followed by AEBN, gayemoire and gayhotmovies...

Thise are the big 4....

Try it again and let me know...

**Comment by CodyBerenson** [comment]
@Jay-Mega As Jason mentions, spacing is important.  The agents are a bit forgiving about some things, but in general follow the naming convention as is detailed in the guide.

A filename with no spaces between the studio and the title will NEVER work. Space dash space between (Studio) and Title are mandatory

i.e. (Studio) - Title (YEAR)

**Comment by Jay-Mega** [comment]
I'm still having some issues. And I did follow the spacing guidelines, I added another file and still nothing. This is how they are written:

(Treasure Island Media) - Take That Black Dick White Boy (2016)
(Wurstfilm) - My Israeli Platoon (2008)

I attached logs, I hope I got the right ones.
[com.plexapp.agents.GayAdult.log](https://github.com/CodyBerenson/PGMA-Modernized/files/13494846/com.plexapp.agents.GayAdult.log)
[com.plexapp.agents.GEVI.log](https://github.com/CodyBerenson/PGMA-Modernized/files/13494847/com.plexapp.agents.GEVI.log)

**Comment by JPH71** [comment]
I am using my mobile at the moment and it's rather difficult to read the
logs..

In the settings, try turning DURATION MATCHING off.

Then restart Plex Media Server, for the changes to take effect...

Jason x

**Comment by Jay-Mega** [comment]
Looks like turning off the duration matching worked! Thank you!

**Comment by JPH71** [comment]
You are welcome...
When some people convert movie, they sometimes chip of the crédits and
intros to the films  ..
