### ISSUE TITLE
[BUG]: GEVI matched but messed up names

### ISSUE THREAD

**Issue by XanderKwan** [CodyBerenson/PGMA-Modernized#288]
# Mandatory #

## Describe the bug: ## 
GEVI seems to work perfectly fine for most of my scenes. However, some of them were matched successfully but the name of the scenes don't show up. Instead they show something like "gaybbtrans.com" or sometimes an unfinished name with "_" or "-" between words. The other information including cast are complete.

**example**
File name: (Cutlers Den) - Deshae + John Thomas - {185954N}.mp4
Name shown: gaybbtrans.com
Matching URL: https://gayeroticvideoindex.com/episode/185954

## Specific Agent(s) Causing the Issue: ##
GEVI
## Index Site URL(s) Attempting to Match: ##
https://gayeroticvideoindex.com/episode/185954
## Log Attached: ##

# Optional #

## Desktop (please complete the following information): ##
macOS Monterey

![Screen Shot 2023-12-14 at 12 16 50 AM](https://github.com/CodyBerenson/PGMA-Modernized/assets/116384267/ef88f618-7f0b-4b3f-ae9c-468fba834c7d)
[com.plexapp.agents.GEVIScenes.log](https://github.com/CodyBerenson/PGMA-Modernized/files/13668853/com.plexapp.agents.GEVIScenes.log)

**Comment by XanderKwan** [comment]
anybody?

**Comment by JPH71** [comment]
I will look at this today

**Comment by CodyBerenson** [comment]
@XanderKwan I believe Plex is natively using metadata already embedded in your file.  If you look at the Properties Details of your file (in windows, its third tab of properties...see image), you'll likely see the file itself has a metadata title of gaybbtrans.com. You should clear this metadata from the file's properties.  It is unusual that download sites such as gaybbtrans.com tag their files with metadata.  

![image](https://github.com/CodyBerenson/PGMA-Modernized/assets/40373801/77ffa918-d580-4ec0-a362-3b1eaa20236a)

**Comment by XanderKwan** [comment]
Cody, thank you! this explains a lot!!!

**Comment by jfreiman** [comment]
I believe that this issue has been resolved and the 'problem' was the Plex scraper grabbing the Title from the metadata.

Please do not change this as I rely on my additional metadata to correct casing, or beautify title matches with WayBig and others which can be exceedingly long.

**Comment by JPH71** [comment]
please mark this as resolved...
Putting local metadata lower in the agent list also resolves this issue

**Comment by JPH71** [comment]
Ta
