### ISSUE TITLE
[BUG]: Unable to match any GayAdult metadata across several libraries.

### ISSUE THREAD

**Issue by joshallen13** [CodyBerenson/PGMA-Modernized#289]
# Mandatory #

## Index Site URL(s) Attempting to Match: ## [
](https://gayeroticvideoindex.com)

## Log Attached: ## 
[Plex Media Scanner.log](https://github.com/CodyBerenson/PGMA-Modernized/files/13800307/Plex.Media.Scanner.log)

# Optional #

## Desktop (please complete the following information): ##
 - OS: [e.g. iOS] macOS Sonoma
 - Browser [e.g. chrome, safari] Safari 
 - Version [e.g. 22] v. 17.2.1

**Comment by JPH71** [comment]
I will look at the logs later on..
By the way have you set the agent parameters?
Jason

**Comment by joshallen13** [comment]
It's been unable to match anything for several weeks, and of course the moment I complain about it and open up an issue, it begins to start matching again. Although a little slow, it's finally giving me something! I will close the issue if it finishes matching all titles without further issue.

**Comment by JPH71** [comment]
OK man...
Sods law...
We have all come across this issue when one reports an issue!!

**Comment by JPH71** [comment]
please mark issue as resolved

**Comment by JPH71** [comment]
Ta
