### ISSUE TITLE
New Thumbor Instance

### ISSUE THREAD

**Issue by CodyBerenson** [CodyBerenson/PGMA-Modernized#292]
Hi @jph71!

Happy Anniversary.  3 months have passed, so our thumbor instance is dead.  Here's the new thumbor address:

http://35.236.218.226

Please update the bundles?  Thanks!!!

**Comment by JPH71** [comment]
Fixed!

**Comment by CodyBerenson** [comment]
Repository updated.  Thanks!

**Comment by JPH71** [comment]
You are welcome! As always xxx
