### ISSUE TITLE
Installation confusion

### ISSUE THREAD

**Issue by carl467** [CodyBerenson/PGMA-Modernized#294]
### Discussed in https://github.com/CodyBerenson/PGMA-Modernized/discussions/262

<div type='discussions-op-text'>

<sup>Originally posted by **gideunz** July  6, 2023</sup>
I am having a lot of trouble getting PGMA to work. I have followed the directions from the old and new Installation and Usage guide, but for some reason I can't any of the plug-ins to show up in the newest Windows 64bit version of PMS and I have also tried uninstalling and reinstalling both PMS and all of my plug-ins with no success. I cloned and downloaded the repository using the Windows GIthub desktop application and according to the installation guide, if I am reading this correctly I just copy the entire PDMA-Modernized directly into the PMS plug-ins folder without removing any of the bundle folders. I completely understand that you might not be able to respond immediately Cody, but any help or suggestions that might be useful would greatly be appreciated, because I would really love to be able to use these plug-ins in PMS.

**Comment by JPH71** [comment]
Send a snapshot of your plugins folder then we can see what you've done...
A picture is worth a thousand words xxx

**Comment by carl467** [comment]
Here's the screenshot of my plug-ins folder and the one thing that I realized when I looked at my plug-ins folder is that I apparently changed the name of the folder PGMA-Modernized to PGMA-Modernized.bundle and I am not sure ifthis makes any difference as to why I can't get the plug-ins to show up in PMS and I am also including a screenshot of the current agents that showing up in PMS as well. I hope the screenshots help.
<img width="828" alt="Plug-ins folder" src="https://github.com/CodyBerenson/PGMA-Modernized/assets/145383338/f6f3ae8a-d883-4316-878b-259a15dd2472">
<img width="741" alt="PMS Agents Movies" src="https://github.com/CodyBerenson/PGMA-Modernized/assets/145383338/ca10e8e7-a2fc-4069-9f7a-c292c52d7ea0">
<img width="746" alt="PMS Agents Shows" src="https://github.com/CodyBerenson/PGMA-Modernized/assets/145383338/b84d0a10-1748-4a59-9ff2-22cc79a1cac1">

**Comment by JPH71** [comment]
Here is mine!

[image: image.png]

And my Plex Settings: Fims
[image: image.png]

Scenes:
[image: image.png]

And an Example of an Agent's Settings:
[image: image.png]

**Comment by CodyBerenson** [comment]
@carl467  Hello, and welcome.

I believe I see your issue.  You shouldn't have a "PGMA-Modernized" or a "PGMA-Modernized.bundle" in your plug-ins folder.  You should have the contents (i.e. all of the individual bundles folders and the _PGMA folder) copied to your plug-ins folder.  

Go one folder down in the zipped clone from GitHub of PGMA-Modernized.  You'll see 28 folders and 5 files.  This is what should be copied to your Plex Plug-ins folder.  Technically, only 26 of these folder need to be copied, as highlighted in this image.  So, try again, kill plex, give it a moment, restart it, and you should see the magic.

![image](https://github.com/CodyBerenson/PGMA-Modernized/assets/40373801/e78910d1-0c52-49e0-b855-720c2e60f9c3)

**Comment by carl467** [comment]
I can't see your pictures, because either they were not attached or for some reason github removed them. I also tried to follow the instructions from the original project PGMA that you have forked on your page and I still can't the plug-ins to show in PMS. I understand how to set up the the plug-ins in the settings, I just need to figure out why I can't get them to show up in PMS. I noticed that in one of the bundle folders there is cduniverse in XML format, can you explain what the xml's do in PMS, because I am not a coder or programmer. Please send me the pictures, so that I can get a better idea of what I need to do get the plug-ins to show up in PMS and thank you for the help.

**Comment by CodyBerenson** [comment]
@carl467 

p.s.  I see that you are using ThePornDB Scene and Movie bundles.  If you're familiar with those, ours are very similar, with a couple distinctions:
1.  Naming convention for theirs vs. ours are different.  File naming matters....follow the naming convention guidance in our guide
2. Ours return a lot more metadata than theirs.  This makes ours better.  LOL.  :)
3.  Ours match actors and retrieves their headshots from the Internet Adult Film Database, which has substantially more actor photos than ThePornDB does...again, makes ours better.  ;)
4. There are plenty of times when ThePornDB has films and scenes that aren't indexed in any of the sites that we use, so kudos for rounding out your set of tools with ThePornDB.  I'm a big fan of the site, and its plugin for TinyMediaManager.

Cheers!

**Comment by CodyBerenson** [comment]
@carl467 Also, do not forget to set the preferences for each of our agents that you choose to use.  Without all of the preference set the agents will not function.  Cheers!

**Comment by carl467** [comment]
Thanks for the help Cody and I now have the plug-ins showing up in PMS and I am going through setting them up under the PMS settings through both movies and shows. Cody I noticed that in one of the bundle folders is the cduniverse.bundle. I am not a coder or a porgrammer, so I don't the difference as to why some scripts and agents are json, xml or python, but I did want to ask if you don't mind answering this if you do know Cody, but I have noticed on a lot of the plex forums as well as a lot of the plex projects on here urging people to use either the json or xml agent if the python one isn't working. Cody, how do you use either the json or xml scripts or agents in PMS, in case I may need to switch to using these in the future? Cody if anyone asks you about using AdultEmpire or GayAdultEmpire as far as getting the metadata is concerned, all they need is the set of numbers directly after the .com and forward slash, but I have found that doing a search on the website and selecting the dvd option instead of the vod option proves to pull all the information instead of only a small portion. Thanks again for your help Cody and I am glad that you created or improved this project, because for me it gives me additional options to match my videos with the correct metadata.

**Comment by CodyBerenson** [comment]
@carl467 Terrific!  Glad you're proceeding.  For coding questions, I'll defer to Jason @JPH71.  He's the brains, I'm just the eye-candy.

**Comment by carl467** [comment]
Thanks Cody for your help, but do you mind asking him to attach pictures when he responds, because when he sent his response last night none of the pictures that he told me to look at showed up in either the email that I received or on his response on here.

**Comment by CodyBerenson** [comment]
Its the price we pay for an overworked genius.

**Comment by carl467** [comment]
Cody do I need to keep the readme.md file in the plug-ins folder?

**Comment by CodyBerenson** [comment]
You do not.  Just the 26 folders.  I did send Jason a reminder about uploading images directly in GitHub.  :)

**Comment by carl467** [comment]
Thanks again Cody for your help and I'm not sure if I would have figured out exactly what I did wrong and why I couldn't get the plug-ins to show up in PMS. Cody I am sure glad that you messaged me this morning, because you prevented me from reinstalling my operating system thinking that might have been the problem.

**Comment by JPH71** [comment]
Here is mine!
![image](https://github.com/CodyBerenson/PGMA-Modernized/assets/43102249/12c8f5bd-369d-47b7-8d5b-7af6d73d4665)

And my Plex Settings: Films
![image](https://github.com/CodyBerenson/PGMA-Modernized/assets/43102249/00153427-fd19-489a-a40d-33c50fd945e0)

Scenes:
![image](https://github.com/CodyBerenson/PGMA-Modernized/assets/43102249/10121271-c98a-43a6-98b1-3a0a4a787bb3)

Example of an Agent Setting:
![image](https://github.com/CodyBerenson/PGMA-Modernized/assets/43102249/48c14855-ab4f-4c6f-b92a-a3d5234404dc)


Note to oneself : Vodka, Red Bull and Github is not a cocktail that works!

**Comment by carl467** [comment]
Jason, Cody tells me that you are the brains of the project and the real genius when it comes to the technical aspects. Jason, I noticed that some scripts and agents in the bundle folders are json, xml or python, but I did want to ask if you don't mind answering this Jason, but I have noticed on a lot of the plex forums as well as a lot of the plex projects on here in the readme.md files urging people to use either the json or xml agent or script if the python agent or script isn't working. Jason, how do you use either the json or xml scripts or agents in PMS, in case I may need to switch to using these in the future?

**Comment by JPH71** [comment]
Hi Carl,

No, we are still on the python scripts. json is used for the settings.
If you have an example of the json/xml agents - send me a link and I will
look into it..

Jason xx
