### ISSUE TITLE
[BUG]: Error trying to match a movie with GayEmpire agent

### ISSUE THREAD

**Issue by joca879** [CodyBerenson/PGMA-Modernized#296]
# Mandatory #

## Describe the bug: ## 
Error trying to match a movie

## Specific Agent(s) Causing the Issue: ##
GayEmpire

## Index Site URL(s) Attempting to Match: ##
https://www.gaydvdempire.com/1665091/2-poles-in-1-hole-gay-porn-movies.html
## Log Attached: ##
[com.plexapp.agents.GayEmpire.log](https://github.com/CodyBerenson/PGMA-Modernized/files/14998855/com.plexapp.agents.GayEmpire.log)

# Optional #

**Comment by joca879** [comment]
None of the users have had errors similar to this one when trying to match a movie with the GayEmpire agent?

**Comment by JPH71** [comment]
Not that I have heard off...
I will look at this over the weekend as I lost my contract... last day is
tomorrow..

**Comment by JPH71** [comment]
Hi Joca, please mark issue as resolved.

**Comment by CodyBerenson** [comment]
@joca879 @JPH71  My apologies.  I just realized I didn't push the fix to the repository.  Doing it now.

**Comment by JPH71** [comment]
Cheers
