### ISSUE TITLE
Enhance GEVI to match titles with punctuation and non-standard characters in them

### ISSUE THREAD

**Issue by CodyBerenson** [CodyBerenson/PGMA-Modernized#3]
@jph71 

Hi Jason,

The major update to GEVI fixed so, so much...not that it wasn't already terrific to start.  

So, really, the largest challenge with GEVI now is when there's punctuation in the title of the movie:

    (Celsius Productions) - Hard To Believe! (1986).mpg
    (Video 10) - G.I. Mac (1988).mpg
    (S.E.V.P.) - Happy Birthday Bruce! (1999).avi
    (Pietro Films) - Mãos à Obra (2001).avi

You ROCK!

**Comment by CodyBerenson** [comment]
Here's a couple more:

1. (Man's Best) - Liebesgrüße aus Mallorca (2002).avi
2. (Image Video) - Looking for Mr. Big (1993).mpg 

Ciao prego

**Comment by JPH71** [comment]
@CodyBerenson 
These four now match
(Celsius Productions) - Hard To Believe! (1986).mpg - change to GEVI
(Video 10) - G.I. Mac (1988).mpg - change to GEVI
(S.E.V.P.) - Happy Birthday Bruce! (1999).avi - change to GEVI
(Pietro Film**e**s) - Mãos à Obra (2001).avi - you had a spelling mistake in the studio!
(Man's Best) - Liebesgrüße aus Mallorca (2002).avi  - change to GEVI
(Image Video) - Looking for Mr. Big (1993).mpg - found it on page 47 - but no poster art!


the following would not work as when some special characters were not converted the correct way by GEVI
(Man's Best) - Liebesgrüße aus Mallorca (2002).avi should have being converted by GEVI as 
liebesgrusseau**ss**mallorca but was recorded as liebesgrusseau**s**mallorca

Here you go - happy testing!
[GEVI.bundle.zip](https://github.com/CodyBerenson/PGMA-Modernized/files/4447398/GEVI.bundle.zip)

**Comment by CodyBerenson** [comment]
@JPH71 

GEVI = 100% success.  Even the one you said didn't match matched:

![image](https://user-images.githubusercontent.com/40373801/78735320-883b8700-7918-11ea-902d-0852beb6bcc3.png)

I will continue to do some more testing, but at this point I'm going to update the master repository and call it complete.  There isn't a single outstanding issue with GEVI.

YOU ROCK!!!!!!!!!!!   A pint on me...perhaps seven....well earned!!!

**Comment by CodyBerenson** [comment]
Master repo is updated.

**Comment by JPH71** [comment]
Oh yes the Mallorca one also matched for me... I just had to replace β with
an 's' before sorting out the other accented and special letters..
And now GEVI has a pukka function that sorts out it's search routine!

Jason xx

**Comment by CodyBerenson** [comment]
All GEVI enhancements and issues resolved.  Closing issue.
