### ISSUE TITLE
[BUG]: WayBIG not matching

### ISSUE THREAD

**Issue by ms52538** [CodyBerenson/PGMA-Modernized#309]
# Mandatory #

## Log Attached:  Yes ##

# Optional #

## Desktop (please complete the following information): ##
 - OS: Windows 11 23H2 22631.3951
 - Browser: MS Edge
 - Version: 126.0.2592.87 (Official build) (64-bit)

![Screenshot_13-7-2024_124222_127 0 0 1](https://github.com/user-attachments/assets/db90292d-e265-4602-86b7-16cf60f299a1)
[com.plexapp.agents.WayBig.log.3.txt](https://github.com/user-attachments/files/16202980/com.plexapp.agents.WayBig.log.3.txt)

**Comment by j-ktz** [comment]
This one matched fine for me!

**Comment by ms52538** [comment]
Thanks, I’ll double check my title.

**Comment by ms52538** [comment]
And now it's matched. I'll close the issue as it appears to be a false-flag.

**Comment by JPH71** [comment]
Please close bug
