### ISSUE TITLE
Please add gt agent

### ISSUE THREAD

**Issue by bknfla** [CodyBerenson/PGMA-Modernized#37]
Please add https://gay(dash)torrents(dot)net  as an agent. Not sure how much advertisement they want.  But they have all the meta data including tags which would be nice to have.

**Comment by JPH71** [comment]
I will look at it tomorrow and let you know.. if there are no stupid adult
confirmation buttons that stop you getting to page... It should be a
breeze... I will just have to test the search functionality and see it's
responsiveness

Do spread the word about our agents to all and sundry

Jason x

**Comment by JPH71** [comment]
Couldn't help myself and had a look... Unfortunately you need an account to
get to the torrent listings

So is a no go...
