### ISSUE TITLE
Can't get a title to match...

### ISSUE THREAD

**Issue by mhunter8** [CodyBerenson/PGMA-Modernized#38]
I've noticed some weirdness with the GEVI site and usually have been able to fairly easily tweak around it by altering the title so it matched, but in this case I'm at a loss.  

The title is (BelAmi) - Greek Holiday 2 Crusing Mykonos (2004)

Here is the output from the log:

GEVI - SEARCH:: Processing: Studio: BelAmi   Title: Greek Holiday 2: Crusing Mykonos   Year: 2004
GEVI - SELF:: Original Search Query [Greek Holiday 2: Crusing Mykonos]
GEVI - SELF:: Search Query:: String has none of these [',&!.#]
INFO (sandbox:19) - GEVI - SELF:: Search Query:: String has none of these [-–—()]
INFO (sandbox:19) - GEVI - SELF:: Search Query:: First word is not numeric
INFO (sandbox:19) - GEVI - SELF:: Search Query:: Splitting at position [14]. Found one of these [0-9]
INFO (sandbox:19) - GEVI - SELF:: Amended Search Query [greek holiday ]
INFO (sandbox:19) - GEVI - SELF:: Search Query:: First word has none of these ['a', 'an', 'the', 'un', 'une', 'des', 'le', 'la', 'les', "l'", 'uns', 'umas', 'o', 'a', 'os', 'as', 'un', 'una', 'unos', 'unas', 'el', 'la', 'los', 'las', 'ein', 'eine', 'eines', 'einen', 'einem', 'einer', 'das', 'die', 'der', 'dem', 'den', 'des']
INFO (sandbox:19) - GEVI - SELF:: Amended Search Query [greek+holiday]
INFO (sandbox:19) - GEVI - SEARCH:: Search Query: https://www.gayeroticvideoindex.com/search.php?type=t&where=b&query=greek+holiday&Search=Search&page=1
DEBUG (networking:138) - Fetching 'https://www.gayeroticvideoindex.com/search.php?type=t&where=b&query=greek+holiday&Search=Search&page=1' from the HTTP cache
INFO (sandbox:19) - GEVI - SEARCH:: No More Pages Found
INFO (sandbox:19) - GEVI - SEARCH:: Result Page No: 1, Titles Found 2
INFO (sandbox:19) - GEVI - SEARCH:: Title Match: [False] Compare Title - Site Title "greekholiday2crusingmykonos - greekholidaycruisingtheaegean"
INFO (sandbox:19) - GEVI - SEARCH:: Title Match: [False] Compare Title - Site Title "greekholiday2crusingmykonos - greekholiday2cruisingmykonos"
DEBUG (runtime:88) - Sending packed state data (104 bytes)
DEBUG (runtime:924) - Response: [200] str, 320 bytes
DEBUG (runtime:717) - Handling request GET /:/plugins/com.plexapp.agents.GEVI/messaging/function/X0FnZW50S2l0OkVyYXNlTWV0YWRhdGE_/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoxCmRpY3QKMgpzNQpNb3ZpZXMxMAptZWRpYV90eXBlczQ5CmNvbS5wbGV4YXBwLmFnZW50cy5HYXlBZHVsdEZpbG1zOi8vNDIxMjk2P2xhbmc9eG5zNApndWlkcjAK
DEBUG (runtime:814) - Found route matching /:/plugins/com.plexapp.agents.GEVI/messaging/function/X0FnZW50S2l0OkVyYXNlTWV0YWRhdGE_/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoxCmRpY3QKMgpzNQpNb3ZpZXMxMAptZWRpYV90eXBlczQ5CmNvbS5wbGV4YXBwLmFnZW50cy5HYXlBZHVsdEZpbG1zOi8vNDIxMjk2P2xhbmc9eG5zNApndWlkcjAK
DEBUG (runtime:88) - Sending packed state data (104 bytes)
DEBUG (runtime:924) - Response: [200] str, 16 bytes

**Comment by CodyBerenson** [comment]
@mhunter8 hope you are doing well.

You were very close.  Since the results lists the title of the movie as "Greek Holiday 2: Cruising Mykonos", we should replace the ":" with " - " (i.e. space dash space).  The correct title, which I just tested and matches perfectly therefore:

(BelAmi) - Greek Holiday 2 - Cruising Mykonos (2004).mp4

![image](https://user-images.githubusercontent.com/40373801/87862916-3779f800-c923-11ea-98a3-d2eb4328a6f6.png)

Take care,

Cody

**Comment by CodyBerenson** [comment]
p.s.  If GEVI is your go-to (it pretty much has become mine), there are a set of "Gay Erotic Video Index (GEVI) Tips and Considerations" in the ReadMe on the code page.  As you know, GEVI is an amazing indexing site, with just a few notable quirks.  

Cheers!

**Comment by JPH71** [comment]
You also had a spelling mistake in your title... Crusing instead cruising

And as Cody mentioned space dash space

Jason xx

**Comment by mhunter8** [comment]
Thanks Guys... I need to pay closer attention... sorry for bothering you needlessly... it was the spelling of "cruising" and it was staring me right in the f*ing face right there in the log... duh!  The : didn't seem to make a difference one way or another... but I'm on Linux.  GEVI - SEARCH:: Title Match: [False] Compare Title - Site Title "greekholiday2crusingmykonos - greekholiday2cruisingmykonos"  

crusing vs cruising - ugh!

**Comment by CodyBerenson** [comment]
@mhunter8 Yay!  Definitely not a bother.  Makes me happy to know folks are using the agents!  

I should also update the ReadMe to say:  In all cases, Jason should troubleshoot before Cody.  LOL.  For sure.

Enjoy your weekend.

**Comment by JPH71** [comment]
It was just there... Noticed it straight away... Usually I would have
gone... Renamed a movie... Ruffled up the code... Then have the 'oh fuck'
moment...

Jason xxxx
