### ISSUE TITLE
Fagalicious has updated their site and broken the Agent :(

### ISSUE THREAD

**Issue by CodyBerenson** [CodyBerenson/PGMA-Modernized#39]
The good folks at Fagalicious just updated the way their site does search, which has broken our agent.  Hang in there, while Dr. Jason performs the necessary surgery.

**Comment by j-ktz** [comment]
Thanks for the update!
GitHub <notifications@github.com> wrote:
“The good folks at Fagalicious just updated the way their site does search, which has broken our agent. Hang in there, while Dr. Jason performs the necessary surgery.”

**Comment by CodyBerenson** [comment]
@j-ktz:  anything for you big guy.

**Comment by j-ktz** [comment]
Haha. Hope you both are well! 🤗
GitHub <notifications@github.com> wrote:
“@j-ktz: anything for you big guy.”

**Comment by JPH71** [comment]
When I have sorted out fagalicious - i will get you to test a MAC
applescript that will be a backup for thumbor!

Hope you have being keeping well

Jason

**Comment by j-ktz** [comment]
Doing well here! Staying safe. Sounds good. I’ll be happy to test. 
GitHub <notifications@github.com> wrote:
“ When I have sorted out fagalicious - i will get you to test a MAC
 applescript that will be a backup for thumbor!
 
 Hope you have being keeping well
 
 Jason

**Comment by j-ktz** [comment]
Is this one still broken?

**Comment by CodyBerenson** [comment]
hi @j-ktz:  unfortunately, it is still broken.  Fagalicious has added a partially truncated search results list that then needs to be clicked into.  the fix is a level of complexity that is perplexing Jason.  

Not that you asked, but my workaround when there's only a match on Fagalicious and not on WayBig or Queer Click:  I check to see if there's a match on IAFD.  If so, I grab the poster from Fagalicious, name it poster.jpg and put it in a folder with the properly IAFD named file.  As long as you have "IAFD" checked as an agent and "Local Media Assets (movies)" also checked as an agent, plex will use the metadata from IAFD and the poster from the folder.

Take care.

**Comment by j-ktz** [comment]
That's a good tip. Thanks!!!
GitHub <notifications@github.com> wrote:
“hi @j-ktz: unfortunately, it is still broken. Fagalicious has added a partially truncated search results list that then needs to be clicked into. the fix is a level of complexity that is perplexing Jason.

Not that you asked, but my workaround when there's only a match on Fagalicious and not on WayBig or Queer Click: I check to see if there's a match on IAFD. If so, I grab the poster from Fagalicious, name it poster.jpg and put it in a folder with the properly IAFD named file. As long as you have "IAFD" checked as an agent and "Local Media Assets (movies)" also checked as an agent, plex will use the metadata from IAFD and the poster from the folder.

Take care.”

**Comment by j-ktz** [comment]
Hey Boys! 

It looks like Fagalicious updated their search functionality again. Not search if this will help or hurt our broken agent but wanted to make you both aware! @CodyBerenson @JPH71

**Comment by CodyBerenson** [comment]
Hey @j-ktz!

You're right!  no more google like search results.  @JPH71 check it out!

**Comment by JPH71** [comment]
The cheeky Heifers!

I will look into it next - just finished updating GayHotMovies and
AVEntertainments

Will bundle everything together when I send them, if I make a change to
either iafd.py or genfunctions.py, I would like them all updated in all the
agents. In case of any error one is singing from the same hymn sheet...

Jason xxx

**Comment by CodyBerenson** [comment]
@JPH71 

I tested a title on Fagalicious with the old code currently in our repository.  It didn't match, but I'm not sure why.  The search result should have returned the match (it did when i manually used the search result in the log), but the log said 0.  

it would be EXCELLENT if Fagalicious could work again.  Can we treat this as the priority?

[com.plexapp.agents.Fagalicious.log](https://github.com/CodyBerenson/PGMA-Modernized/files/6016268/com.plexapp.agents.Fagalicious.log)

**Comment by j-ktz** [comment]
Darn I was hoping it would work but hadn’t tried yet. Thanks for testing @CodyBerenson  @JPH71 if you can get Fagalicous working again I owe you a big kiss!

**Comment by CodyBerenson** [comment]
That incentive from you will help reel in his focus.  Nothing I say does any good.  ;)

**Comment by j-ktz** [comment]
@CodyBerenson LOL. Doubt that. You can get one too. :)

**Comment by JPH71** [comment]
Biatch! You both begging for a left arse cheek slap! Not that I am
complaining .... LOL

**Comment by JPH71** [comment]
I am starting on it now!

**Comment by JPH71** [comment]
Could one of you two send me a log... so i can identify where it is failing
on the old code... and I can implement a fix quicker!

**Comment by CodyBerenson** [comment]
LOL.  Its three entries up in this thread.

https://github.com/CodyBerenson/PGMA-Modernized/issues/39#issuecomment-782742385

**Comment by CodyBerenson** [comment]
@j-ktz see what I mean about focus?    LOL LOL LOL

**Comment by j-ktz** [comment]
@JPH71 @CodyBerenson Sorry not sorry. 😂

**Comment by CodyBerenson** [comment]
Me thinks someone is snockered again.  Speaking of, its already after 4...why am I drinking water?  Be right back.  LOL.

**Comment by j-ktz** [comment]
PGMA after dark. 🌙 Cheers boys!

**Comment by JPH71** [comment]
Nearly done with fagalicious!

its 03h15 here and it's oh so quiet! Brilliant

Jason

**Comment by CodyBerenson** [comment]
take your time. im watching the Spain ESC 2021 selection (TVE in the USA is delayed).  Per usual, it will be crap. But better than the UK. 

question:  spending so much time in Belgium, do you align yourself with them in the ESC?  Their entries are typically quite good vs Spain or the UK. lol

**Comment by JPH71** [comment]
I got pissed off with Eurovision and the effing Russians and their
sycophants in the east ... it has become a regional; thing... people no
longer vote for the best song but from the closest country...

After the middle east shenanigans where we helped with the invasion and
bitch slapping of Sadam - we never get any votes in the UK... I can
understand that as Eurovision has always been used as a protest vote... but
the fucking Russians??????

If I can hear myself whistling to the song by the end of it or I feel like
dancing when I hear it ... it gets my vote!

I dont have TV here.... I download all my TV to watch on Plex so
dont usually watch TV Stations....

**Comment by CodyBerenson** [comment]
@JPH71 
Here's the problem with that argument.  And I hear that argument from so many Spaniard and UK folks.  Western countries nearly always win.  Azerbaijan won a few years back, and the Ukraine (very much an anti Russia vote).  But by and large, Western countries win.  They have an entire algorythm for which countries participate in each semi finals and which countries are allowed to vote in each semi final.  They've done as best they can to negate the vote for your neighbor syndrome.  And, now that popular vote is as equal to the jury vote in the final, the best song really does tend to win.

So, bitter Brits, the UK songs suck.  Just own it.  LOL LOL LOL LOL.  

xoxoxoxoxoxo

**Comment by CodyBerenson** [comment]
@j-ktz @JPH71 

I tested the fix to Fagalicious.  20 out of 20 test titles matched perfectly.  I'm going to push it to the repository so we can close this long standing bug once and for all!  

@j-ktz Jason is waiting for his long and very sloppy kiss.  Pay up!

**Comment by JPH71** [comment]
The British entries are always so shit and the guys they pick to represent
have faces begging for a slap... I hear they changed the voting system a
year or two back... But I had lost interest by then especially as my two
friends who were ESV philes had lived up north...
