### ISSUE TITLE
User reports 503 errors with Fagalicious

### ISSUE THREAD

**Issue by CodyBerenson** [CodyBerenson/PGMA-Modernized#4]
A user has reported receiving 503 errors with Fagalicious.  

Testing is now underway.

**Comment by CodyBerenson** [comment]
@jph71 @j-ktz   Please use this issue for the Fagalicious issue.   The other issue has been closed.  

I used Fagalicious yesterday and it worked fine.  I will do some testing now.

**Comment by CodyBerenson** [comment]
@jph71 @j-ktz

Hi folks, I just did a quick test, using the most recent blog entry and it worked fine.

![image](https://user-images.githubusercontent.com/40373801/78705975-50aee980-78dc-11ea-8fa3-974948b365d6.png)

i will do larger testing, including taking the latest code from the master repository.

**Comment by CodyBerenson** [comment]
@jph71 @j-ktz

I just grabbed and installed the latest fagalicious code.  I threw 14 test files at it.  13 matched perfectly fine.  The one that didn't was a scenario I've never run up against, the entire name of the title within quotes...if i were worried about it, i'd play around with it to see what i could do to get it to match:

(TheBigCMen) - “Insanely Hot Afternoon 3 Way Cory & Jared Tag Sexy Pup Tanner Hyde” (2020).mp4

So at this point, i'm not sure what to say to either of you...other than it sucks to be you.  lol.  Working fine on this end.

**Comment by CodyBerenson** [comment]
@jph71 

Hey buttercup.  Any progress with Fagalicious?

**Comment by JPH71** [comment]
Haven't gotten round to it yet..
In another 3 hours when I finish work
👍

**Comment by CodyBerenson** [comment]
I wonder if your priorities are askew.....  LOL

**Comment by JPH71** [comment]
Today they are definitely askew... I am not in the mood to do anywork

**Comment by CodyBerenson** [comment]
@JPH71 good to hear that fagalicious is working for you.  Let's keep this issue open a bit more, see if you have any additional observations.

@j-ktz you mentioned in a post somewhere that you may be having issues.  If so please detail and we'll see if we can help.

**Comment by CodyBerenson** [comment]
@JPH71 I updated the ReadMe on the main Repository page to include a walkthru of GEVI.  Whenever your free time allows, please take a look.  Feedback welcome as always.  :)

**Comment by JPH71** [comment]
Cool I will look at the readme and download it on to my machine - so that
next time I do an update - it doesn't get overwritten

Cheers

Jason

**Comment by j-ktz** [comment]
@CodyBerenson One that I remember was (Corbin Fisher) - Chandler fucks three loads out of Aiden (2012), which pulled in dates and the URL but no summary or cover photo. Very strange...

**Comment by CodyBerenson** [comment]
Hi @j-ktz 

I just tested that scene and got the same exact result, so its definitely the agent and not you.  @JPH71 can you look into what's going on in Fagalicious for:
(Corbin Fisher) - Chandler fucks three loads out of Aiden (2012)

Alternatively, that same scene is on WayBig which matches fine:
(CorbinFisher) - Aiden’s Triple Load III (2012)

**Comment by JPH71** [comment]
I will look into that...
Have you guys any other blog which we can scrape?

**Comment by CodyBerenson** [comment]
@jph71 
I have a handful of scenes that won't match on all three blog sites....i'll do some googling and see if i can find anymore.

xoxo

**Comment by JPH71** [comment]
I think we can close this issue - as we found out as per your suggestion
that if we used a VPN pointed to another country that it works
@nyethi - any ideas on geoBlocking???

**Comment by CodyBerenson** [comment]
Resolved.  Code works as expected.

**Comment by nyethi** [comment]
Sorry for reopening - just went through backlog of Github notifications and saw a mention. @JPH71 You could use a simple HTTP/SOCKS proxy to force a specific location for http requests. I use this service (https://getproxylist.com) in my personal projects (magic metadata)

**Comment by JPH71** [comment]
@nyethi - many thanks Adrian, do you have any example code - I dont have
much experience with web stuff, I sort of stumbled into scrapping...
how does this work in principle, so I can figure out how to write the code
around it...

cheers

Jason

**Comment by nyethi** [comment]
no, not for python. you might be able to find a copy (it's circulating around the web somewhere, i had it at one point, u gotta look hard) of the complete Plex Python documentation and it should have something about proxies IIRC. I would look, but it's 4 AM here and I need to go to bed :)

**Comment by JPH71** [comment]
@nyethi
Here it is
I hope this is the one
Cheers

Hope you had a good sleep!

**Comment by nyethi** [comment]
No methods for proxying using Plex built in libraries. I would use urllib2 as that does have support for http proxies

**Comment by JPH71** [comment]
Could you give me an example of how to do it... I don't come from a web
programming background...

**Comment by nyethi** [comment]
Of course, I could probably get to it tomorrow if I can find the time. What part of the code is blocked by geo blocking?

**Comment by JPH71** [comment]
it seems to be the area on line 198!
Fagalicious refuses to work from the UK, is haphazard in the US but works
if I set my VPN to Mexico???

Cheers

Jason
