### ISSUE TITLE
Web Developers Help Urgently Needed, Please!

### ISSUE THREAD

**Issue by CodyBerenson** [CodyBerenson/PGMA-Modernized#40]
@acvigue @mrplow254

Friends, and any web developers, we need your help.  The change that Fagalicious has made to its search has perplexed us. This is from Jason....any help/pointers you could offer would be really, really appreciated!  Thanks so much in advance!

From @jph71:

this is the full xPath to the list of titles

1. //div[@class="page-wrap"]/div[@class="page-main"]/div[@class="entry-content"]/div[@class="wgs_wrapper"]/div[@id="___gcse_1"]/div[@class="gsc-control-cse gsc-control-cse-en"]/div[@class="gsc-control-wrapper-cse"]/div[@class="gsc-results-wrapper-nooverlay gsc-results-wrapper-visible"]/div[@class="gsc-wrapper"]/div[@class="gsc-resultsbox-visible"]/div[@class="gsc-resultsRoot gsc-tabData gsc-tabdActive"]/div[@class="gsc-results gsc-webResult"]/div[@class="gsc-expansionArea"]/div[@class="gsc-webResult gsc-result"]/div[@class="gs-webResult gs-result"]/div[@class="gsc-thumbnail-inside"]/div[@class="gs-title"]/a[@class="gs-title"]

I shorten it to this

2. //a[@class="gs-title"]

which returns nothing in the code but in Chrome developer when one inspects the page it returns the correct number of search results

however, when scraping it returns up to this point

3. //div[@class="page-wrap"]/div[@class="page-main"]/div[@class="entry-content"]/div[@class="wgs_wrapper"]/div[@id="___gcse_1"]

That is to say if I run 

            titleList = html.xpath('any of the three xpath')
            self.log('SEARCH:: Result Page No: %s, Titles Found %s', pageNumber, len(titleList))

            for title in titleList:
                # Site Entry : Composed of Studio, then Scene Title separated by a Colon
                try:
                    siteEntry = title.xpath('//text()')
                    siteEntry = ''.join(siteEntry)
                    siteEntry = siteEntry.split(":")
                    self.log('SEARCH:: Site Entry: %s', siteEntry)
                except:
                    continue

I get some output for strings 1 and 3, but nothing for 2...

it's like the page has not loaded anything by the time i get to the for loop and the length of the titleList is ZERO for string 2.
For strings 1 and 3, it seems that whatever is returned is not what is displayed in the web browser if you click on the following link:

https://fagalicious.com/search_gcse/?q=dennis+calvin+and+jordan+flip+fuck+in+seancody

Could you post this on our repository and ask for help?

Cheers

Jason

**Comment by CodyBerenson** [comment]
@acvigue

Hope you are well.  We could really use your help and advanced expertise here, please!!!  This agent is dead-in-the-water.  Could you offer any suggestions?

**Comment by codeanator** [comment]
Hi...
Began to work on a fork of your agent and found out that Fagalicious is relying on Google Custom Search Engine (CSE) (see : https://developers.google.com/custom-search).
The search is made through a JS and the results are loaded asynchronously. Therefore, the HTML DOM loaded by the agent doesn't contain any result.

I would require extended work to reverse engineer the CSE workflow and see if we can mimic it but I am not optimistic.
Also I looked for a "legacy" search option (for example, the search function of Wordpress) but none seems to exist.

**Comment by JPH71** [comment]
darned it - no bloody wonder it wasn't working.
Thanks for taking the time to look into this, your help is much appreciated.

KR

Jason

**Comment by codeanator** [comment]
It seems there is a couple of ways of doing it using Python.
See : https://medium.com/@rifaislamet1509/solved-scraping-all-of-data-from-google-cse-using-python-13d3e6f12413
Or : https://github.com/rakshith36/Google-Custom-Search-Python
Or : https://stackoverflow.com/questions/37083058/programmatically-searching-google-in-python-using-custom-search

**Comment by CodyBerenson** [comment]
@codeanator Thank you so much for sharing!  Wanted to let you know that it is truly, truly appreciated....it may take a bit to hear back as @JPH71 is traveling and has very limited availability at the moment.  

Merci bien!

**Comment by JPH71** [comment]
Thank you so much for this information!!!!!

**Comment by JPH71** [comment]
@CodeAnator
I looked at the 3 links you posted and so far had no scripting luck

I generated an API key and setup the custom search engine - when I tried
this I got the following error

*{
  "error": {
    "code": 400,
    "message": "API key not valid. Please pass a valid API key.",
    "errors": [
      {
        "message": "API key not valid. Please pass a valid API key.",
        "domain": "global",
        "reason": "badRequest"
      }
    ],
    "status": "INVALID_ARGUMENT"
  }
}*


I read somewhere that the API key is not needed - so i tried building
the searchy string as

https://cse.google.com/cse?cx=cfdc79a11d23b7755&q=john+thomas

the cx value is what I created from here https://cse.google.com/cse/all

When I clicked on the link it returned the results from the
fagalicious website, but when I try to scrape this I am back
at square one as this return is also asynchronous. Using the following xpath
'//div[@class="gs-title"]/a[@class="gs-title"]/text()[contains(.,": ")]'

picks the correct returns when in inspect mode... but in the code
nothing is returned due to the asynchronicity...

Could you look at the code and point me in the right direction - code attached

https://drive.google.com/file/d/16rcoUaZ-v_iHl2rhDmucI_2sIwZ2OoxP/view?usp=sharing


Kind Regards

Jason

**Comment by CodyBerenson** [comment]
Fagalicious has eliminated their search results page. This issue has been resolved.
