### ISSUE TITLE
GEVI won't match title

### ISSUE THREAD

**Issue by j-ktz** [CodyBerenson/PGMA-Modernized#41]
Trying to match the [following file](https://www.gayeroticvideoindex.com/E/4024.html) and it fails, log attached.

File name: **(Out In Public) - Public Anal Sex by the River! (2014)**

[com.plexapp.agents.GEVI.log](https://github.com/CodyBerenson/PGMA-Modernized/files/5012405/com.plexapp.agents.GEVI.log)

**Comment by JPH71** [comment]
I will check it out

**Comment by JPH71** [comment]
Is this a scene or a movie..
As GEVI does not do scenes...

**Comment by j-ktz** [comment]
It’s a scene 
GitHub <notifications@github.com> wrote:
“ Is this a scene or a movie..
 As GEVI does not do scenes...

**Comment by JPH71** [comment]
It won't match with GEVI... Even when you go on the website and put the
title in the search box it returns nowt.
Check for it on Waybig and queer click and change its title to what you
find on either of those sites, then match it using the gay adult scenes
agent.
👍

**Comment by CodyBerenson** [comment]
Hi @j-ktz, hope you're safe and staying out of trouble.  :)

I've ensured the ReadMe and FAQ reflect this challenge accordingly.  

Take care of yourself.  Happy Porn-ing.

**Comment by j-ktz** [comment]
@JPH71 @CodyBerenson Thanks for checking into it. Was I doing something wrong with the agent? Not sure why it wouldn't work. [Here's another example](https://www.gayeroticvideoindex.com/E/139849.html) I just tried that doesn't match.

Filename: **(Colby Knox) - Club Kid Kinda Night (2015)**

[com.plexapp.agents.GEVI.log](https://github.com/CodyBerenson/PGMA-Modernized/files/5016044/com.plexapp.agents.GEVI.log)

**Comment by CodyBerenson** [comment]
@j-ktz:  The GEVI site, and therefore the agent, doesn't allow you to search for Scenes...only for Films.  You can get to online scenes (GEVI calls them episodes)  thru searching for performers or production companies, but to search for a scene itself, GEVI doesn't allow.  

![image](https://user-images.githubusercontent.com/40373801/89194877-f82fe600-d575-11ea-9ea8-ae7c7116fcc2.png)

In your examples, "Club Kid Kinda Night" and "Public Anal Sex by the River!", these are scenes (i.e.onlie episodes), not the titles of movies so it is impossible to search directly to the episode.  In fact, "club Kid Kinda Night" isn't even an episode listed under Colby Knox, so you must have found it via the performer.  

![image](https://user-images.githubusercontent.com/40373801/89194997-201f4980-d576-11ea-838b-0bbada7dc779.png)

Sorry, my friend, it just isn't possible with GEVI.  You can either paste the metadata summaries, etc. manually, or if you'd like, I can show you how to manually create .xml and use a different agent to read the .xml to update the metadata in plex.

**Comment by j-ktz** [comment]
Gotcha. Okay. Good to know. Thank you!!
GitHub <notifications@github.com> wrote:
“@j-ktz: The GEVI site, and therefore the agent, doesn't allow you to search for Scenes...only for Films. You can get to online scenes (GEVI calls them episodes) thru searching for performers or production companies, but to search for a scene itself, GEVI doesn't allow.”

[image]
“In your examples, "Club Kid Kinda Night" and "Public Anal Sex by the River!", these are scenes (i.e.onlie episodes), not the titles of movies so it is impossible to search directly to the episode. In fact, "club Kid Kinda Night" isn't even an episode listed under Colby Knox, so you must have found it via the performer.”

[image]
“Sorry, my friend, it just isn't possible with GEVI. You can either paste the metadata summaries, etc. manually, or if you'd like, I can show you how to manually create .xml and use a different agent to read the .xml to update the metadata in plex.”
