### ISSUE TITLE
First Time User, Unable to Match Scenes

### ISSUE THREAD

**Issue by jocklover** [CodyBerenson/PGMA-Modernized#42]
HI
Thanks for making this great tool!
I am struggling to get "Gay Adult Scenes" to match my videos. I have all 4 options selected, except Local Media Assets.
I am mostly at the testing level of setup. I was able to get a match to a movie using "Gay Adult Films" (although I actually need to match specific scenes), so it appears that info, photos, etc. are pulling down.
However, I cannot get the scenes to match. I have been working with a Sean Cody scene with Jayce & Jaymus.  I have located it on three of the sites: https://www.waybig.com/blog/2019/04/05/sean-cody-jaymus-fucks-jayce/; https://fagalicious.com/sean-cody-jaymus-jayce-bareback-gay-porn/; and https://www.queerclick.com/qc/2019/04/sean-cody-jayce-and-jaymus.php.
I am using the naming format "(Studio) - Name (year)". I have tried both seancody & Sean Cody for the studio. I have tried naming my file to match each title (Jaymus f's Jayce; Jaymus f's Jayce bareback; and Jacyce and Jaymus). And am using the year 2019.
It also appears that the console shows Plex is calling out to each site to request information, but am not experienced enough to be able to debug the console messages.

Do you have any suggestions for what I should check or try to troubleshoot this? THANKS!

**Comment by jocklover** [comment]
Kept fiddling with it. Not sure if turning off Fagalicius was the key (based on the separate issue). Or if something else helped.

**Comment by JPH71** [comment]
Hi JockLover

Fagalicious changed its search mechanism recently, I am still trying to
sort it out - so disable it for the moment.

I am looking into creating another scene agent to help.

Sean Cody: Jaymus Fucks Jayce

Should be set to (Sean Cody) - Jaymus Fucks Jayce (2019) and waybig must be
checked.... if you ever come across a colon ":" in the title replace this
with space dash space

Glad to hear that you sorted it out

If you know of any website that gives scene details including poster art -
let me know!

Jason x

**Comment by jocklover** [comment]
I thought I had this figured out - I have now been able to make 2 videos match. But have tested another 6 that I cannot get to match. It doesn't seem to be so much related to the actual working of this agent, as it is my understanding of Plex.

Here is an example that I have that isn't matching up: https://www.waybig.com/blog/2020/03/09/seancody-rowan-returns-fucks-blake/ and it is titled (Sean Cody) - Rowan Returns And Fucks Blake (2020).mp4

Are there any tips for the Plex platform to help get the matches? When the videos first show up in the Library they show w/out the () & the year. I have tried Unmatching them (which can help get the real file name to show), Fixing the Match, Refreshing Metadata.

**Comment by CodyBerenson** [comment]
@jocklover 

Welcome friend!  

You will need to match WayBig exactly.  Note that (and believe me it is inconsistent) there is no space in SeanCody.  When you correct your title it will match perfectly....I just tested it with a space (didn't match) and without a space (matched):

(SeanCody) - Rowan Returns And Fucks Blake (2020).mp4

![image](https://user-images.githubusercontent.com/40373801/89738422-56613b00-da46-11ea-8ad6-f3d4ca735c1b.png)

Here's how I do it.  I drag the entire title, copy it, paste it into the file name, add a "(" at the beginning a ") - " in place of the colon and (YYYY) at the end.   That way, it doesn't matter how inconsistent WayBig treats a studio or if WayBig has typos in the title....the Plex Agent will match.  Just wait until you get to Men.com and see how many iterations of that studio name WayBig has!  

LOL.  Hope this helps.

**Comment by jocklover** [comment]
OMG!!! I have been spinning my wheels on that for hours! I had 2 matches occur w/ "Sean Cody" but it must have been pulling off of QueerClick or IAFD and I didn't realize it. Matches popping for most all of my videos I have tried. THANKS!!!

**Comment by CodyBerenson** [comment]
@jocklover 

Glad this helped!  And that was the point I was trying to make.  WayBig has a mix of SeanCody and Sean Cody and maybe even SeanCody! and you have to match it exactly as is, title by title.  So, I'm not at all saying all WayBig has to be SeanCody (no space)...it truly depends on the very specific individual title.  

FYI, if its ever important to you, you know know exactly the source by looking at the "Tagline" in the properties for the file (ignore the foreign language, my test system is still set from when we were testing language translation functionality a bit ago).

![image](https://user-images.githubusercontent.com/40373801/89740474-ea3b0300-da56-11ea-90bf-21508d2d1b85.png)
