### ISSUE TITLE
Ease mandatory Date of Release for Films

### ISSUE THREAD

**Issue by joshallen13** [CodyBerenson/PGMA-Modernized#44]
I'm in awe of the amazing work you put into this. I've been waiting so long for something this good to come along, and here it is.

I do have a slight request/enhancement/unintended conflict resolve idea that I"m sure you have a reason for it being the way it is, but I've run into several instances in GEVI where the release date is unknown. Therefore, the scrape does not recognize the title, and GEVI is my go-to agent.

Is there the possibility you can alleviate the mandatory requirement for adding the Release Date (YYYY) for full titles using the GEVI agent? For the most part, I'm able to name my files correctly using the studio and the title as it correctly shows, but for my 2k+ titles, I am having to look up the release year for each one, and it is painstaking. 

Please provide some relief, if possible!

**Comment by JPH71** [comment]
Hi Josh

If there is no release year in GEVI, the agent is supposed to pick the date
provided in the file title.

The agent is quite strict file names should follow the following format

(Studio Name) - Film Title (Release Year).ext

If the filename does not follow this format the agent will refuse to
process.

If you do not know the year the film was released just set the release year
as 1900....

Give me examples of the filenames you have....

If you have a load of filenames with no year info - I can write a little
script for you to add (1900) to the end of the filename for you.

Kind Regards

Jason

**Comment by joshallen13** [comment]
Thanks for the quick reply!

It's not a whole lot, and I'm usually able to solve it by trying a few agents until one hits, so it's not a dead end. I'd just rather have uniformity with everything as I'm a perfectionist. 

I'm curious to know why the year is required on GEVI agent, when I've yet to see any conflicts under the Studio & Title hierarchy. Unless it's something to do with how Plex processes it, then I understand the limitations there. I guess my question points towards is the Year requirement a part of Plex's agent search, or is it a requirement written by the scraper?

**Comment by JPH71** [comment]
Hi Josh

I so understand the perfectionist comment and everything looking uniform...
For me I found it rather irritating to see some files in windows explorer
with YYYY and some without.  Thus, I trawl through the webisphere trying to
find the date a film was released before giving it to plex to match

The YYYY date is not a plex requirement but a scraper one - a hangover from
the time I was new to Python programming and handling Regex in relation to
optional matching.

I will talk to Cody in relation to this, as I would have to make the
changes uniform across all the 13..14 agents.... So bear with us

In the meantime use this piece of software https://www.advancedrenamer.com/
to add (1900) to all the files you have that have no date...I should have
thought of that beforehand...

Kind regards

Jason x

**Comment by joshallen13** [comment]
The YYYY date is not a plex requirement but a scraper one - a hangover from the time I was new to Python programming and handling Regex in relation to optional matching. I will talk to Cody in relation to this, as I would have to make the changes uniform across all the 13..14 agents.
