### ISSUE TITLE
IAFD won't match title

### ISSUE THREAD

**Issue by j-ktz** [CodyBerenson/PGMA-Modernized#45]
Trying to match (Str8Hell) - Martin and Boda - Raunchy Raw (2017) but can't seem to get it to match IAFD title. I've tried the following combinations:

(Str8hell.com) - Martin and Boda - Raunchy Raw (2017)
(Str8 hell) - Martin and Boda - Raunchy Raw (2017)
(Williams Higgins) - Martin and Boda - Raunchy Raw (2017)
(WilliamsHiggins.com) - Martin and Boda - Raunchy Raw (2017)

Any ideas?
[com.plexapp.agents.IAFD.log](https://github.com/CodyBerenson/PGMA-Modernized/files/5210581/com.plexapp.agents.IAFD.log)

**Comment by CodyBerenson** [comment]
Hi @j-ktz hope you're doing well.  

Interesting...good catch, doesn't match for me either.  Jason will have to take a look at it.  Not sure if it has something to do with the hyphen...I don't recall too many hyphens in IAFD titles.    

@jph71 what do you think?

**Comment by j-ktz** [comment]
@CodyBerenson That's what I was thinking too? I also tried an em dash at one point but no dice. I'm doing good!!! I hope you boys are too and staying safe :)

**Comment by JPH71** [comment]
Any of you have a log file...
IAFD is very pernickety for me at the moment - I have to log into a vpn for
it to work....
Just clear the log file and try and match the title. then send me the
logs....
I hope it's a good one so that we can sort it out and help for future
matching!


Jason
xxxxx

**Comment by CodyBerenson** [comment]
@JPH71 Here is a clean log

[com.plexapp.agents.IAFD.log](https://github.com/CodyBerenson/PGMA-Modernized/files/5212550/com.plexapp.agents.IAFD.log)

**Comment by CodyBerenson** [comment]
The update fixes this issue.  Typically, I'd do a lot more robust testing on updates to make sure nothing broke but I just don't have the time so I'll upload the corrected Agent to the master repository in about 3 minutes.

**Comment by CodyBerenson** [comment]
@j-ktz you should be good to go, dude.  Stay well.

**Comment by j-ktz** [comment]
Worked beautifully. Thanks for the quick fix!
GitHub <notifications@github.com> wrote:
“@j-ktz you should be good to go, dude. Stay well.”
