### ISSUE TITLE
IAFD won't match title

### ISSUE THREAD

**Issue by j-ktz** [CodyBerenson/PGMA-Modernized#47]
Hope you all are doing well and being safe! Here's another one I can't get to match: (Fuckermate) - Franklin Acevedo And Bastian Karim [Inch by Inch] (2018). I think it's the brackets throwing it off but it won't match without them either. Here's the IAFD link: http://www.iafd.com/title.rme/title=franklin+acevedo+and+bastian+karim+%5binch+by+inch%5d/year=2018/franklin-acevedo-and-bastian-karim-%5binch-by-inch%5d.htm

Logs attached. Any ideas boys?
[com.plexapp.agents.IAFD.log](https://github.com/CodyBerenson/PGMA-Modernized/files/5247358/com.plexapp.agents.IAFD.log)

**Comment by CodyBerenson** [comment]
Hi @j-ktz I get the same result, and have the same suspicion on the brackets.

@jph71 will have to look into...I'm not sure of his availability, as he's continent hopping.

Stay well!

**Comment by CodyBerenson** [comment]
@j-ktz 
Just occurred to me.  I'm not sure if you've yet installed our new agent, BestExclusivePorn.  This scene is blogged on that site and matches perfectly.  Two thoughts:
1) not sure why but this is a rare time where there's no poster art on the blog for this scene (in this case, no different than IAFD LOL)
2) the site doesn't include actors but @JPH71 has built in a workaround detailed in the ReadMe.  The agent will infer actors names from the the words in the filename, by looking for congruent sets of two capitalized words and then does a match against IAFD to see if its a valid actor that exist.  So, once in a while you have to tweak the case in the filename, as in this instance where the word "inch" was changed to lower case:

(FuckerMate) - Inch by inch Franklin Acevedo and Bastian Karim (2018)

Obviously we'll leave the IAFD bug open, but this may be a workaround for you in the interim.

Cheers,

Cody

**Comment by j-ktz** [comment]
@CodyBerenson Thanks! I didn't see the new agent. I'll give it a go. Also just another example of the IAFD bug with a different title: Sir Peter and Axel Brown [Summerend Lust] (2020)

**Comment by CodyBerenson** [comment]
@j-ktz 

Terrific, thanks!  More test cases help ensure the eventual fix works universally.

You're probably aware, that scene is blogged on WayBig:
(FUCKERMATE) - Sir Peter Fucks Axel Brown in ‘Summerend Lust’ (2020)

Your libraries are current to the minute.  Impressive.  :)

**Comment by j-ktz** [comment]
Yup! Sorry just modified by comment cause I saw it on Waybig, but so @JPH71 knows, another example is: Sir Peter and Axel Brown [Summerend Lust] (2020).

Yes, pretty up to date. It's quarantine. What else am I supposed to do? :-P

**Comment by CodyBerenson** [comment]
@j-ktz 
No apologies!  You've been an amazing tester/stakeholder.  Be safe.

**Comment by CodyBerenson** [comment]
@j-ktz

The world traveler took a moment to fix the IAFD bracket issue.  You seem to have special pull with him.  The master repository has been updated.

@JPH71

Thanks for addressing.  Both of the test cases work perfectly.  I will close the issue sometime tomorrow.

Stay safe.

Cody

**Comment by j-ktz** [comment]
Awesome! Thanks boys. @JPH71 is out here doing the lords work. 

On September 20, 2020, GitHub <notifications@github.com> wrote:
> @j-ktz <https://github.com/j-ktz>
>
> The world traveler took a moment to fix the IAFD bracket issue. You
> seem to have special pull with him. The master repository has been
> updated.
>
> @JPH71 <https://github.com/JPH71>
>
> Thanks for addressing. Both of the test cases work perfectly. I will

> close the issue sometime tomorrow.
>
> Stay safe.
>
> Cody
>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/CodyBerenson/PGMA-Modernized/issues/47#issuecomment-

695848887>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AOEY5RBCVXQFLEFWCAMIVBTSG2EGLANCNFSM4RSKDLOA>.

**Comment by CodyBerenson** [comment]
certainly would explain the frequency of “OH GOD!” in the dialog. and the deflowered morman boyz.

**Comment by JPH71** [comment]
he he - you guys are begging for smacked arses!
Got nowt to do at the moment...
And programming is a good stress reliever!

Jason
xxx
