### ISSUE TITLE
Unable to get Studio to populate or pull from file name

### ISSUE THREAD

**Issue by bkndc** [CodyBerenson/PGMA-Modernized#48]
I am unable to get (Studio) to show up or pull from the file name even after doing the Plex Dance and using the correct naming syntax for the particular Studio.  The Studio field doesn't even show up on the description of the movie as shown on the example screens in the WiKi.  Do the agents pull from the metadata at all or strictly use the file name?  What logs or screenshots can I provide which will help troubleshoot this issue?  I am using the standard "(Studio) - Movie Title (Year)"  naming convention.    FYI I have all my Movies in one \\Movies\directory would that have something to do with it?  Thank you.

**Comment by CodyBerenson** [comment]
Hi @bkndc 

I'm not sure I entirely understand what you're asking.  Are you saying you're able to match, it returns coverart and most metadata except for studio?  if so, skip #1-7 that follow.  If you're unable to get anything to match, follow #1-7.  I *think* you're asking the former, but just in case here's a step by step on setup.

Can you tell me a few more details.  What operating system is your Plex Media Server on?  Which agent(s) are you trying to use?  

When I was first starting to use similar agents, I found that once I got one title to match, that was 99.5% of the battle.  So, lets start with one title. 

Can you provide a couple screen shots:

1.  For the library you've established in the PMS, can you give me a screen shot of the bottom of the Advanced tab?  Here's mine so you know what you're looking for:

![image](https://user-images.githubusercontent.com/40373801/94068835-b6752c00-fdbd-11ea-90d3-7c7dca4099b0.png)

2.  Can you give me a screen shot of the agents that you selected?  Go into Advanced, Agents.  Here's mine so you can see what I mean:

![image](https://user-images.githubusercontent.com/40373801/94069121-166bd280-fdbe-11ea-911e-418f44b25979.png)

3.  For whichever agent you checked (e.g., GEVI (IAFD) in my screen shot), please click on the little gear and send me a screen shot of that.  Here's an example from mine:

![image](https://user-images.githubusercontent.com/40373801/94069458-a01ba000-fdbe-11ea-88bd-f0852d394bed.png)

4.  Please start with one film title in a directory all by itself.  For now, either create a new library that points to the directory for this movie, *or* move the other movies outside to a different directory (not a subdirectory).  It will just help with troubleshooting.

5.  For that one movie, please provide the exact filename that you're using, and which agent/website you believe it should match against (e.g. GEVI, AEBN, etc.).

6.  Once we verity your setup, then i'll point you to the logfiles that we might ask you to send....but first, lets focus on your setup.

7.  if you'd prefer to IM, my direct email is dakota.berenson@gmail.com

However, if you're saying that you get a match, cover art and some metadata but not all, I just need an example.  Can you:

A.  Give me the exact filename you're using.

B.  Tell me the exact match.  You can tell that by looking at the tagline in the metadata.  The agent will populate the match that it found.  Here's an example:

![image](https://user-images.githubusercontent.com/40373801/94070387-1bca1c80-fdc0-11ea-8a37-18a967c8025a.png)

C.  I'll test out from there.  

Cheers, and welcome to the community!

**Comment by CodyBerenson** [comment]
@bkndc 

Just realized I didn't answer your question on what the agents do.  The agents use the combination of (studio name) title and (YYYY) in the file name to identify an exact an exact match on an index.  Once the agent has confirmed that the title is an exact match, it populates metadata and images within Plex solely from two websites:  1.  the coverart (poster), and all pertinent movie info (including studio) comes from the matched website (e.g., AEBN); the actor's headshot images returned from IAFD.com, if there's a match.  i.e. if AEBN lists an actor as Rocco Steele, the AEBN agent that we've created will search IAFD for a match to Rocco Steele, which it will find, and populate his headshot in Plex.  So to answer your question, no, the agent does not use (studio) from the file name to populate the Studio metadata within Plex.

**Comment by bkndc** [comment]
If there is no match then the information is populated from the file name but the studio is not populated it ends up in the title and sort field minus the ().  Then you end up with the video title being shown in the library.  Unless I go through and batch a bunch of the movies and add the studio to the Plex meta data field.  Then at least the studio will show up on the screen and I can filter on studios.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by CodyBerenson** [comment]
HI @bkndc 

I've attempted to support your questions by detailing step-by-step explanations on how to use our agents, as well as asking you to provide specifics, which you have not.  The agents that we offer follow the following paradigm:

1.  you identify a specific target on an index site (e.g., GEVI) that you want metadata pulled from
2.  you name the file correctly using **both** (studio) - title (yyyy).ext **and** where studio, title and yyyy **match exactly the target on the GEVI specific site**
3.  our GEVI agent, via Plex's matching functionality, then matches the title against the site and retrieves the metadata.  
4.  when you need help because the title won't match, we ask that you provide specific details about 1, 2 and the log from 3.  

If you aren't willing to follow this paradigm, our agents, this repository, and anything else I could offer are of no use to you.  As you have already explored, there are plenty of tools that will scrape and populate metadata.  Ours are quite accurate, but require you to follow the paradigm.  

Stay healthy and safe.

Cheers,

Cody

**Comment by bkndc** [comment]
You are correct Cody.  And I should have provided the information you requested.  I will do that.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
