### ISSUE TITLE
Only Fans

### ISSUE THREAD

**Issue by JPH71** [CodyBerenson/PGMA-Modernized#5]
@j-ktz - if you have a site which gives artwork and summaries to only fans videos, ket me know and I will right an agent for it. As I haven't seen one yet, I haven't downloaded many of them. Which is a shame as their is quite good onlyfans contents!

**Comment by j-ktz** [comment]
Haven't found one yet but I'll keep a look out!

**Comment by CodyBerenson** [comment]
So, this doesn't help with Only Fans, but for studios in general that aren't blogged, WayBig has a studios/videos site which provides summaries but no cover artwork.  

For instance, there is very little blogged on WB, QC and F for Blake Mason....but, there are 678 videos on WayBig (only thing missing is no cover artwork)...

https://www.waybig.com/studios/105/blake-mason/

I'm NOT a fan of specific studio sites...they're updated too frequently and they break the Agent....but, down the road I could see utility for the tons of scenes that we all have that have no blog, anywhere....

....for the back of your mind for consideration.

**Comment by JPH71** [comment]
I had looked at the other parts of waybig before as I had a couple of
onlyfan videos - but didn't go further due to the lack of cover art
If you ever find a site that does some cover art - or may be we could sort
of take the actors pictures of IAFD and make a composite of the actors and
use that as cover art
@nyethi - do you think thumbor can do this??

**Comment by nyethi** [comment]
probably not, but python can use the PIL (now pillow) library to do image manipulation and i bet we could figure something out there.

**Comment by nyethi** [comment]
https://pypi.org/project/Pillow/2.1.0/

**Comment by JPH71** [comment]
@nyethi 
in relation to libraries that are not standard like pillow - where in the scrapper would we drop the libraries files so that one can include them in an agent.
I was wanting to write my image cropper code in python, but i couldn't include any none standard library in the code... which irritated me no end... I ended up writing the cropper in vbScript...
Jason

**Comment by JPH71** [comment]
> So, this doesn't help with Only Fans, but for studios in general that aren't blogged, WayBig has a studios/videos site which provides summaries but no cover artwork.
> 
> For instance, there is very little blogged on WB, QC and F for Blake Mason....but, there are 678 videos on WayBig (only thing missing is no cover artwork)...
> 
> https://www.waybig.com/studios/105/blake-mason/
> 
> I'm NOT a fan of specific studio sites...they're updated too frequently and they break the Agent....but, down the road I could see utility for the tons of scenes that we all have that have no blog, anywhere....
> 
> ....for the back of your mind for consideration.

@CodyBerenson 
Just took a look at the Blake Mason webside and they don't have any artwork either.... grrr.

**Comment by nyethi** [comment]
@JPH71 Make sure this is in Info.plist for the plugin
```
<key>PlexPluginCodePolicy</key>
<string>Elevated</string>
```

Then, place the library folder in <plugin_dir>/Contents/Libraries/Shared

Then use a basic import statement in __init__.py

**Comment by CodyBerenson** [comment]
@JPH71 
re: https://github.com/CodyBerenson/PGMA-Modernized/issues/5#issuecomment-616812419

I wasn't suggesting to create a Blake Mason or any other studio scraper.  I was suggesting that maybe we want to create a scraper that scrapes the WayBig Scenes (not the blog)...way down the road.  low low on the priority list.

**Comment by JPH71** [comment]
As usual I picked the wrong stick up...
I will start looking at the video section of way big

**Comment by CodyBerenson** [comment]
Now that Jason has created an IAFD agent, this is no longer needed.
