### ISSUE TITLE
Another title I can't get to match. 

### ISSUE THREAD

**Issue by joshallen13** [CodyBerenson/PGMA-Modernized#50]
Please describe the challenge:
I can't get this title ([Fuck 8 (Treasure Island)](https://www.gayeroticvideoindex.com/V/4/55214.html)) on GEVI to  match, and I think I know why, but you're the experts here. However, since there is no entry on IAFD it's my thoughts as to why it won't, and I searched high and low, but as you know TIM isn't on AEBN anymore. I tried to use the (TreasureIsland) after the title and without since the others in the series had no issues. I also tried another naming convention since It was on another of the sites ([GayHotMovies](https://www.gayhotmovies.com/video/354034/TIMFuck-Vol-8/?rewrite_title=x)), but I am not sure how to get the agent to point there (TIMFuck Vol. 8)

I've attached the GEVI log files but if you need another, let me know.
[com.plexapp.agents.GEVI.log.zip](https://github.com/CodyBerenson/PGMA-Modernized/files/5326784/com.plexapp.agents.GEVI.log.zip)

**Comment by CodyBerenson** [comment]
@jph71
Can you look into?  I've tested and am also unable to get this title to match with the GEVI agent.

@joshallen13 
In the meantime, the title does match fine using the GayHotMovies agent.  Do you have it selected?

![image](https://user-images.githubusercontent.com/40373801/95074461-a114d180-06dc-11eb-9064-8fe7d2da4210.png)

![image](https://user-images.githubusercontent.com/40373801/95074979-69f2f000-06dd-11eb-83ed-f73c8a56c630.png)

The title is also on GayDVDEmpire and matches using that agent as well.

**Comment by joshallen13** [comment]
I have all of them selected, but it won't match to it because I don't have it called that, it's named based on the GEVI agent. I've tried to match it based on that name, and the different year it has as well, but didn't prove successful. I wonder if the sort order for the agents has anything to do with the matching not happening. 

I got it to finally match on GayDVDEmpire in a test site after reordering and choosing the Agent Gay Adult Films instead of my usual Gay Adult.  I'm thinking the order definitely affected it and made sure they were above the IAFD checkbox and re-running. Instantly matched.

Thanks guys!

**Comment by CodyBerenson** [comment]
@joshallen13  
I'm going to reopen this because the bug you identified in GEVI does still need to be addressed.

Also, for performance, you may want to limit the number of agents you select to just those that you really regularly use.  I discussed that here  https://github.com/CodyBerenson/PGMA-Modernized/issues/49#issuecomment-703582926

**Comment by joshallen13** [comment]
Fair enough :) 

I'm still getting the hang of using Git. I'm using pornography to slowly teach myself how to code. LOL

**Comment by CodyBerenson** [comment]
Good morning @joshallen13 

Jason has made the corrective update to the GEVI agent to cull through a much larger set of results lists.  A common name such as this film returns MANY pages of results lists from GEVI.  The film is found on page 35.  LOL.  Now the agent will cull through up to 50 pages of results to find a match.

I am uploading the fix to the master repository.  This issue will be closed tomorrow.  Take care!

**Comment by CodyBerenson** [comment]
@joshallen13 
I forgot to mention, I tested the fix with the entire series of TIM Fuck movies on GEVI.  100% match.  Cheers.

**Comment by JPH71** [comment]
Brilliant!
