### ISSUE TITLE
IAFD has updated their site to HTTPS and broke the agent

### ISSUE THREAD

**Issue by j-ktz** [CodyBerenson/PGMA-Modernized#52]
I'm trying to get [(GayRoom.com) - Intimate Rubdown (2013)](https://www.iafd.com/title.rme/title=intimate+rubdown/year=2013/intimate-rubdown.htm) to match with IAFD with no luck.

I've tried:
(GayRoom.com) - Intimate Rubdown (2013)
(Gay Room) - Intimate Rubdown (2013)
(GayRoom) - Intimate Rubdown (2013)
(Massage Bait) - Intimate Rubdown (2013)
(MassageBait) - Intimate Rubdown (2013)
(MassageBait.com) - Intimate Rubdown (2013)

@CodyBerenson Should I be matching studio or distributer? I've tried all combos here, but I would think studio?

Here's an example of a log.

Any ideas boys?

[com.plexapp.agents.IAFD.log](https://github.com/CodyBerenson/PGMA-Modernized/files/5329823/com.plexapp.agents.IAFD.log)

**Comment by CodyBerenson** [comment]
@j-ktz 

How are you our little angel?  We miss you.

with IAFD, match the studio.  so, (MassageBait.com) - Intimate Rubdown (2013) would be the winner....but I can't get it to match either.  *sometimes* you can use the AKA, but not if there's any punctuation in it.

so, if this title were working, you could match either:

(MassageBait.com) - Intimate Rubdown (2013)  *or*
(MassageBait.com) - An Intimate Rubdown (2013) (using the AKA) *or*
(MassageBait.com) - A Hard Rub (2013)

@jph71 can you trouble shoot this one also?

**Comment by j-ktz** [comment]
@CodyBerenson Whoever said I'm an angel LIED. Hope you boys are well and safe! I feel bad, I only chat when I have a problem, haha. I'm always around on social (johnkatez) if you want to say hi 👋 

Thanks for troubleshooting @JPH71!

**Comment by j-ktz** [comment]
@CodyBerenson @JPH71 Wonder if it's an agent issue? Men on Edge usually matches perfectly and neither [(Men on Edge) - Men On Edge 35106 (2014)](https://www.iafd.com/title.rme/title=men+on+edge+35106/year=2014/men-on-edge-35106.htm) or [(Men on Edge) - Men On Edge 26527 (2012)](https://www.iafd.com/title.rme/title=men+on+edge+26527/year=2012/men-on-edge-26527.htm) will match for me.

**Comment by CodyBerenson** [comment]
@j-ktz agreed, MOE usually matches perfectly as well; and agreed, neither will match for me.  

@jph71 here are two more non IAFD matches for you to look into, please.

**Comment by CodyBerenson** [comment]
@j-ktz @jph71

Nothing seems to be matching on IAFD at the moment.  Perhaps IAFD changed something that broke the agent....?

**Comment by CodyBerenson** [comment]
@j-ktz @jph71

Even the javascript tool i use to scrape IAFD isn't working.  They must have pushed some sort of change that broke us.  :(

**Comment by CodyBerenson** [comment]
I figured it out.  They tweeted today that they've changed to https.  

![image](https://user-images.githubusercontent.com/40373801/95156982-d1548280-0765-11eb-8184-a23be7538c5d.png)

so, you can either wait for Jason to push new code, or if you are daring, you can make the fix yourself and until the new code comes along.

in the IAFD.bundle/Contents/Code folder, make a copy of the __init__.py file...just in case.

Open the IAFD __init__.py file in notepad and make an update:

change: 
BASE_URL = 'http://www.iafd.com'
to
BASE_URL = 'https://www.iafd.com'

save it.  kill your PMS.  restart it.  and IAFD works again.

**Comment by JPH71** [comment]
Made the changes - the change had broke all the agents which used IAFD to
source the cast list and pictures

**Comment by JPH71** [comment]
@j-ktz,  @CodyBerenson <https://github.com/CodyBerenson>

(MassageBait) - Intimate Rubdown (2013)  - should work - you can leave out
the .com in the studios.....

I have fixed IAFD - so this should now match.
Happy testing guys

Jason

**Comment by CodyBerenson** [comment]
@j-ktz 
Uploading the updated agents to the master repository now.  I'll close this issue tomorrow.

p.s.  I don't do social media anymore....quit cold turkey on the-day-after-election-day 2016.  Hopefully, in 4 weeks if the country course-corrects, I can reactivate facebook, etc.  in the meantime, jason told me you are in fact an angel-prude.  nice try.

**Comment by JPH71** [comment]
What is an angel prude... Is this an Americanism that I am as yet unaware
off???😆

**Comment by j-ktz** [comment]
@JPH71 Yes, it is. And I'm no angel! 😆

**Comment by JPH71** [comment]
Lol... Being angelic is boring!!

**Comment by j-ktz** [comment]
Glad you agree! Join the dark side @JPH71.

**Comment by JPH71** [comment]
Being a paid up member since I was 13!
