### ISSUE TITLE
Small edit needed for Error on Usage Guide Wiki

### ISSUE THREAD

**Issue by joshallen13** [CodyBerenson/PGMA-Modernized#53]
**Hi gentlemen!** 

I noticed an error when going through and showing a friend how to add metadata and wanted to point it out to you for a future update so as to not confuse others.

images/PlexGayMetadataAgents-InstallationandUsageGuide.pdf

Page 16 
![Screen Shot 2020-11-16 at 9 42 30 PM](https://user-images.githubusercontent.com/33143443/99339705-a4ab8480-2854-11eb-936c-6d99f7dfa2ef.jpg)

Notice the second line has a "--" after Distributor instead of just the singular "-" as is noted under Studio. I assume the extra dash results in the match not being successful here.

**Comment by JPH71** [comment]
Thank you for this...
That was a good spot!

**Comment by CodyBerenson** [comment]
@joshallen13 

Greetings, hope this finds you and yours safe and well.  Really appreciate the feedback.  The guide was written either two or three martinis in...so, please don't hesitate to find more typos.  LOL!

Cheers,

Cody
