### ISSUE TITLE
Organization Tips 

### ISSUE THREAD

**Issue by j-ktz** [CodyBerenson/PGMA-Modernized#59]
Hey Gents,

No bug but just seeking advice. How do you organize your libraries? Right now I have two libraries, one for Porn and one for Amateur/Fan Sites. Then I make Collections for Studios, Stars and Themes I like. Curious of how you all have yours set up?

**Comment by joshallen13** [comment]
I have three libraries for adult themed content. I found it to be easiest this way to make sure the agents pull from GEVI for full films, and the scenes I am not as anal on making sure it matches. Feel free to add me to share servers so you can peruse my setup: joshallen13.

I did find a python script on here that can auto create collections based on Studio, and I adjusted it for each studio I wanted to create a collection for, and ran it for each one. [Plex-Utills](https://github.com/jkirkcaldy/plex-utills)
![Screen Shot 2021-02-05 at 12 42 53 AM](https://user-images.githubusercontent.com/33143443/106995297-929efb00-674c-11eb-9672-2b83be9b0fbc.jpg)

Let me know if you need any help with that python script, or if you have any other questions. :)

**Comment by j-ktz** [comment]
Thanks Josh! I'm thinking about splitting up my scenes and full films. Also still unsure of how to organize Fan Site content. I added you to see your setup. I've manually done the Studio Collections and made poster artwork for my faves, but the Python script sees way smarter. Going to check it out. Thanks for sharing!

**Comment by JPH71** [comment]
I organise mine in this way

For Studios with a large presence, like Falcon, Raging Stallion, Hot House,
Treasure Island Media - I have separate libraries

For all the other smaller Studios which I do not have many films I have
arranged alphabetically into 3 broad groups Studio Names Starting with # -
E, F-P and Q-Z

As I collect and one of these smaller studios film count goes over a number
say 80... it gets its own library.


For video clips I do the same, So I would have for Tim Tales, FuckerMate
etc...

Then I have for the other ones

and finally for those I can't match - in this library OnlyFans tend to go.
here I do not always bother to name them as (studio) - Title (Year)


Hope this helps


Jason

**Comment by j-ktz** [comment]
It is helpful. Thanks Jason!!

**Comment by j-ktz** [comment]
@joshallen13 Could you attached your modified python script for Studio Collections?

**Comment by joshallen13** [comment]
It won't let me attach the script, but here's the modified code below for Treasure Island as a Studio. Make sure you update the config file with your correct Plex library info and token. What I did was just create a new script for each studio I wanted to create and save individually. I'm sure there is a quicker way to do that, but at least I can have it handy for when I need to re-run to add new content to the collections. The Readme file is pretty easy to follow with install instructions. I'm a beginner to using python scripts and it was a good teaching tool. Let me know if you need help there.

`#!/usr/bin/env python3
from collections import defaultdict
from plexapi.server import PlexServer
from configparser import ConfigParser

#Read config.ini file
config_object = ConfigParser()
config_object.read("config.ini")
server = config_object["PLEXSERVER"]

baseurl = (server["PLEX_URL"])
token = (server["TOKEN"])
films = (server["FILMSLIBRARY"])
plex = PlexServer(baseurl, token)
movies_section = plex.library.section(films)
added = movies_section.search(sort='titleSort')

for movie in added:
    try:
        if "Treasure Island Media" in movie.studio:
            movie.addCollection('Treasure Island Media')
            print('%s (%s)' % (movie.title, movie.studio))
    # Skip movie if there is no studio info
    except TypeError:
        continue

**Comment by j-ktz** [comment]
@joshallen13 You rock. Thank you!!!
