### ISSUE TITLE
Plex Collection Covers

### ISSUE THREAD

**Issue by j-ktz** [CodyBerenson/PGMA-Modernized#6]
Does anyone make custom Collection covers for actors or studios? For example, if I have an Arad Winwin collection it would be nice to have a formatted poster as opposed to a collage of scene posters. Same idea for studios with Studio logo. I can make some but just checking to see if either of you have already done it?

**Comment by CodyBerenson** [comment]
@j-ktz I sure haven't. In a pinch I've created a movie poster where I couldn't find one ANYWHERE on the net....but it was rudimentary.  I'm not particularly artistically inclined.

**Comment by j-ktz** [comment]
I bit the bullet and did some covers for studios and actors that I have a lot of. Feel free to close this if you want @CodyBerenson

**Comment by CodyBerenson** [comment]
Hi @j-ktz 

Will do.  Thanks!
