### ISSUE TITLE
Coming soon:  Enhancements to PGMA-Modernized Agents

### ISSUE THREAD

**Issue by CodyBerenson** [CodyBerenson/PGMA-Modernized#62]
We have begun to rollout enhancements to our Agents.  @JPH71 Jason is introducing the following enhancements to functionality:

1. Directors: getting info from IAFD including photos. Fixing a long term error on GEVI, which stopped them being set.
2. Cast: Photo, AKA Names or Roles in films. Agents get this now by one operational request. If the film is found it gets all the actors and Roles will be indicated. If the Agent has extra Cast members who are not listed as part of the film by IAFD OR if the film is not found on IAFD then these cast members are searched for individually and marked with a red tick. This is influenced by whether a movie is a compilation or not.
3. Summary now has a legend at top indicating, the status of the cast and whether the film is on IAFD or not
4. Film naming structure: one can now add the IAFD studio to the filename if needed (Studio[;IAFD Studio]) - Title (Year).ext
5. Collections: The final installment is that all parts of the file name are added to a collection. This includes: 
- Studio Name - Not IAFD Studio 
- All Parts of the Title delimited by " - " upto and including the final part if it ends with a series number. 
- Cast Members 
- Directors 
- Country of Production

This illustrates the cast enhancement.  If a match is made to IAFD and IAFD has a role, it will return it.  Otherwise, a legend is provided for the nature of the match (or not) made to IAFD:

![image](https://user-images.githubusercontent.com/40373801/108717372-35949a80-74eb-11eb-8d43-33d1f2f21489.png)

The enhancements will roll out in any new Agents or as existing Agents get updated.

**Comment by j-ktz** [comment]
This is EPIC! 🙌

On February 22, 2021, GitHub <notifications@github.com> wrote:
> We have begun to rollout enhancements to our Agents. @JPH71
> <https://github.com/JPH71> Jason is introducing the following
> enhancements to functionality:
>
> 1. Directors: getting info from IAFD including photos. Fixing a long

>    term error on GEVI, which stopped them being set.
> 2. Cast: Photo, AKA Names or Roles in films. Agents get this now by
>    one operational request. If the film is found it gets all the
>    actors and Roles will be indicated. If the Agent has extra Cast
>    members who are not listed as part of the film by IAFD OR if the
>    film is not found on IAFD then these cast members are searched for

>    individually and marked with a red tick. This is influenced by
>    whether a movie is a compilation or not.
> 3. Summary now has a legend at top indicating, the status of the cast

>    and whether the film is on IAFD or not
> 4. Film naming structure: one can now add the IAFD studio to the
>    filename if needed (Studio[;IAFD Studio]) - Title (Year).ext
> 5. Collections: The final installment is that all parts of the file
>    name are added to a collection. This includes:
>
>  *  a. Studio Name - Not IAFD Studio
>  *  b. All Parts of the Title delimited by " - " upto and including
>     the final part if it ends with a series number.
>  *  c. Cast Members
>  *  d. Directors
>  *  e. Country of Production
>
> This illustrates the cast enhancement. If a match is made to IAFD and

> IAFD has a role, it will return it. Otherwise, a legend is provided
> for the nature of the match (or not) made to IAFD:
>
>
>

> The enhancements will roll out in any new Agents or as existing Agents

> get updated.
>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/CodyBerenson/PGMA-Modernized/issues/62>, or
unsubscribe <https://github.com/notifications/unsubscribe-
auth/AOEY5REYXTYEXDCGF5YG7NDTAJOVVANCNFSM4YAR7QKA>.

**Comment by joca879** [comment]
Spectacular! Great improvement.
Keep it going :)

**Comment by CodyBerenson** [comment]
Status update:

These have been done:

1. AdultFilmDatabase.bundle
2. AEBNiii.bundle
3. AVEntertainments.bundle
4. BestExclusivePorn.bundle
5. CDUniverse.bundle
6. Fagalicious.bundle
7. GayDVDEmpire.bundle
8. GayFetishandBDSM.bundle
9. GayHotMovies.bundle
10. GayMovie.bundle
11. GayWorld.bundle
12. GEVI.bundle
13. WolffVideo.bundle

Queued in backlog:

1. GayRado.bundle
2. HomoActive.bundle
3. IAFD.bundle
4. nymMedia.bundle
5. QueerClick.bundle
6. RadVideo.bundle
7. WayBig.bundle

**Comment by CodyBerenson** [comment]
Correction.  The BestExclusivePorn.bundle did not function and had to be reverted to the 2/21/2021 code.  

Status update:

These have been done:

    AdultFilmDatabase.bundle
    AEBNiii.bundle
    AVEntertainments.bundle
    
    CDUniverse.bundle
    Fagalicious.bundle
    GayDVDEmpire.bundle
    GayFetishandBDSM.bundle
    GayHotMovies.bundle
    GayMovie.bundle
    GayWorld.bundle
    GEVI.bundle
    WolffVideo.bundle

Queued in backlog:

1.     BestExclusivePorn.bundle
2.     GayRado.bundle
3.     HomoActive.bundle
4.     IAFD.bundle
5.     nymMedia.bundle
6.     QueerClick.bundle
7.     RadVideo.bundle
8.     WayBig.bundle

**Comment by CodyBerenson** [comment]
Updated:
Queued in backlog:

1. GayRado.bundle
2. HomoActive.bundle
3. IAFD.bundle
4. nymMedia.bundle
