### ISSUE TITLE
Fagalicious agent converts case of title on matching

### ISSUE THREAD

**Issue by j-ktz** [CodyBerenson/PGMA-Modernized#64]
Hey Boys,

I've noticed that when I match with the Fagalicious agent, **it'll change the case of the first letter after a "**. Here's three examples. Confirmed that the the letters are capitalized on Fagalicious itself and the filenames. It's an easy fix (I just change the case in Plex), but still annoying. Possible to fix?

<img width="562" alt="screenshot 2021-02-24 at 9 26 16 PM" src="https://user-images.githubusercontent.com/59346628/109093968-4578ce00-76e7-11eb-9b8a-af61e24c2257.png">
<img width="701" alt="screenshot 2021-02-24 at 9 25 19 PM" src="https://user-images.githubusercontent.com/59346628/109093971-46116480-76e7-11eb-8483-2596d21981a0.png">

**Comment by JPH71** [comment]
@j-ktz Issue Fixed, thanks for noticing that! with Cody for testing
