### ISSUE TITLE
Update options to "Create Collection based on Film Series"

### ISSUE THREAD

**Issue by CodyBerenson** [CodyBerenson/PGMA-Modernized#67]
> @JPH71 @joshallen13 @j-ktz
> 
> Here is the draft updates to the guide re: Collections.
> 
> [Collections.pdf](https://github.com/CodyBerenson/PGMA-Modernized/files/6051496/Collections.pdf)
> 
> I'm not a Collections user. Please review/provide any feedback.

My one comment would be the mention of "Creating a Collection based on Film Title." Is there an easier way to say that without having to explain it as is currently done below the picture? Perhaps, "Create Collection based on Film Series" or the like? When saying Film Title it sounds like you would create a collection based on a word within the title... unless that is the function and I'm not clearly interpreting the use case.

_Originally posted by @joshallen13 in https://github.com/CodyBerenson/PGMA-Modernized/issues/65#issuecomment-786952339_

**Comment by JPH71** [comment]
That was the comment - I couldn't seem to find afterwards....
When I put the option in for the legend - I will do this too...

Jason

**Comment by CodyBerenson** [comment]
@JPH71 This change has been made to the 4 Scenes agents.  I'll push momentarily.

This issue will remain open until the Films agents are updated.

**Comment by CodyBerenson** [comment]
Forgot the screenshot.

![image](https://user-images.githubusercontent.com/40373801/109554554-6011c500-7aa2-11eb-83d8-97bd65a6049c.png)

**Comment by JPH71** [comment]
Correct!
