### ISSUE TITLE
Move Cast Legend to the bottom of the description

### ISSUE THREAD

**Issue by CodyBerenson** [CodyBerenson/PGMA-Modernized#68]
<img width="597" alt="screenshot 2021-02-26 at 9 12 41 PM" src="https://user-images.githubusercontent.com/59346628/109372413-66702900-7877-11eb-8e52-5c1ee0f0a8da.png">
This is SUPER nit-picky but is it possible to move the Roles legend to the bottom of the summary? Otherwise, you have to click Read More, to see the first line of the Summary because the legend takes up all the space. Imo, I think the scene/movie summary is more helpful since the legend is the same every time. Not a priority.

@CodyBerenson In the Roles documentation it states you can put both Studio names ((Studio;IAFDStudio) - Title (Year).ext.) but can you also do this with scene names? For example, what if the scene name is different on IAFD than WayBig, but you wanna use WayBig for the poster art and description but IAFD for roles and cast... possible?

_Originally posted by @j-ktz in https://github.com/CodyBerenson/PGMA-Modernized/issues/65#issuecomment-786986080_

**Comment by JPH71** [comment]
It's simple, I will make it an option whether to prefix or suffix it...

When I started this legend malarkey - plex offered more space to the
summary...

This changed late January and now one has a ridiculous small amount....

I am off to bed now - my eyes feel like they are spinning in
opposite directions in their sockets!

**Comment by CodyBerenson** [comment]
@JPH71 This option works for the four Scenes agents.  I"ll push them now.  

Leaving this issue open until the Films agents are updated.

Thanks!

**Comment by CodyBerenson** [comment]
Forgot to include the screen shot

![image](https://user-images.githubusercontent.com/40373801/109554408-2d67cc80-7aa2-11eb-9b61-ce051914f0fd.png)

**Comment by JPH71** [comment]
Yes, it will be standard for the film agents when I send them to you,
It is already in place for the Scene Agents!
