### ISSUE TITLE
Fagalicious doesn't seem able to pull in the posters

### ISSUE THREAD

**Issue by CodyBerenson** [CodyBerenson/PGMA-Modernized#69]
These are now matching but Fagalicious doesn't seem able to pull in the posters. I've just been grabbing the URLs and using the image cropper in the meantime.

_Originally posted by @j-ktz in https://github.com/CodyBerenson/PGMA-Modernized/issues/66#issuecomment-786985848_

**Comment by CodyBerenson** [comment]
I just tested the five most recent Fagalicious blog titles.  3 pulled in posters fine, 2 did not.  Rather, they pulled in the next-in-line image as the poster.  

![image](https://user-images.githubusercontent.com/40373801/109374933-d934d080-7886-11eb-92b4-5d8f550d0a90.png)

**Comment by JPH71** [comment]
@CodyBerenson  - it's thumbor....for one reason or another... maybe it's
being accessed too much tonight... an idea would be to use a VPN and see if
it works

2021-02-26 21:00:34,892 (7f4f3892c700) :  INFO (sandbox:19) - Fagalicious
 -
------------------------------------------------------------------------------
2021-02-26 21:00:34,899 (7f4f3892c700) :  DEBUG (networking:143) -
Requesting '
https://fagalicious.com/wp-content/uploads/2021/02/Sir-Peter-Alexis-Grande-Lucas-Entertainment-1.jpg
'
2021-02-26 21:00:35,273 (7f4f3892c700) :  DEBUG (networking:175) - Not
caching '
https://fagalicious.com/wp-content/uploads/2021/02/Sir-Peter-Alexis-Grande-Lucas-Entertainment-1.jpg'
(content type 'image/jpeg' not cacheable in Agent plug-ins)
2021-02-26 21:00:35,274 (7f4f3892c700) :  INFO (sandbox:19) - Fagalicious
 - AGNT  :: Poster Found: Width (800) x Height (1,565); URL:
https://fagalicious.com/wp-content/uploads/2021/02/Sir-Peter-Alexis-Grande-Lucas-Entertainment-1.jpg
2021-02-26 21:00:35,274 (7f4f3892c700) :  INFO (sandbox:19) - Fagalicious
 - AGNT  :: Crop Required: Poster: Actual (w800 x h1,565), Desired (w800 x
h1,200), % Dx = w[0.00%] x h[23.32%]
2021-02-26 21:00:35,275 (7f4f3892c700) :  INFO (sandbox:19) - Fagalicious
 - AGNT  :: Using Thumbor to crop image to: 800 x 1,200
2021-02-26 21:00:35,276 (7f4f3892c700) :  ERROR (sandbox:19) - Fagalicious
- AGNT  ::* Error Thumbor Failed to Crop Image to: 800 x 1,200*
2021-02-26 21:00:35,276 (7f4f3892c700) :  ERROR (sandbox:19) - Fagalicious
- UPDATE:: Error getting Poster: local variable 'picContent' referenced
before assignment

**Comment by JPH71** [comment]
send me the links to the 2 that did not work as expected and i will check
the xpath to see how it reacts to their web page...

oK off to bed

Jason

**Comment by CodyBerenson** [comment]
I've disconnected from my VPN.  No change.  I reconnected to a Spain VPN.  no change. 

here are the two that aren't working:
https://fagalicious.com/falcon-studios-jimmy-west-devin-trez-born-to-porn/
https://fagalicious.com/raging-stallion-max-konnor-isaac-x-scrum/

When I crop the image directly inline using thumbor, it works fine:  http://35.232.232.183:8888/unsafe/0x0:800x1200/https://fagalicious.com/wp-content/uploads/2021/02/Devin-Trez-Jimmy-West-Born-To-Porn-Falcon-Studios-1a.jpg?x77389

**Comment by CodyBerenson** [comment]
By the way, the two images that the Agent did return which are not the poster art, were still cropped by thumbor.  I don't believe the log is accurately capturing the errors.

**Comment by JPH71** [comment]
I have enhanced the log...

Jason
