### ISSUE TITLE
Caffeine to help?

### ISSUE THREAD

**Issue by j-ktz** [CodyBerenson/PGMA-Modernized#70]
Not an issue but I'd love to help contribute! @CodyBerenson @JPH71 you should set up a https://www.buymeacoffee.com or something similar? This repo has been life changing and I ask for a lot and report a lot of bugs and I just want to show my appreciation! :)

**Comment by JPH71** [comment]
I think it may be a good idea to talk to @CodyBerenson on this one especially in regards to Thumbor, for which he paid for out of his own pocket and which we all use and I don't think it is right that he should shoulder this alone.....
I try my best to pay him back with all the agent work... but that is like a two-edged sword ... as he also has to test them.....

**Comment by j-ktz** [comment]
@CodyBerenson @JPH71 Totally in debt to both of you for all of your hard work and dedication. Set up a way for us to donate/contribute Cody!
