### ISSUE TITLE
Discussion - Plex-Meta-Manager

### ISSUE THREAD

**Issue by j-ktz** [CodyBerenson/PGMA-Modernized#72]
Hey Boys!

I've recently found and fell in love with [Plex-Meta-Manager.](https://github.com/meisnate12/Plex-Meta-Manager) I have it running in Docker every night at 3AM and makes collections based on a Movies.yml code (auto generated Genre, Studio, Trakt, IMDB, etc. Collections). It's GREAT. So it got be thinking of I could retrofit for my XXX libraries, and I can!

I did some basic studio collections and it worked. For example, I can have it run at 3AM with my Movies.yml code and it'll find any scene/movie that's has studio = seancody, sean cody, seancody.com and add it to the Sean Cody collection. This saves me so much time for manually tagging scenes, which is what I was doing before. It could work for Genres, Stars, etc. You can even add in Summaries and Poster art for Collections. What Jason is doing with IAFD Collections is already phenomenal but this could be a great addition too!

Just getting started but happy to share my code and posters for studios and let you guys know how to modify for your own collections. Interested? 

Also @CodyBerenson is it possible to have a Discussions tab for the Repo? This isn't really an issue but didn't know where else to post. :)

**Comment by CodyBerenson** [comment]
@j-ktz Discussions now enabled.  Thanks for the suggestion.
