### ISSUE TITLE
New Waybig Version -Wait for Cody to put into Repository after testing

### ISSUE THREAD

**Issue by JPH71** [CodyBerenson/PGMA-Modernized#8]
@CodyBerenson 
Found out today that waybig is also allergic to '&' in titles
And found out that waybig sometimes lists the studio name in different formats for example
Next Door Ebony can also be found as NextDoorEbony and NextDoor Ebony, so i made some changes to the code.

here is the latest bundle to test
[WayBig.bundle.zip](https://github.com/CodyBerenson/PGMA-Modernized/files/4463585/WayBig.bundle.zip)

**Comment by CodyBerenson** [comment]
@JPH71 
I thought you and the rest of Europe are on Easter weekend lockdown....now you're giving me work to do?  

Here's what I'm gonna do.  Sans specific test cases, I'm about to drop 60 Corbin Fisher files to match against WayBig.  I'll test and make sure nothing is broken....

I can't say that any of the issues you describe have ever caused me problems personally....  however, you seem to be giving a more robust solution, so i'm in.

p.s.  have you noticed that there are new folks trying out the Agents???  👍

**Comment by CodyBerenson** [comment]
Pushing the update now.  I'll close this thread.

**Comment by CodyBerenson** [comment]
@JPH71 Update successful.  Closing thread.

**Comment by JPH71** [comment]
yes I noticed, its brilliant!
