### ISSUE TITLE
GayDVDEmpire creates "Bio" and "Interview" actors

### ISSUE THREAD

**Issue by CodyBerenson** [CodyBerenson/PGMA-Modernized#81]
Hi @jph71

@joca879 reports that when GayDVDEmpire includes (bio) next to a cast member in the cast list, the agent creates a cast member called "Bio"

https://www.gaydvdempire.com/2602813/cade-has-a-big-fat-dick-gay-porn-movies.html?qs=Cade%20Has%20A%20Big%20Fat%20Dick

(Jake Jaxson Presents) - Cade Has A Big Fat Dick (2019)

![image](https://user-images.githubusercontent.com/40373801/110868190-23aa4a00-8296-11eb-9394-05ccaec3338a.png)

Would you mind taking a look?

**Comment by JPH71** [comment]
Corrected!

**Comment by CodyBerenson** [comment]
@jph71 I just noticed, while the agent correctly identified by Director, it included him as a cast.

![image](https://user-images.githubusercontent.com/40373801/110868693-07f37380-8297-11eb-8f26-4c925c446152.png)

**Comment by JPH71** [comment]
darned it ... i will check it out!
give me 10

**Comment by CodyBerenson** [comment]
we might frighten patrons away if we start including Chi Chi la Rue's photo amongst the cast.......

**Comment by JPH71** [comment]
The new xpath i use //a[@class="PerformerName" and @label="Performers - detail"] sorts this out
so its good to go - Jake Jaxson has "Directors - Detail" - so is not picked up

**Comment by joca879** [comment]
thanks guys for the corrections, you are awesome :)

**Comment by JPH71** [comment]
LOL - chi chi

**Comment by CodyBerenson** [comment]
so, none of this as a cast member?

![image](https://user-images.githubusercontent.com/40373801/110869253-0d9d8900-8298-11eb-9ddf-bce3dc3c1d7c.png)

you suck

**Comment by JPH71** [comment]
Just so you can see the internals
[image: image.png]

the path is now
***@***.***="PerformerName" and @label="Performers - detail"]/text()

**Comment by joca879** [comment]
it's the truth ... practically I didn't even have time to see the post, it already appeared with the situation resolved :)
@JPH71 you are a machine!

**Comment by JPH71** [comment]
She must have had to start somewhere!

**Comment by CodyBerenson** [comment]
Yes, that fixed it.  I'll post the fix.

**Comment by JPH71** [comment]
I am on a roll today, Lindo!

**Comment by JPH71** [comment]
It really helps when everyone helps - as the agents get a lot more titles
thrown against them and more pairs of eyes to spot errors....
Jason!

**Comment by joca879** [comment]
Glad to help :)

**Comment by JPH71** [comment]
You are Welcome!
