### ISSUE TITLE
Unable to fetch meta data from Gay Scenes (WayBig.com)

### ISSUE THREAD

**Issue by vampirelayer** [CodyBerenson/PGMA-Modernized#84]
First of all, let me thank you for writing this amazing set of plugins! I have 1Tb worth of videos to organise and your work has certainly helped!

I did encounter an issue recently with the Gay Scenes agents. Hope you can shed some light. I'm a novice programmer myself so I'm comfortable going into log files :)

My video file name is `(Men) - Adam Ramzi, Alex Mecum, Julian Knowles And Kurtis Wolfe In ‘Dangerous Days’ Part 3 At Men.com (2017)`, copied directly from the blog entry:

`https://www.waybig.com/blog/2017/06/19/adam-ramzi-alex-mecum-julian-knowles-and-kurtis-wolfe-in-dangerous-days-part-3-at-men-com/`

The first agent I was going to use is for `WayBig.com`

No matter what I do - `unmatch`, `fix match`, `refresh metadata`, I will never get to fetch any meta data. :( Wondering where I went wrong?

Digging into `com.plexapp.agents.WayBig.log` this is what I see:

![image](https://user-images.githubusercontent.com/81353722/112444928-8963ff00-8d89-11eb-8422-fb05361311d7.png)

**Comment by CodyBerenson** [comment]
@vampirelayer Welcome to the community!

There is a quirk that some of the blogs temporarily undertook.  Waybig, for example, circa 2016-2017, started titling their entries with "at Studio" at the end of the entry.  You're close on the naming of your file....you just need to kill the "at Studio" at the end of the entry.  I had thought this was covered in the documentation but it is not....thanks for pointing out this quirk so I can update the documentation!  

![image](https://user-images.githubusercontent.com/40373801/112461498-57757d00-8d36-11eb-8963-831cf9872c9e.png)

However, having said that, I've tested this title properly named and it doesn't match.   @jph71 Can you take a look?  Neither naming convention works for me.  

(Men.com) - Adam Ramzi, Alex Mecum, Julian Knowles and Kurtis Wolfe in ‘Dangerous Days’ Part 3 (2017).mp4
(Men) - Adam Ramzi, Alex Mecum, Julian Knowles and Kurtis Wolfe in ‘Dangerous Days’ Part 3 (2017).mp4

@vampirelayer  p.s.  if you don't want to wait for the resolution, this title is also on Fagalicious.com and matches perfectly with the Fagalicious agent.  At any rate, there will be a resolution.  Cheers, and welcome again!

**Comment by vampirelayer** [comment]
It's nice to be part of this community!

I have tested with `Fagalicious.com` and still could not make it work.

File name is `(Men) - Adam Ramzi and Kurtis Wolfe fuck Alex Mecum and Julian Knowles in “Dangerous Days, Part 3” (2017).mp4`, matching this blog entry exactly at `https://fagalicious.com/men-com-adam-ramzi-kurtis-wolfe-fuck-alex-mecum-julian-knowles-dangerous-days-part-3/`.

This time, the log looks a bit different, reporting a `HTTP 503 Service is Unavailable` error, even though when I paste the same search query `https://fagalicious.com/search/adam+ramzi+and+kurtis+wolfe+fuck+alex+mecum+and+ju` into Safari it takes me to the results page as expected.

![image](https://user-images.githubusercontent.com/81353722/112486950-4fa9ed00-8db7-11eb-9db2-1f49d668a6f7.png)

**Comment by CodyBerenson** [comment]
@vampirelayer before I started using a VPN, I used to get similar errors for fagalicious.  We considered/concluded that fagalicious may perceive a DOS attack so We built in a delay timer for Fagalicious as an option that you may want to consider....

![image](https://user-images.githubusercontent.com/40373801/112514718-f9638c80-8d6b-11eb-94de-591de484d97f.png)

and, as I mentioned, if you use a VPN you may consider reconnecting; if you aren't using a VPN, you may consider using one.

**Comment by JPH71** [comment]
hI @Xtian

I will look into this and get back to you - could you send me the log
file... I like the screen shot but I could have done with an extra bit of
width :-)!

Jason

**Comment by CodyBerenson** [comment]
@JPH71 

here it is.  

[com.plexapp.agents.WayBig.log](https://github.com/CodyBerenson/PGMA-Modernized/files/6211808/com.plexapp.agents.WayBig.log)

@vampirelayer 

no action needed on your part yet.

**Comment by CodyBerenson** [comment]
@vampirelayer Jason has fixed the issue, its been tested, and the updated code has been pushed to the repository.  Please download and install the updates, kill and restart your PMS, and give it a go.  

Thanks again for reaching out, its terrific to have a new voice in the community!  

Cheers!

**Comment by vampirelayer** [comment]
This is working now!
There are a few more issues I'm seeing. Expect a few more bugs raised :) Happy to be the de facto tester here.

**Comment by JPH71** [comment]
BRILLIANT - all help is appreciated
