### ISSUE TITLE
Agents fail to return actors, regardless of IAFD

### ISSUE THREAD

**Issue by CodyBerenson** [CodyBerenson/PGMA-Modernized#86]
Beyond that IAFD is now blocking our agents requests, each agent should still return actors and/or directors if they are listed on the index (without headshots, since IAFD is blocked).  If/when IAFD is fixed, once can refresh metadata to obtain headshots, but until then actors and/or directors should be populated.

**Comment by JPH71** [comment]
Yes... That's what I am fixing, I inadvertently threw an error rather than
log an error when iafd failed... I remembered thinking at the time, I need
to change that... But ho him.. I went to bed and forgot .....

**Comment by CodyBerenson** [comment]
Hi folks, @jph71 has fixed this. For any folks that have done any matching in the past 4 days since IAFD blocked our scraping, you should be able to refresh metadata on those scenes and the actors should now be returned (without headshots because of the IAFD block).  

Jason continues to look for a resolution to the IAFD block.
