### ISSUE TITLE
Two titles won't match

### ISSUE THREAD

**Issue by j-ktz** [CodyBerenson/PGMA-Modernized#89]
Just noticed these two scenes won't match.

[(BelAmi) - Ariel Vanean and Bastian Dufy fuck each other raw (2017)
](https://fagalicious.com/belami-ariel-vanean-and-bastian-dufy-fuck-each-other-raw/)
[(Bel Ami Online) - Ariel Vanean Fucks Jeroen Mondrian In ‘Ariel Goes Scouting’ (2017)
](https://www.waybig.com/blog/2017/01/08/ariel-vanean-fucks-jeroen-mondrian-in-ariel-goes-scouting-at-bel-ami-online/)

[com.plexapp.agents.Fagalicious.log](https://github.com/CodyBerenson/PGMA-Modernized/files/6329236/com.plexapp.agents.Fagalicious.log)
[com.plexapp.agents.WayBig.log](https://github.com/CodyBerenson/PGMA-Modernized/files/6329237/com.plexapp.agents.WayBig.log)

**Comment by CodyBerenson** [comment]
@j-ktz um....have you considered that @JPH71 doesn't care for twinks and the non-matching is in fact by design?  

lol!

**Comment by j-ktz** [comment]
@CodyBerenson The thought did cross my mind. 😉  If anything they're twunks!

**Comment by CodyBerenson** [comment]
As i suspected.  @JPH71, ever the twink-naysayer, left an easter-egg in the log:

![image](https://user-images.githubusercontent.com/40373801/115119268-84076800-9f75-11eb-895c-4621a0a39232.png)

**Comment by JPH71** [comment]
You are both @j-ktz @CodyBerenson, begging for smacked arses, using my name
in vain.... but correct on the twinky shit... beurgh... give me a man with
hair in all the right places any day over a fucking twink....

**Comment by CodyBerenson** [comment]
@j-ktz Jason coded fixes for issue #92 and the Fagalicious portion of this issue.  The WayBig issue remains outstanding, so we'll leave this issue open.  Thanks for your patience.

**Comment by j-ktz** [comment]
@CodyBerenson No prob, boys! Thanks for all your hard work.

**Comment by JPH71** [comment]
@j-ktz - I will look at waybig tomorrow...

**Comment by j-ktz** [comment]
@j-ktz Ty. Sending you the biggest twink hung. 😆

**Comment by j-ktz** [comment]
Found another one that won't match with Fagalicious: [(Raging Stallion) - Sean Maygers fucks Beau Butler bareback in "Show Hard" (2021)](https://fagalicious.com/raging-stallion-sean-maygers-beau-butler-show-hard/)


[com.plexapp.agents.Fagalicious.log](https://github.com/CodyBerenson/PGMA-Modernized/files/6421964/com.plexapp.agents.Fagalicious.log)

**Comment by vampirelayer** [comment]
Works for Waybig.

**Comment by JPH71** [comment]
just finishing off GEVI, and then sorting WayBig...
Should be done this evening

**Comment by JPH71** [comment]
Hi Xtian

Let me know what error you get.
Empty the waybig log file then refresh the metadata for the clip, then
email the log file!

Jason x
