### ISSUE TITLE
Thinking of uploading an XML Agent, and JAVA IAFD Scraper

### ISSUE THREAD

**Issue by CodyBerenson** [CodyBerenson/PGMA-Modernized#9]
@JPH71
Happy Easter Buttercup!

I'm thinking about adding an XML Agent and JAVA IAFD Scraper that I use, along with a tutorial.  There are two occasions when I use these tools, important in my Porn Plex Arsenal:   

1.  In the rare rare instances when none of the scrapers can find a film, but the film is listed on IAFD.  The JAVA Scraper will scrape IAFD, including actors pictures (I can augment the metadata if I please)
2.  The film isn't on IAFD but metadata and posters are available and I wish to manually enter metadata myself into the JAVA Scraper

In either case, the Java Scraper creates the XML (actually, its a .NFO), creates a folder, and moves the film and the XML.  I just drop the movie poster in the folder, scan into plex, and match using the XML agent.   

What do you think?  It isn't codeset that we would maintain, I just thought it would offer a more complete solution? 

![image](https://user-images.githubusercontent.com/40373801/79070315-06928300-7ca3-11ea-8372-c8aa93256212.png)

**Comment by JPH71** [comment]
That's a brilliant idea.

I was going to ask you about scrapping IAFD as I had being thinking about
it.. but had not done so as the site did not seem to have the DVD front and
back covers.
It should be easy to do and may help you do things faster....As you would
only need to worry about the covers missing.....
Let me know what you think

By the way I have just finished scrapping RadVideo as I write you this
email. I will post it in a couple of minutes after I have amended
GayAdultFilms and GayAdult to incoporate it in their descriptions.

Jason

**Comment by CodyBerenson** [comment]
@JPH71 
Hello.  If you do create an IAFD scraper, please combine the "Scene Breakdowns" and Synopsis" into Plex's Summary...Synopsis first.  :)

**Comment by JPH71** [comment]
Ok, will do👍

**Comment by CodyBerenson** [comment]
Also, since IAFD doesn't discriminate between scenes and films, the IAFD agent maybe should be in all three of the buckets (GA, GAF, and GAS).  :)

**Comment by JPH71** [comment]
yes - i will set it to contribute to GA, GF, GS

**Comment by CodyBerenson** [comment]
#JPH71 I've created a new enhancement for the new IAFD Agent.  I can't remember where things stand with it.

**Comment by JPH71** [comment]
I will take a wee gander at it in a moment...

**Comment by CodyBerenson** [comment]
Now that Jason has created the IAFD scraper, this enhancement to the repository is no longer needed.  For the rare instances when a film or scene isn't indexed, one can manually index using Plex's built in functionality, including uploading a poster.
