### ISSUE TITLE
fagalicious agent 500 error

### ISSUE THREAD

**Issue by fivedays555** [CodyBerenson/PGMA-Modernized#90]
Thanks for making this great agent. 

Here just a small issue that sometimes, it adds an additional '+' at the end of the Fagalicious searching URL which causes a 500 error.

For studio matching or title matching, I think "fuzzywuzzy" is a pretty good python package to consider. 
I currently use it for a title match at 75 scores and a studio match at 88 scores. It gave me a pretty good result.
https://github.com/seatgeek/fuzzywuzzy

 >Thanks again.

> 2021-04-17 20:09:12,145 (46dec) :  INFO (logkit:16) - Fagalicious  - AGNT  :: Original Search Query        : Attila Kardos and Apolo Fire flip fuck bareback in 'Time for Action
> 2021-04-17 20:09:12,147 (46dec) :  INFO (logkit:16) - Fagalicious  - AGNT  :: Search Query:: String has none of these (‘|’)
> 2021-04-17 20:09:12,147 (46dec) :  INFO (logkit:16) - Fagalicious  - AGNT  :: Search Query:: String has none of these (,|-|‑|‒|–|—)
> 2021-04-17 20:09:12,147 (46dec) :  INFO (logkit:16) - Fagalicious  - AGNT  :: Search Query:: First character has none of these ('|"|`|“|”|‘|’)
> 2021-04-17 20:09:12,147 (46dec) :  INFO (logkit:16) - Fagalicious  - AGNT  :: Search Query:: Splitting at position [51]. Found one of these ('|"|`|“|”|‘|’)
> 2021-04-17 20:09:12,148 (46dec) :  INFO (logkit:16) - Fagalicious  - AGNT  :: Returned Search Query        : attila+kardos+and+apolo+fire+flip+fuck+bareback+

> 021-04-17 20:09:12,148 (46dec) :  INFO (logkit:16) - Fagalicious  - SEARCH:: Search Query: https://fagalicious.com/search/attila+kardos+and+apolo+fire+flip+fuck+bareback+
> 2021-04-17 20:09:12,174 (46dec) :  DEBUG (networking:143) - Requesting 'https://fagalicious.com/search/attila+kardos+and+apolo+fire+flip+fuck+bareback+'
> 2021-04-17 20:09:21,125 (46dec) :  ERROR (networking:196) - Error opening URL 'https://fagalicious.com/search/attila+kardos+and+apolo+fire+flip+fuck+bareback+'
> 2021-04-17 20:09:21,125 (46dec) :  ERROR (logkit:22) - Fagalicious - SEARCH:: Error: Search Query did not pull any results: HTTP Error 500: Internal Server Error
>

==============================================================================

> 2021-04-17 20:56:37,533 (4748c) :  DEBUG (networking:143) - Requesting 'https://fagalicious.com/search/attila+kardos+and+apolo+fire+flip+fuck+bareback'
> 2021-04-17 20:56:48,108 (4748c) :  INFO (logkit:16) - Fagalicious  - SEARCH:: No More Pages Found
> 2021-04-17 20:56:48,111 (4748c) :  INFO (logkit:16) - Fagalicious  - SEARCH:: Result Page No: 1, Titles Found 1

I am adding the following line for the Fagalicious class to prevent this.
class Fagalicious(Agent.Movies):
'''
'''
'''
        myString = myString if myString[-1] != '+' else myString[:-1]
'''
'''
'''
        return myString

**Comment by JPH71** [comment]
Cheers for letting me know... This will be an easy one to fix 👍

**Comment by JPH71** [comment]
The + is added because there is a trailing space - this issue is fixed in
the latest code - the + should not affect the search string results unless
at the time it went over 48 characters, but it's not aesthetically pleasing
either :-)
