### ISSUE TITLE
Series Collections are created even when the preference is unselected

### ISSUE THREAD

**Issue by CodyBerenson** [CodyBerenson/PGMA-Modernized#91]
@JPH71 not sure how prevalent across the agents this is, but it is definitely true of GEVI and AEBN.  Even though the "Create Collections based on Film Series" is unchecked, collections are still created for film series.  This has been happening for some time, unrelated with the recent updates.  

Cheers.

**Comment by JPH71** [comment]
I will look into this at the same time xxx
