### ISSUE TITLE
Title won't match (Fagalicious)

### ISSUE THREAD

**Issue by j-ktz** [CodyBerenson/PGMA-Modernized#92]
Not sure if this is a known issue or not, or why it won't match, but can't get this scene to match.

[(Next Door Taboo) - Brandon Anderson fucks Chris Blades bareback in “Get In Deeper Bro” (2021)](https://fagalicious.com/next-door-taboo-brandon-anderson-fucks-chris-blades-get-in-deeper-bro/)

[com.plexapp.agents.Fagalicious.log](https://github.com/CodyBerenson/PGMA-Modernized/files/6343084/com.plexapp.agents.Fagalicious.log)

**Comment by JPH71** [comment]
I will look at this 👍

**Comment by fivedays555** [comment]
fagalicious server is a bit strange. Sometimes, it does not like the '+' at the end of url; sometime, it does not like the F word or 'bareback' in the searching url. Easy fix will be remove those words in the searching query. ; )

**Comment by JPH71** [comment]
@fivedays55 - give me a list of titles with this issue and I will look in
to it the + at the end is easy to sort out - but the other issues with the
f words are a bit concerning...
Once I got 2 or 3 titles which this issue is affecting I will be able to
pin point the issue and provide a fix.

Keep well and thanks for your input :-)

Jason

**Comment by fivedays555** [comment]
@JPH71 Thanks for your reply and hard work. 
Yeah, I have noticed this problem when I do some manual search in fagalicious.com. 
For example, in "Next Door Taboo: Brandon Anderson fucks Chris Blades bareback in 'Get In Deeper Bro'" (https://fagalicious.com/search/Brandon+Anderson+Chris+Blades).
If you search "Brandon+Anderson+fuck+Chris+Blades", it will give a 500 error.
But if you search "Brandon+Anderson+fucks+Chris+Blades", it works fine.
If you add "bareback" at the end of the search query (Brandon+Anderson+fuck+Chris+Blades+bareback or Brandon+Anderson+fuck+Chris+Blades+bareback+in), it will give a 500 error.
However, if you search "Brandon+Anderson+fuck+Chris+Blades+bareback+in+“Get+In+Deeper+Bro”", it works perfectly fine.
However, "Brandon+Anderson+fuck+Chris+Blades+bareback+in+Get+In+Deeper+Bro" is not working, nor is "Brandon+Anderson+fuck+Chris+Blades+bareback+in+'Get+In+Deeper+Bro'"
So, not sure how fagalicious server handles the searching query. I think it is more likely their backend design's fault.

**Comment by fivedays555** [comment]
Here are some links for you to check:

2021-04-20 15:19:40,510 (b168) :  ERROR (networking:196) - Error opening URL 'https://fagalicious.com/search/kevin+daley+and+cameron+parks+fuck+angel+rivera'
2021-04-20 15:19:40,512 (b168) :  ERROR (logkit:22) - Fagalicious - SEARCH:: Error: Search Query did not pull any results: HTTP Error 500: Internal Server Error



2021-04-20 15:23:37,948 (bcf8) :  ERROR (networking:196) - Error opening URL 'https://fagalicious.com/search/kieran+%26+jayce+flip+fuck'
2021-04-20 15:23:37,948 (bcf8) :  ERROR (logkit:22) - Fagalicious - SEARCH:: Error: Search Query did not pull any results: HTTP Error 500: Internal Server Error



2021-04-20 15:24:23,776 (bd84) :  ERROR (networking:196) - Error opening URL 'https://fagalicious.com/search/kevin+texas+fucks+james+dawn+raw'
2021-04-20 15:24:23,776 (bd84) :  ERROR (logkit:22) - Fagalicious - SEARCH:: Error: Search Query did not pull any results: HTTP Error 500: Internal Server Error



2021-04-20 14:57:41,135 (b8c0) :  ERROR (networking:196) - Error opening URL 'https://fagalicious.com/search/kaleb+stryker+and+justin+matthews+flip+fuck+in'
2021-04-20 14:57:41,137 (b8c0) :  ERROR (logkit:22) - Fagalicious - SEARCH:: Error: Search Query did not pull any results: HTTP Error 500: Internal Server Error


2021-04-20 15:00:18,233 (ba10) :  ERROR (networking:196) - Error opening URL 'https://fagalicious.com/search/kaleb+stryker+and+nic+sahara+flip+fuck+in'
2021-04-20 15:00:18,233 (ba10) :  ERROR (logkit:22) - Fagalicious - SEARCH:: Error: Search Query did not pull any results: HTTP Error 500: Internal Server Error


2021-04-20 15:09:57,615 (bc08) :  ERROR (networking:196) - Error opening URL 'https://fagalicious.com/search/kennedy+%26+kellan+%28+flip+fuck'
2021-04-20 15:09:57,615 (bc08) :  ERROR (logkit:22) - Fagalicious - SEARCH:: Error: Search Query did not pull any results: HTTP Error 500: Internal Server Error


2021-04-20 15:11:19,407 (47dc) :  ERROR (networking:196) - Error opening URL 'https://fagalicious.com/search/kent+%26+kellan+%28fuck+buddies%29+%28'
2021-04-20 15:11:19,407 (47dc) :  ERROR (logkit:22) - Fagalicious - SEARCH:: Error: Search Query did not pull any results: HTTP Error 500: Internal Server Error

**Comment by JPH71** [comment]
@ fivedays555 - error fixed - fagalicious has reduced the length of the
search string further from 48 characters to 21...
This you can prove by typing in the search bar
*Cole Blue gets his ass* - 22 characters - returns a 500 error
but
*Cole Blue gets his as* - 21 char returns a result

Many thanks for pointing this out, and thanks for the kind words.

Once Cody has given it the go ahead - he will upload the latest to the
repository

Jason

**Comment by fivedays555** [comment]
@JPH71 Thanks for looking into this.

However, the following search query is working fine.......It passes 21 characters for sure.......fagalicious server is strange...

https://fagalicious.com/search/Cole+Blue+gets+his+spanked+and+plugged+by+Felix+Kamp+in

But if I add "ass" in, Hmm it stops working...

https://fagalicious.com/search/Cole+Blue+gets+his+ass+spanked+and+plugged+by+Felix+Kamp+in

**Comment by JPH71** [comment]
yes - it has to stop at *"as" * if you add an extra *"s"* so that is ends
as *"ass"*, you end up with a HTTP 500

**Comment by JPH71** [comment]
This will work
https://fagalicious.com/search/Cole+Blue+gets+his+as

This won't
https://fagalicious.com/search/Cole+Blue+gets+his+ass

**Comment by fivedays555** [comment]
@JPH71 Thanks for your explain...

How about the following link......I got HTTP ERROR 500 for it.

https://fagalicious.com/search/Cole+Blue+ass

**Comment by JPH71** [comment]
That works for me as you can see
[image: image.png]

But why would you do that when matching with the agent....
The agent is picking the first 21 characters of the title... so if you
named the video (Masonic Boys) - Cole Blue Ass Spanked and Plugged by Felix
Kamp in "Disciplinary Action" (2021) it would fail to match as that title
does not exist in fagalicious.

The search can contain upto 21 characters of any of the words in the
title..... most likely in the order they appear in the title...

Jason

**Comment by fivedays555** [comment]
Strangely, it works now.......for https://fagalicious.com/search/Cole+Blue+ass. 
Their server is weird... or I am. Lol

You are right about file naming. Let's change a keyword to "bareback", which will most likely be there in the first 21 characters. 
The following link would return a 500 error for me for now at least. 

https://fagalicious.com/search/Cole+Blue+bareback

**Comment by JPH71** [comment]
And correctly so - the website is returning a 500 because it can not get a
result from that search string

Strangely, it works now.......for
https://fagalicious.com/search/Cole+Blue+ass. - that  would work - all
three words are in the search string and the total length of the search
string is under 21 characters....

But remember - the search string is made up of the first 21 characters of
the Title! not just arbitrary words from the title that fit within 21
characters


Jason

**Comment by fivedays555** [comment]
Yeah, you are right. 

I need to consider using another agent as fagalicious is quite strange. Thanks for your patience. I know these things could be so tedious. 

Cheers!

**Comment by JPH71** [comment]
I tend to use WayBig and Best Exclusive more

Queer Click also seems to work quite well...

If you come across owt strange - let us know!

Jason

**Comment by CodyBerenson** [comment]
Sorry that Jason got y'alls hopes up, but his fix doesn't work on the original title in this issue.

**Comment by CodyBerenson** [comment]
> 
> 
> Here are some links for you to check:
> 
> 2021-04-20 15:19:40,510 (b168) : ERROR (networking:196) - Error opening URL 'https://fagalicious.com/search/kevin+daley+and+cameron+parks+fuck+angel+rivera'
> 2021-04-20 15:19:40,512 (b168) : ERROR (logkit:22) - Fagalicious - SEARCH:: Error: Search Query did not pull any results: HTTP Error 500: Internal Server Error
> 
> 2021-04-20 15:23:37,948 (bcf8) : ERROR (networking:196) - Error opening URL 'https://fagalicious.com/search/kieran+%26+jayce+flip+fuck'
> 2021-04-20 15:23:37,948 (bcf8) : ERROR (logkit:22) - Fagalicious - SEARCH:: Error: Search Query did not pull any results: HTTP Error 500: Internal Server Error
> 
> 2021-04-20 15:24:23,776 (bd84) : ERROR (networking:196) - Error opening URL 'https://fagalicious.com/search/kevin+texas+fucks+james+dawn+raw'
> 2021-04-20 15:24:23,776 (bd84) : ERROR (logkit:22) - Fagalicious - SEARCH:: Error: Search Query did not pull any results: HTTP Error 500: Internal Server Error
> 
> 2021-04-20 14:57:41,135 (b8c0) : ERROR (networking:196) - Error opening URL 'https://fagalicious.com/search/kaleb+stryker+and+justin+matthews+flip+fuck+in'
> 2021-04-20 14:57:41,137 (b8c0) : ERROR (logkit:22) - Fagalicious - SEARCH:: Error: Search Query did not pull any results: HTTP Error 500: Internal Server Error
> 
> 2021-04-20 15:00:18,233 (ba10) : ERROR (networking:196) - Error opening URL 'https://fagalicious.com/search/kaleb+stryker+and+nic+sahara+flip+fuck+in'
> 2021-04-20 15:00:18,233 (ba10) : ERROR (logkit:22) - Fagalicious - SEARCH:: Error: Search Query did not pull any results: HTTP Error 500: Internal Server Error
> 
> 2021-04-20 15:09:57,615 (bc08) : ERROR (networking:196) - Error opening URL 'https://fagalicious.com/search/kennedy+%26+kellan+%28+flip+fuck'
> 2021-04-20 15:09:57,615 (bc08) : ERROR (logkit:22) - Fagalicious - SEARCH:: Error: Search Query did not pull any results: HTTP Error 500: Internal Server Error
> 
> 2021-04-20 15:11:19,407 (47dc) : ERROR (networking:196) - Error opening URL 'https://fagalicious.com/search/kent+%26+kellan+%28fuck+buddies%29+%28'
> 2021-04-20 15:11:19,407 (47dc) : ERROR (logkit:22) - Fagalicious - SEARCH:: Error: Search Query did not pull any results: HTTP Error 500: Internal Server Error

@fivedays555....i'm a big confused.  I looked at every Angel Rivera title on Fagalicious.  The title you reference doesn't exist.  I then checked every James Dawn title on Fagalicious.  Similarly the title you reference isn't indexed on Fagalicious.

**Comment by fivedays555** [comment]
@CodyBerenson You are right. I just pulled out whatever is caused an HTTP Error 500: Internal Server Error from the log file. If it doesn't exist, at least it should return a 200 response with 0 result listed. Here is a normal response:

2021-04-21 16:59:24,657 (32d8) :  INFO (logkit:16) - Fagalicious  - ------------------------------------------------------------------------------
2021-04-21 16:59:24,657 (32d8) :  INFO (logkit:16) - Fagalicious  - AGNT  :: Original Search Query        : Roman Todd Fucks Zayne Hardy in 'Revolt' Part 2
2021-04-21 16:59:24,657 (32d8) :  INFO (logkit:16) - Fagalicious  - AGNT  :: Search Query:: String has none of these (‘|’)
2021-04-21 16:59:24,658 (32d8) :  INFO (logkit:16) - Fagalicious  - AGNT  :: Search Query:: String has none of these (,|-|‑|‒|–|—)
2021-04-21 16:59:24,658 (32d8) :  INFO (logkit:16) - Fagalicious  - AGNT  :: Search Query:: First character has none of these ('|"|`|“|”|‘|’)
2021-04-21 16:59:24,660 (32d8) :  INFO (logkit:16) - Fagalicious  - AGNT  :: Search Query:: Splitting at position [32]. Found one of these ('|"|`|“|”|‘|’)
2021-04-21 16:59:24,660 (32d8) :  INFO (logkit:16) - Fagalicious  - AGNT  :: Returned Search Query        : roman+todd+fucks+zayne+hardy+in
2021-04-21 16:59:24,661 (32d8) :  INFO (logkit:16) - Fagalicious  - ------------------------------------------------------------------------------
2021-04-21 16:59:24,661 (32d8) :  INFO (logkit:16) - Fagalicious  - SEARCH:: Search Query: https://fagalicious.com/search/roman+todd+fucks+zayne+hardy+in
2021-04-21 16:59:24,726 (32d8) :  DEBUG (networking:143) - Requesting 'https://fagalicious.com/search/roman+todd+fucks+zayne+hardy+in'
2021-04-21 16:59:42,352 (32d8) :  INFO (logkit:16) - Fagalicious  - SEARCH:: No More Pages Found
2021-04-21 16:59:42,354 (32d8) :  INFO (logkit:16) - Fagalicious  - SEARCH:: Result Page No: 1, Titles Found 0

**Comment by JPH71** [comment]
Hi cody - fixed that issue...
Fagalicious still can not search beyond 21 characters...
Sometimes it lets the last word be cut off at the 21 character..
I have now made it to cut the title at the last space before 21 chars - so
that instead of it searching on Brandon Anderson fuck
<https://fagalicious.com/next-door-taboo-brandon-anderson-fucks-chris-blades-get-in-deeper-bro/>
it
will now search on
Brandon Anderson
<https://fagalicious.com/next-door-taboo-brandon-anderson-fucks-chris-blades-get-in-deeper-bro/>

this worked!

Sending you the fix!

**Comment by CodyBerenson** [comment]
@fivedays555 similarly re: the last two entries.  There are two titles with kennedy and kellan, but neither having anything to do with "flip fuck" and there are two titles with kent and kellan but neither having anything to do with "fuck buddies"

I don't mean for this to sound rude so please, please don't take offense.  One must match the scene to the specific blog.  A scene may have a specific title given to it from the original studio or torrent, but the file must be named to the specific entry on the specific blog (waybig or fagalicious or queerclick or bestexclusive).  And the same scene may in fact be on all blogs with very different titles.  You have to name the file using the file naming conventions matched to the specific blog you're trying to match to.  There is no "Kent & kellen: fuck buddies" on fagalicious, so it would never match, period.   That is the name of the entry on  on WayBig, not Fagalacious.  I hope this makes sense.

**Comment by fivedays555** [comment]
Again, I am not thinking this is an agent's fault. I think it is more likely Fagalicious's server's fault. They did not handle their search query properly.

**Comment by CodyBerenson** [comment]
@fivedays555 please look at my last response.  I don't believe you're using the agents correctly.  You're looking for titles on blogs that do not exist and will therefore never match.

**Comment by JPH71** [comment]
@fivedays555* - *you are right about it returning a 200 response with no
results.... but fagalicious is behaving strangely - this may be a way for
them to stop scraping..

**Comment by fivedays555** [comment]
@CodyBerenson Thanks for your explanation. I understand how I should use the agents. I turn on both Fagalicious and Waybig agents in the agent tab, so I am not sure which title should match by which agent when I look at all the logs. I understand some or all of them may not match. I just try to show @JPH71 that fagalicious is returning some 500 errors that may worth looking into.

**Comment by CodyBerenson** [comment]
folks, stop.  @fivedays555 has taken WayBig titles, and thrown them against fagalicious.  it doesn't work that way.  @fivedays555 please see the guide for usage.

![image](https://user-images.githubusercontent.com/40373801/115637359-fa8dc800-a2dd-11eb-83b9-05d15b50f5ef.png)

![image](https://user-images.githubusercontent.com/40373801/115637552-65d79a00-a2de-11eb-8e66-1676df3acbd7.png)

**Comment by CodyBerenson** [comment]
An agent not matching a title that doesn't exist on an index site isn't a problem that Jason should be looking into.  Not for one moment.

If you have a true title that is unable to be matched, please open an issue as @j-ktz does.

**Comment by fivedays555** [comment]
@CodyBerenson Yep. Understood. ; )
