### ISSUE TITLE
Some small issues.

### ISSUE THREAD

**Issue by fivedays555** [CodyBerenson/PGMA-Modernized#94]
Hi there, it is me again. I ran through my library and most of them are working perfectly, so thank you for making these great agents! Here is just a list of small issues I ran into. Should be an easy fix for our amazing coder. ; )

- Error: Filename overrides Media Title in searching query. Cannot perform "fix match" when needed.

    *2021-04-22* *17:52:42,045* (d7f0) :  INFO (logkit:16) - WayBig  - SEARCH:: Media Title                  : Caleb King Gets His First DP By Koldo Goran And Franklin Acevedo

    *2021-04-22* *17:52:42,045* (d7f0) :  INFO (logkit:16) - WayBig  - SEARCH:: File Name                    : (Tim Tales) - Caleb King gets double penetrated by Koldo Goran and Franklin Acevedo (2018)

    *2021-04-22* *17:52:42,046* (d7f0) :  INFO (logkit:16) - WayBig  - SEARCH:: File Folder                  : J:\$Fivedays\[Data]\Tim Tales - Caleb King gets double penetrated by Koldo Goran and Franklin Acevedo

    *2021-04-22* *17:52:42,046* (d7f0) :  INFO (logkit:16) - WayBig  - ------------------------------------------------------------------------------

    *2021-04-22* *17:52:42,046* (d7f0) :  INFO (logkit:16) - WayBig  - GENF  :: Film Dictionary Variables:

    *2021-04-22* *17:52:42,048* (d7f0) :  INFO (logkit:16) - WayBig  - GENF  :: Collection                   : []

    *2021-04-22* *17:52:42,048* (d7f0) :  INFO (logkit:16) - WayBig  - GENF  :: CompareDate                  : December 31, 2018

    *2021-04-22* *17:52:42,049* (d7f0) :  INFO (logkit:16) - WayBig  - GENF  :: CompareIAFDStudio            :

    *2021-04-22* *17:52:42,049* (d7f0) :  INFO (logkit:16) - WayBig  - GENF  :: CompareStudio                : timtales

    *2021-04-22* *17:52:42,049* (d7f0) :  INFO (logkit:16) - WayBig  - GENF  :: CompareTitle                 : ['aaaaaabbbccdddddeeeeeeeefgggiikkkllllnnnnnnoooooprrrstttuvy']

    *2021-04-22* *17:52:42,051* (d7f0) :  INFO (logkit:16) - WayBig  - GENF  :: Compilation                  : No

    *2021-04-22* *17:52:42,051* (d7f0) :  INFO (logkit:16) - WayBig  - GENF  :: FoundOnIAFD                  : No

    *2021-04-22* *17:52:42,052* (d7f0) :  INFO (logkit:16) - WayBig  - GENF  :: IAFDCompareTitle             : ['aaaaaabbbccdddddeeeeeeeefgggiikkkllllnnnnnnoooooprrrstttuvy']

    *2021-04-22* *17:52:42,052* (d7f0) :  INFO (logkit:16) - WayBig  - GENF  :: IAFDSearchTitle              : Caleb+King+gets+double+penetrated+by+Koldo+Goran+and+Franklin+Acevedo

    *2021-04-22* *17:52:42,052* (d7f0) :  INFO (logkit:16) - WayBig  - GENF  :: IAFDShortTitle               : Caleb King gets double penetrated by Koldo Goran and Franklin Acevedo

    *2021-04-22* *17:52:42,052* (d7f0) :  INFO (logkit:16) - WayBig  - GENF  :: IAFDStudio                   :

    *2021-04-22* *17:52:42,053* (d7f0) :  INFO (logkit:16) - WayBig  - GENF  :: IAFDTitle                    : Caleb King gets double penetrated by Koldo Goran and Franklin Acevedo

    *2021-04-22* *17:52:42,053* (d7f0) :  INFO (logkit:16) - WayBig  - GENF  :: SearchTitle                  : Caleb King gets double penetrated by Koldo Goran and Franklin Acevedo

    *2021-04-22* *17:52:42,053* (d7f0) :  INFO (logkit:16) - WayBig  - GENF  :: Series                       : []

    *2021-04-22* *17:52:42,055* (d7f0) :  INFO (logkit:16) - WayBig  - GENF  :: ShortTitle                   : Caleb King gets double penetrated by Koldo Goran and Franklin Acevedo

    *2021-04-22* *17:52:42,055* (d7f0) :  INFO (logkit:16) - WayBig  - GENF  :: Studio                       : Tim Tales

    *2021-04-22* *17:52:42,055* (d7f0) :  INFO (logkit:16) - WayBig  - GENF  :: Title                        : Caleb King gets double penetrated by Koldo Goran and Franklin Acevedo

    *2021-04-22* *17:52:42,055* (d7f0) :  INFO (logkit:16) - WayBig  - GENF  :: Year                         : 2018

    *2021-04-22* *17:52:42,056* (d7f0) :  INFO (logkit:16) - WayBig  - ------------------------------------------------------------------------------

    *2021-04-22* *17:52:42,056* (d7f0) :  INFO (logkit:16) - WayBig  - AGNT  :: Original Search Query        : Caleb King gets double penetrated by Koldo Goran and Franklin Acevedo

    *2021-04-22* *17:52:42,058* (d7f0) :  INFO (logkit:16) - WayBig  - AGNT  :: Search Query:: String has none of these (‘|’)

    *2021-04-22* *17:52:42,058* (d7f0) :  INFO (logkit:16) - WayBig  - AGNT  :: Search Query:: First word has none of these ('|"|`|“|”|‘|’)

    *2021-04-22* *17:52:42,059* (d7f0) :  INFO (logkit:16) - WayBig  - AGNT  :: Search Query:: First character has none of these ('|"|`|“|”|‘|’)

    *2021-04-22* *17:52:42,059* (d7f0) :  INFO (logkit:16) - WayBig  - AGNT  :: Search Query:: Split not attempted. String has none of these ('|"|`|“|”|‘|’)

    *2021-04-22* *17:52:42,059* (d7f0) :  INFO (logkit:16) - WayBig  - AGNT  :: Returned Search Query        : caleb+king+gets+double+penetrated+by+koldo+goran+a

---

Why Not Bi? Michael DelRay, Trent King And Summer Hart In “Let’s Talk About Ass”

[https://www.waybig.com/blog/2019/07/12/why-not-bi-michael-delray-trent-king-summer-hart-talk-about-ass/](https://www.waybig.com/blog/2019/07/12/why-not-bi-michael-delray-trent-king-summer-hart-talk-about-ass/)

Error: SEARCH:: Error determining Site Studio and Title from Site Entry

Reason: Waybig blog title used a "?" for a studio separator.

---

Young Perps, Case # 1811048-36 (Feat Dante Drackis And Greg McKeon)

[https://www.waybig.com/blog/2018/11/08/young-perps-case-1811048-36-dante-drackis-greg-mckeon/](https://www.waybig.com/blog/2018/11/08/young-perps-case-1811048-36-dante-drackis-greg-mckeon/)

Error: SEARCH:: Error determining Site Studio and Title from Site Entry

Reason: Waybig blog title used a "," for a studio separator.

---

DallasReeves: Vadim Black’s Bareback Threesome With Donny & Johnny Forza

[https://www.waybig.com/blog/2014/07/08/dallasreeves-vadim-blacks-bareback-threesome-with-donny-johnny-forza/](https://www.waybig.com/blog/2014/07/08/dallasreeves-vadim-blacks-bareback-threesome-with-donny-johnny-forza/)

Error: Not Matched

Reason: There is an "'s" in the title. Search query becomes Vadim Black (stopped at "'"). Did not find a match. I would suggest removing "'s" and replace "s'" with "s".

---

(MEN) - DeAngelo Jackson and Joey Mills Fuck Ty Mitchell in ‘Top Of The Fair Ass Wheel - Bareback’ (2020)

[https://www.waybig.com/blog/2020/04/15/men-bareback-deangelo-jackson-joey-mills-ty-mitchell-top-of-the-fair-ass-wheel/](https://www.waybig.com/blog/2020/04/15/men-bareback-deangelo-jackson-joey-mills-ty-mitchell-top-of-the-fair-ass-wheel/)

*2021-04-22* *14:36:12,792* (b204) :  INFO (logkit:16) - WayBig  - SEARCH:: File Name                    : (MEN) - DeAngelo Jackson and Joey Mills Fuck Ty Mitchell in ‘Top Of The Fair Ass Wheel - Bareback’ (2020)

*2021-04-22* *14:36:12,793* (b204) :  INFO (logkit:16) - WayBig  - SEARCH:: File Folder                  : K:\[Data]\MEN - DeAngelo Jackson and Joey Mills Fuck Ty Mitchell in ‘Top Of The Fair Ass Wheel - Bareback’

*2021-04-22* *14:36:12,793* (b204) :  INFO (logkit:16) - WayBig  - ------------------------------------------------------------------------------

*2021-04-22* *14:36:12,802* (b204) :  INFO (logkit:16) - WayBig  - GENF  :: Film Dictionary Variables:

*2021-04-22* *14:36:12,802* (b204) :  INFO (logkit:16) - WayBig  - GENF  :: Collection                   : []

*2021-04-22* *14:36:12,803* (b204) :  INFO (logkit:16) - WayBig  - GENF  :: CompareDate                  : December 31, 2020

*2021-04-22* *14:36:12,803* (b204) :  INFO (logkit:16) - WayBig  - GENF  :: CompareIAFDStudio            :

*2021-04-22* *14:36:12,803* (b204) :  INFO (logkit:16) - WayBig  - GENF  :: CompareStudio                : men

*2021-04-22* *14:36:12,803* (b204) :  INFO (logkit:16) - WayBig  - GENF  :: CompareTitle                 : ['aaaaaaabbccccddeeeeeeeefffghhhiiiijjkkkllllllmmnnnnoooooprrssssttttuwyy', 'aabbcekr']

*2021-04-22* *14:36:12,805* (b204) :  INFO (logkit:16) - WayBig  - GENF  :: Compilation                  : No

*2021-04-22* *14:36:12,805* (b204) :  INFO (logkit:16) - WayBig  - GENF  :: FoundOnIAFD                  : No

*2021-04-22* *14:36:12,805* (b204) :  INFO (logkit:16) - WayBig  - GENF  :: IAFDCompareTitle             : ['aaaaaaabbccccddeeeeeeeefffghhhiiiijjkkkllllllmmnnnnoooooprrssssttttuwyy', 'aabbcekr']

*2021-04-22* *14:36:12,805* (b204) :  INFO (logkit:16) - WayBig  - GENF  :: IAFDSearchTitle              : Bareback

*2021-04-22* *14:36:12,805* (b204) :  INFO (logkit:16) - WayBig  - GENF  :: IAFDShortTitle               : DeAngelo Jackson and Joey Mills Fuck Ty Mitchell in 'Top Of The Fair Ass Wheel - Bareback'

*2021-04-22* *14:36:12,805* (b204) :  INFO (logkit:16) - WayBig  - GENF  :: IAFDStudio                   :

*2021-04-22* *14:36:12,805* (b204) :  INFO (logkit:16) - WayBig  - GENF  :: IAFDTitle                    : Bareback

*2021-04-22* *14:36:12,805* (b204) :  INFO (logkit:16) - WayBig  - GENF  :: SearchTitle                  : Bareback

*2021-04-22* *14:36:12,806* (b204) :  INFO (logkit:16) - WayBig  - GENF  :: Series                       : []

*2021-04-22* *14:36:12,806* (b204) :  INFO (logkit:16) - WayBig  - GENF  :: ShortTitle                   : Bareback

*2021-04-22* *14:36:12,806* (b204) :  INFO (logkit:16) - WayBig  - GENF  :: Studio                       : MEN

*2021-04-22* *14:36:12,808* (b204) :  INFO (logkit:16) - WayBig  - GENF  :: Title                        : DeAngelo Jackson and Joey Mills Fuck Ty Mitchell in 'Top Of The Fair Ass Wheel - Bareback'

*2021-04-22* *14:36:12,808* (b204) :  INFO (logkit:16) - WayBig  - GENF  :: Year                         : 2020

*2021-04-22* *14:36:12,808* (b204) :  INFO (logkit:16) - WayBig  - ------------------------------------------------------------------------------

*2021-04-22* *14:36:12,808* (b204) :  INFO (logkit:16) - WayBig  - AGNT  :: Original Search Query        : Bareback

*2021-04-22* *14:36:12,809* (b204) :  INFO (logkit:16) - WayBig  - AGNT  :: Search Query:: String has none of these (‘|’)

*2021-04-22* *14:36:12,809* (b204) :  INFO (logkit:16) - WayBig  - AGNT  :: Search Query:: First word has none of these ('|"|`|“|”|‘|’)

*2021-04-22* *14:36:12,809* (b204) :  INFO (logkit:16) - WayBig  - AGNT  :: Search Query:: First character has none of these ('|"|`|“|”|‘|’)

*2021-04-22* *14:36:12,809* (b204) :  INFO (logkit:16) - WayBig  - AGNT  :: Search Query:: Split not attempted. String has none of these ('|"|`|“|”|‘|’)

*2021-04-22* *14:36:12,809* (b204) :  INFO (logkit:16) - WayBig  - AGNT  :: Returned Search Query        : bareback

Error: Search Query is bareback. 

Reason: not sure what happened here. Seems like IAFD return the wrong title?

---

(Lucas Entertainment) - Tomas Brand Tops Cody Winter Bareback in ‘Bareback Auditions 8’ Scene 3 (2017)

[https://www.waybig.com/blog/2017/09/18/tomas-brand-tops-cody-winter-bareback-in-bareback-auditions-8-scene-3-at-lucas-entertainment/](https://www.waybig.com/blog/2017/09/18/tomas-brand-tops-cody-winter-bareback-in-bareback-auditions-8-scene-3-at-lucas-entertainment/)

Error: Error determining Site Studio and Title from Site Entry

Reason: Studio separator is "at", which is at the siteEntry[-3].

---

(Twink Top) - Austin Young, Dale Savage, Dallas Steele, Felix Maze and Lukas Stone in ‘Felix’s Team Play - All Play’ (2020)

[https://www.waybig.com/blog/2020/03/28/twinktop-austin-young-dale-savage-dallas-steele-felix-maze-lukas-stone-felix-team-play/](https://www.waybig.com/blog/2020/03/28/twinktop-austin-young-dale-savage-dallas-steele-felix-maze-lukas-stone-felix-team-play/)

*2021-04-22* *14:56:27,013* (367c) :  INFO (logkit:16) - WayBig  - SEARCH:: Media Title                  : Twink Top Austin Young, Dale Savage, Dallas Steele, Felix Maze and Lukas Stone in ‘Felix’s Team Play All Play’

*2021-04-22* *14:56:27,013* (367c) :  INFO (logkit:16) - WayBig  - SEARCH:: File Name                    : (Twink Top) - Austin Young, Dale Savage, Dallas Steele, Felix Maze and Lukas Stone in ‘Felix’s Team Play - All Play’ (2020)

*2021-04-22* *14:56:27,013* (367c) :  INFO (logkit:16) - WayBig  - SEARCH:: File Folder                  : K:\[Data]\Twink Top - Austin Young, Dale Savage, Dallas Steele, Felix Maze and Lukas Stone in ‘Felix’s Team Play - All Play’

*2021-04-22* *14:56:27,013* (367c) :  INFO (logkit:16) - WayBig  - ------------------------------------------------------------------------------

*2021-04-22* *14:56:27,020* (367c) :  INFO (logkit:16) - WayBig  - GENF  :: Film Dictionary Variables:

*2021-04-22* *14:56:27,022* (367c) :  INFO (logkit:16) - WayBig  - GENF  :: Collection                   : []

*2021-04-22* *14:56:27,022* (367c) :  INFO (logkit:16) - WayBig  - GENF  :: CompareDate                  : December 31, 2020

*2021-04-22* *14:56:27,023* (367c) :  INFO (logkit:16) - WayBig  - GENF  :: CompareIAFDStudio            :

*2021-04-22* *14:56:27,023* (367c) :  INFO (logkit:16) - WayBig  - GENF  :: CompareStudio                : twinktop

*2021-04-22* *14:56:27,023* (367c) :  INFO (logkit:16) - WayBig  - GENF  :: CompareTitle                 : ['aalllpy', 'aaaaaaaaaaaaadddeeeeeeeeeeffggiiiiklllllllllllmmnnnnnooppsssssssttttuuuvxxyyyz']

*2021-04-22* *14:56:27,023* (367c) :  INFO (logkit:16) - WayBig  - GENF  :: Compilation                  : No

*2021-04-22* *14:56:27,023* (367c) :  INFO (logkit:16) - WayBig  - GENF  :: FoundOnIAFD                  : No

*2021-04-22* *14:56:27,023* (367c) :  INFO (logkit:16) - WayBig  - GENF  :: IAFDCompareTitle             : ['aalllpy', 'aaaaaaaaaaaaadddeeeeeeeeeeffggiiiiklllllllllllmmnnnnnooppsssssssttttuuuvxxyyyz']

*2021-04-22* *14:56:27,025* (367c) :  INFO (logkit:16) - WayBig  - GENF  :: IAFDSearchTitle              : All+Play

*2021-04-22* *14:56:27,025* (367c) :  INFO (logkit:16) - WayBig  - GENF  :: IAFDShortTitle               : Austin Young, Dale Savage, Dallas Steele, Felix Maze and Lukas Stone in 'Felix's Team Play - All Play'

*2021-04-22* *14:56:27,025* (367c) :  INFO (logkit:16) - WayBig  - GENF  :: IAFDStudio                   :

*2021-04-22* *14:56:27,026* (367c) :  INFO (logkit:16) - WayBig  - GENF  :: IAFDTitle                    : All Play

*2021-04-22* *14:56:27,026* (367c) :  INFO (logkit:16) - WayBig  - GENF  :: SearchTitle                  : All Play

*2021-04-22* *14:56:27,026* (367c) :  INFO (logkit:16) - WayBig  - GENF  :: Series                       : []

*2021-04-22* *14:56:27,026* (367c) :  INFO (logkit:16) - WayBig  - GENF  :: ShortTitle                   : All Play

*2021-04-22* *14:56:27,026* (367c) :  INFO (logkit:16) - WayBig  - GENF  :: Studio                       : Twink Top

*2021-04-22* *14:56:27,026* (367c) :  INFO (logkit:16) - WayBig  - GENF  :: Title                        : Austin Young, Dale Savage, Dallas Steele, Felix Maze and Lukas Stone in 'Felix's Team Play - All Play'

*2021-04-22* *14:56:27,026* (367c) :  INFO (logkit:16) - WayBig  - GENF  :: Year                         : 2020

*2021-04-22* *14:56:27,028* (367c) :  INFO (logkit:16) - WayBig  - ------------------------------------------------------------------------------

*2021-04-22* *14:56:27,028* (367c) :  INFO (logkit:16) - WayBig  - AGNT  :: Original Search Query        : All Play

*2021-04-22* *14:56:27,029* (367c) :  INFO (logkit:16) - WayBig  - AGNT  :: Search Query:: String has none of these (‘|’)

*2021-04-22* *14:56:27,029* (367c) :  INFO (logkit:16) - WayBig  - AGNT  :: Search Query:: First word has none of these ('|"|`|“|”|‘|’)

*2021-04-22* *14:56:27,029* (367c) :  INFO (logkit:16) - WayBig  - AGNT  :: Search Query:: First character has none of these ('|"|`|“|”|‘|’)

*2021-04-22* *14:56:27,029* (367c) :  INFO (logkit:16) - WayBig  - AGNT  :: Search Query:: Split not attempted. String has none of these ('|"|`|“|”|‘|’)

*2021-04-22* *14:56:27,030* (367c) :  INFO (logkit:16) - WayBig  - AGNT  :: Returned Search Query        : all+play

Error: Search Query is all+play. 

Reason: not sure what happened here. Seems like IAFD return the wrong title?

---

**Comment by CodyBerenson** [comment]
@fivedays555 
Hope this finds you well.  When opening a new issue, We just need 1) the link to the blog that you're trying to match, and 2) the corresponding Agent's log as an attachment...per the FAQ:  "(i.e. if the film is on AEBN, please include the com.plexapp.agents.AEBN.log.)"  It would be more efficient to us if you take a look at how @J-KTZ opens issues (e.g., #89).   

Specific to the 7 scenes you point out above, three match when named properly.  The first you've just mistakenly named the file, probably to a title in a blog other than WayBig.  The 2nd two you properly followed the "replace colons with dashes" rule, but for some reason it won't now match with a dash....when you leave the dash out it matches fine:

(TimTales) - Caleb King Gets His First DP by Koldo Goran and Franklin Acevedo (2018)
(TwinkTop Orgy) - Austin Young, Dale Savage, Dallas Steele, Felix Maze and Lukas Stone in ‘Felix’s Team Play All Play’ (2020)
(MEN) - DeAngelo Jackson and Joey Mills Fuck Ty Mitchell in ‘Top Of The Fair Ass Wheel Bareback’ (2020)

![image](https://user-images.githubusercontent.com/40373801/115956688-41d9ab80-a4cc-11eb-957a-e343683f95f4.png)

@JPH71
Please look into the following scenes.  FYI, at some point in the past the first two had previously matched in my library but now do not.  

1.
https://www.waybig.com/blog/2018/11/08/young-perps-case-1811048-36-dante-drackis-greg-mckeon/
FYI This matched previously in my library when named: (Young Perps) - Young Perps, Case # 1811048-36 (feat Dante Drackis and Greg McKeon) (2018).mp4 

2.
https://www.waybig.com/blog/2017/09/18/tomas-brand-tops-cody-winter-bareback-in-bareback-auditions-8-scene-3-at-lucas-entertainment/
FYI this matched previously in my library when named: (Lucas Entertainment) - Tomas Brand Tops Cody Winter Bareback in 'Bareback Auditions 8' Scene 3 (2017).mp4 

3.
https://www.waybig.com/blog/2014/07/08/dallasreeves-vadim-blacks-bareback-threesome-with-donny-johnny-forza/

4.
https://www.waybig.com/blog/2019/07/12/why-not-bi-michael-delray-trent-king-summer-hart-talk-about-ass/

5. and 6.
FYI:  when one does not follow the "replace colon with dash" rule these titles match fine.  when a dash is included to replace the second colon, the title will not match.

https://www.waybig.com/blog/2020/03/28/twinktop-austin-young-dale-savage-dallas-steele-felix-maze-lukas-stone-felix-team-play/
https://www.waybig.com/blog/2020/04/15/men-bareback-deangelo-jackson-joey-mills-ty-mitchell-top-of-the-fair-ass-wheel/

**Comment by CodyBerenson** [comment]
@JPH71 
Although the fixes to the WayBig agent causes the above 7 titles to correctly match, this version of WayBig now fails with IAFD.  I took a look in GitHub and see that you've removed utils.py, which had the cloudscraping fixes, and adding the bunch of other libraries, not sure why....but I can't push this or folks will stop getting actors photos, etc..

![image](https://user-images.githubusercontent.com/40373801/116490897-8cf61480-a866-11eb-9628-f72ca1853370.png)

![image](https://user-images.githubusercontent.com/40373801/116490441-65eb1300-a865-11eb-922c-7526f4df403a.png)
