### ISSUE TITLE
Thumbor Address requires Updating!!

### ISSUE THREAD

**Issue by CodyBerenson** [CodyBerenson/PGMA-Modernized#95]
Hi folks,

The address for Thumbor, the service which crops Scene Blog posters when needed, needs to be updated. The current address will cease to work momentarily.  You can update it yourself now, or install the updated Scene agents that will be posted shortly.  To do that now, go into the settings for each Scene agent and update the IP Address to 34.68.158.72:

![image](https://user-images.githubusercontent.com/40373801/116271682-35648580-a74e-11eb-9e3e-66436ef78c7d.png)

After you update, you probably need to stop and restart your PMS.

Cheers.

**Comment by CodyBerenson** [comment]
@JPH71 
Hi Jason,

The scene agents preferences have all been updated with the new Thumbor address.  Here's hoping this address says as consistent/persistent as the last.

Please be sure to grab the latest scene agents for your code base when making future changes to them.  

Cody

**Comment by JPH71** [comment]
I update them yesterday when you sent out the mail... the lates waybig I
sent you has the new address in it

Jason
